[triggers]

	[[triggers.mob]]
		identifier = "taint"
		resource_name = [ "Taintacle" ]
		detection_range = "40"
		mob_targeting = false
		level = "1"
		priority = "10"
		[[triggers.dimension]]
		identifier = "overworld"
		resource_name = ["0"]

	
[songs]
[songs.kevinmcleod_giantwyrm]
		triggers = [ "mob-taint" ]

[songs.kevinmcleod_martiancowboy]
		triggers = [ "mob-taint" ]
		volume = "1.0"

[songs.chriszabriskie_whatdoesanybodyknowaboutanything]
		triggers = [ "mob-taint" ]

[songs.kevinmcleod_bluesizzle]
		triggers = [ "dimension-overworld" ]

[songs.kevinmcleod_thedread]
		triggers = [ "dimension-overworld" ]

[songs.kevinmcleod_itislost]
		triggers = [ "dimension-overworld" ]







