#  Main header!
#  Line 2

[songs]
	[songs.chriszabriskie_whatdoesanybodyknowaboutanything]
		triggers = [ "mob-taint" ]
	[songs.kevinmcleod_bluesizzle]
		triggers = [ "dimension-overworld" ]
	[songs.kevinmcleod_giantwyrm]
		triggers = [ "mob-taint" ]
	[songs.kevinmcleod_itislost]
		triggers = [ "dimension-overworld" ]
	[songs.kevinmcleod_martiancowboy]
		triggers = [ "mob-taint" ]
		volume = "1.0"
	[songs.kevinmcleod_thedread]
		triggers = [ "dimension-overworld" ]

[triggers]
	[triggers.dimension]
		identifier = "overworld"
		resource_name = [ "0" ]
	[triggers.mob]
		detection_range = "40"
		identifier = "taint"
		level = "1"
		mob_targeting = false
		priority = "10"
		resource_name = [ "Taintacle" ]
	[triggers.universal]
		active_cooldown = "0"
		fade_in = "0"
		fade_out = "0"
		persistence = "0"
		ticks_before_active = "0"
		ticks_before_audio = "0"
		ticks_between_audio = "0"

