mods.immersiveengineering.Excavator.addMineral("Quartz", 20, 0.005, ["gemQuartz", "gemSatinspar"], [0.95, 0.05]);
mods.immersiveengineering.Excavator.addMineral("Hematite", 10, 0.005, ["oreHematitePoor", "oreHematiteNormal", "oreHematiteRich"], [0.6, 0.3, 0.1]);
mods.immersiveengineering.Excavator.addMineral("Magnetite", 10, 0.005, ["oreMagnetitePoor", "oreMagnetiteNormal", "oreMagnetiteRich"], [0.6, 0.3, 0.1]);
mods.immersiveengineering.Excavator.addMineral("Limonite", 10, 0.005, ["oreLimonitePoor", "oreLimoniteNormal", "oreLimoniteRich"], [0.6, 0.3, 0.1]);
mods.immersiveengineering.Excavator.addMineral("Coal", 10, 0.005, ["Coal", "gemDiamondChipped", "gemDiamondFlawed", "gemRubyChipped", "gemRubyFlawed", "gemEmeraldChipped", "gemEmeraldFlawed"], [0.95, 0.01, 0.0066, 0.01, 0.0067, 0.01, 0.0067]);
mods.immersiveengineering.Excavator.addMineral("Bituminous Coal", 20, 0.005, ["mineralBituminousCoal"], [1]);
mods.immersiveengineering.Excavator.addMineral("Lignite", 20, 0.005, ["gemLignite"], [1]);
mods.immersiveengineering.Excavator.addMineral("Native Copper", 10, 0.005, ["oreNativeCopperPoor", "oreNativeCopperNormal", "oreNativeCopperRich"], [0.6, 0.3, 0.1]);
mods.immersiveengineering.Excavator.addMineral("Tetrahedrite", 10, 0.005, ["oreTetrahedritePoor", "oreTetrahedriteNormal", "oreTetrahedriteRich"], [0.6, 0.3, 0.1]);
mods.immersiveengineering.Excavator.addMineral("Malachite", 10, 0.005, ["oreMalachitePoor", "oreMalachiteNormal", "oreMalachiteRich"], [0.6, 0.3, 0.1]);
mods.immersiveengineering.Excavator.addMineral("Cassiterite", 20, 0.005, ["oreTinPoor", "oreTinNormal", "oreTinRich"], [0.6, 0.3, 0.1]);
mods.immersiveengineering.Excavator.addMineral("Bismuthinite", 20, 0.005, ["oreBismuthPoor", "oreBismuthNormal", "oreBismuthRich"], [0.6, 0.3, 0.1]);
mods.immersiveengineering.Excavator.addMineral("Native Gold", 10, 0.005, ["oreGoldPoor", "oreGoldNormal", "oreGoldRich", "oreTetrahedritePoor", "oreTetrahedriteNormal", "oreTetrahedriteRich", "oreLeadPoor", "oreLeadNormal", "oreLeadRich"], [0.45, 0.15, 0.05, 0.175, 0.075, 0.015, 0.06, 0.0175, 0.0075]);
mods.immersiveengineering.Excavator.addMineral("Silver", 20, 0.005, ["oreSilverPoor", "oreSilverNormal", "oreSilverRich", "oreLeadPoor", "oreLeadNormal", "oreLeadRich"], [0.30, 0.15, 0.05, 0.30, 0.15, 0.05]);
mods.immersiveengineering.Excavator.addMineral("Platinum", 7, 0.005, ["orePlatinumPoor", "orePlatinumNormal", "orePlatinumRich", "oreTetrahedritePoor", "oreNickelPoor"], [0.35, 0.175, 0.075, 0.20, 0.20]);
mods.immersiveengineering.Excavator.addMineral("Lapis Lazuli", 10, 0.005, ["oreLapisLazuli", "oreHematitePoor"], [0.6842, 0.2895]);
mods.immersiveengineering.Excavator.addMineral("Galena", 25, 0.005, ["oreLeadPoor", "oreLeadNormal", "oreLeadRich", "oreSilverSmall", "oreSilverPoor"], [0.70, 0.125, 0.0539, 0.35, 0.0711]);
mods.immersiveengineering.Excavator.addMineral("Nickel", 20, 0.005, ["oreNickelPoor", "oreNickelNormal", "oreNickelRich", "oreHematiteSmall", "oreHematitePoor"], [0.70, 0.175, 0.0694, 0.045, 0.0106]);
mods.immersiveengineering.Excavator.addMineral("Sphalerite", 20, 0.005, ["oreZincPoor", "oreZincNormal", "oreZincRich", "oreSilverSmall", "tfc:ore/small/tetrahedrite"], [0.70, 0.15, 0.05, 0.055, 0.045]);
mods.immersiveengineering.Excavator.addMineral("Cinnabar", 10, 0.005, ["gemCinnabar"], [1]);
mods.immersiveengineering.Excavator.addMineral("Cryolite", 10, 0.005, ["tfc:ore/cryolite", "tfc:ore/selenite"], [0.8444, 0.1556]);
mods.immersiveengineering.Excavator.addMineral("Gypsum", 10, 0.005, ["gemGypsum"], [1]);
mods.immersiveengineering.Excavator.addMineral("Graphite", 10, 0.005, ["gemGraphite"], [1]);
mods.immersiveengineering.Excavator.addMineral("Kimberlite", 5, 0.005, ["gemKimberlite", "gemDiamondChipped", "gemDiamondFlawed", "gemDiamondNormal", "gemDiamondFlawless", "gemDiamondExquisite"], [0.80, 0.10, 0.05, 0.03, 0.015, 0.005]);
mods.immersiveengineering.Excavator.addMineral("Saltpeter", 10, 0.005, ["gemSaltpeter"], [1]);
mods.immersiveengineering.Excavator.addMineral("Sylvite", 10, 0.005, ["gemSylvite"], [1]);
mods.immersiveengineering.Excavator.addMineral("Borax", 10, 0.005, ["gemBorax"], [1]);
mods.immersiveengineering.Excavator.addMineral("Petrified Wood", 20, 0.005, ["gemPetrifiedWood"], [1]);
mods.immersiveengineering.Excavator.addMineral("Silt Igneous Extrusive", 40, 0.005, ["clay", "sandIgneousExtrusive", "gravelIgneousExtrusive"], [0.5, 0.3, 0.2]);
mods.immersiveengineering.Excavator.addMineral("Silt Igneous Intrusive", 40, 0.005, ["clay", "sandIgneousIntrusive", "gravelIgneousIntrusive"], [0.5, 0.3, 0.2]);
mods.immersiveengineering.Excavator.addMineral("Silt Sedimentary", 40, 0.005, ["clay", "sandSedimentary", "gravelSedimentary"], [0.5, 0.3, 0.2]);
mods.immersiveengineering.Excavator.addMineral("Silt Metamorphic", 40, 0.005, ["clay", "sandMetamorphic", "gravelMetamorphic"], [0.5, 0.3, 0.2]);
mods.immersiveengineering.Excavator.addMineral("Microcline", 5, 0.005, ["gemMicrocline"], [1]);
mods.immersiveengineering.Excavator.addMineral("Serpentine", 5, 0.005, ["gemSerpentine", "oreBismuthPoor", "oreLeadPoor"], [0.5, 0.30, 0.20]);
mods.immersiveengineering.Excavator.addMineral("Bauxite", 20, 0.005, ["oreAluminiumPoor", "oreAluminiumNormal", "oreAluminiumRich"], [0.6, 0.3, 0.1]);
mods.immersiveengineering.Excavator.addMineral("Cobaltite", 2, 0.005, ["oreCobaltPoor", "oreCobaltNormal", "oreCobaltRich"], [0.6, 0.3, 0.1]);
mods.immersiveengineering.Excavator.addMineral("Ardite", 2, 0.005, ["oreArditeNormal", "oreBismuthPoor", "oreLeadPoor", "oreArditeRich"], [0.5, 0.30, 0.20, 0.1]);
mods.immersiveengineering.Excavator.addMineral("Native Osmium", 1, 0.005, ["oreOsmiumPoor", "oreOsmiumNormal", "oreOsmiumRich"], [0.6, 0.3, 0.1]);
mods.immersiveengineering.Excavator.addMineral("Stibnite", 5, 0.005, ["oreAntimonyPoor", "oreAntimonyNormal", "oreAntimonyRich"], [0.6, 0.3, 0.1]);
mods.immersiveengineering.Excavator.addMineral("Wolframite", 1, 0.005, ["oreTungstenNormal", "oreHematitePoor", ], [0.75, 0.25]);
mods.immersiveengineering.Excavator.addMineral("Chromite", 5, 0.005, ["gemChromite", ], [0.1]);
mods.immersiveengineering.Excavator.addMineral("Pyrolusite", 5, 0.005, ["gemPyrolusite", ], [0.1]);
mods.immersiveengineering.Excavator.addMineral("Magnesite", 5, 0.005, ["gemMagnesite", ], [0.1]);
mods.immersiveengineering.Excavator.addMineral("Boron", 5, 0.005, ["gemBoron", ], [0.1]);
mods.immersiveengineering.Excavator.addMineral("Amber", 5, 0.005, ["ore:gemAmber"], [1]);
