// File generated by MineTweakerRecipeMaker
//                     READ THIS HEADER BEFORE EDITING ANYTHING
// ================================================================================
//     This file is read and changed by the mod.
//     If you remove/edit any of the markers, IT WILL STOP WORKING!
//     If you want to make manual edits, make a backup of this file!
//     Markers look like this: "//#MARKER something"
//     They indicate where calls should be placed, so that MineTweaker does them in the correct order.
//     Removes come first, then stuff is added.
// ================================================================================
//

// ================================================================================
//#MARKER REMOVE
recipes.remove(<advancedrocketry:thermite>);
recipes.removeByRecipeName("railcraft:dust#7$1");
recipes.removeByRecipeName("railcraft:locomotive_steam_solid#0$1");
recipes.remove(<ore:dustVoid>);
recipes.remove(<minecraft:anvil>);
recipes.remove(<minecraft:minecart>);
recipes.remove(<pneumaticcraft:remote>);
recipes.remove(<pneumaticcraft:network_component:5>);
recipes.remove(<pneumaticcraft:network_component:3>);

recipes.remove(<embers:boiler>);
recipes.remove(<immersiveengineering:metal_decoration0:5>);
recipes.remove(<immersiveengineering:metal_decoration0:3>);
recipes.remove(<ic2:crafting:1>);
recipes.remove(<tconstruct:soil>);
recipes.remove(<thermalfoundation:material:513>);
recipes.remove(<thermalfoundation:material:514>);
recipes.remove(<thermalfoundation:material:515>);
recipes.remove(<metallurgy:brass_knuckles>);
recipes.remove(<minecraft:compass>);
recipes.remove(<minecraft:enchanting_table>);
recipes.remove(<minecraft:fishing_rod>);
recipes.remove(<minecraft:ender_eye>);

recipes.remove(<advancedrocketry:ic:*>);
recipes.remove(<advancedrocketry:jackhammer>);
recipes.remove(<extrautils2:filter>);
recipes.remove(<extrautils2:filterfluids>);
recipes.remove(<extrautils2:indexer>);
recipes.remove(<extrautils2:indexerremote>);
recipes.remove(<extrautils2:grocket>);
recipes.remove(<extrautils2:grocket:1>);
recipes.remove(<extrautils2:grocket:2>);
recipes.remove(<extrautils2:grocket:5>);
recipes.remove(<extrautils2:grocket:6>);
recipes.remove(<extrautils2:pipe>);
recipes.remove(<tetra:duplex_tool_modular>);
recipes.remove(<tetra:toolbelt_modular>);
recipes.remove(<thermalexpansion:satchel>);
recipes.remove(<extrautils2:drum>);
recipes.remove(<mystgears:ember_gatling_gun>);
recipes.remove(<embers:mini_boiler>);
recipes.remove(<mystgears:windup_box>);
recipes.remove(<embers:cinder_plinth>);
recipes.remove(<minecraft:wool>);
recipes.remove(<immersiveengineering:skyhook>);
recipes.remove(<bloodmagic:altar>);
recipes.remove(<bloodmagic:soul_forge>);
recipes.remove(<bloodmagic:soul_snare>);

recipes.remove(<embers:clockwork_attenuator>);
recipes.remove(<embers:steam_engine>);
recipes.remove(<embers:breaker>);
recipes.remove(<mysticalmechanics:gearbox_frame>);
recipes.remove(<mysticalmechanics:mergebox_frame>);
recipes.remove(<mystgears:drill>);
recipes.remove(<mystgears:drill_diamond>);
recipes.remove(<extrautils2:spike_diamond>);
recipes.remove(<extrautils2:spike_gold>);
recipes.remove(<extrautils2:spike_iron>);
recipes.remove(<extrautils2:spike_stone>);
recipes.remove(<extrautils2:spike_wood>);
recipes.remove(<ic2:glass>);
recipes.remove(<cyberware:beacon_large>);
recipes.remove(<cyberware:scanner>);
recipes.remove(<magneticraft:steam_boiler>);



// ================================================================================
//#MARKER REMOVE SHAPELESS
recipes.removeShapeless(<betternether:reeds_block>, [<ore:sugarcane>, <ore:sugarcane>, <ore:sugarcane>, <ore:sugarcane>, <ore:sugarcane>, <ore:sugarcane>, <ore:sugarcane>, <ore:sugarcane>, <ore:sugarcane>]);
recipes.removeShapeless(<minecraft:flint_and_steel>, [<ore:ingotIron>, <ore:flint>]);
recipes.removeShapeless(<railcraft:cart_cargo>, [<minecraft:trapped_chest>, <minecraft:minecart>]);
recipes.removeShapeless(<minecraft:clay_ball> * 2, [<tfc:ceramics/unfired/mold/ingot>]);
recipes.removeShapeless(<minecraft:paper> * 3, [<ore:sugarcane>, <ore:sugarcane>, <ore:sugarcane>]);
recipes.removeShapeless(<minecraft:rotten_flesh> * 9, [<thaumcraft:flesh_block>]);
recipes.removeShapeless(<advancedrocketry:thermitetorch> * 4, [<minecraft:stick>, <advancedrocketry:thermite>]);

// ================================================================================
//#MARKER REMOVE SHAPED
recipes.removeShaped(<railcraft:tool_spike_maul_steel>, [[<ore:ingotSteel>, <ore:blockSteel>, <ore:ingotSteel>], [null, <ore:stickWood>, null], [null, <ore:stickWood>, null]]);
recipes.removeShaped(<railcraft:tool_spike_maul_iron>, [[<ore:ingotIron>, <ore:blockIron>, <ore:ingotIron>], [null, <ore:stickWood>, null], [null, <ore:stickWood>, null]]);
recipes.removeShaped(<mekanism:basicblock2:7> * 4, [[null, <ore:ingotSteel>, null], [<ore:ingotSteel>, null, <ore:ingotSteel>], [null, <ore:ingotSteel>, null]]);
recipes.removeShaped(<mekanism:basicblock2:8> * 2, [[null, <mekanism:basicblock2:7>, null], [<mekanism:basicblock2:7>, <ore:circuitAdvanced>, <mekanism:basicblock2:7>], [null, <mekanism:basicblock2:7>, null]]);
recipes.removeShaped(<railcraft:circuit>, [[null, <minecraft:repeater>, <minecraft:wool:14>], [<ore:slimeball>, <ore:plateGold>, <ore:dustRedstone>], [<minecraft:wool:14>, <ore:dustRedstone>, <ore:gemLapis>]]);
recipes.removeShaped(<railcraft:circuit:1>, [[null, <minecraft:repeater>, <minecraft:wool:13>], [<ore:slimeball>, <ore:plateGold>, <ore:dustRedstone>], [<minecraft:wool:13>, <ore:dustRedstone>, <ore:gemLapis>]]);
recipes.removeShaped(<railcraft:circuit:2>, [[null, <minecraft:repeater>, <minecraft:wool:4>], [<ore:slimeball>, <ore:plateGold>, <ore:dustRedstone>], [<minecraft:wool:4>, <ore:dustRedstone>, <ore:gemLapis>]]);
recipes.removeShaped(<railcraft:circuit:3>, [[null, <minecraft:repeater>, <ore:wool>], [<ore:slimeball>, <ore:plateGold>, <ore:dustRedstone>], [<minecraft:wool:11>, <ore:dustRedstone>, <ore:gemLapis>]]);
recipes.removeShaped(<railcraft:circuit:3>, [[null, <minecraft:repeater>, <ore:wool>], [<ore:slimeball>, <ore:plateGold>, <ore:dustRedstone>], [<ore:wool>, <ore:dustRedstone>, <ore:gemLapis>]]);
recipes.removeShaped(<railcraft:circuit:2>, [[null, <minecraft:repeater>, <ore:wool>], [<ore:slimeball>, <ore:plateGold>, <ore:dustRedstone>], [<ore:wool>, <ore:dustRedstone>, <ore:gemLapis>]]);
recipes.removeShaped(<railcraft:circuit:1>, [[null, <minecraft:repeater>, <ore:blockWoolGreen>], [<ore:slimeball>, <ore:plateGold>, <ore:dustRedstone>], [<ore:blockWoolGreen>, <ore:dustRedstone>, <ore:gemLapis>]]);
recipes.removeShaped(<railcraft:circuit>, [[null, <minecraft:repeater>, <ore:woolRed>], [<ore:slimeball>, <ore:plateGold>, <ore:dustRedstone>], [<ore:woolRed>, <ore:dustRedstone>, <ore:gemLapis>]]);
recipes.remove(<clothesline:spinner>);
recipes.remove(<clothesline:crank>);
recipes.remove(<clothesline:clothesline_anchor>);
recipes.remove(<clothesline:clothesline>);

recipes.removeShaped(<quark:chain> * 3, [[<ore:nuggetIron>, <ore:nuggetIron>, null], [<ore:nuggetIron>, <ore:ingotIron>, null], [null, null, <ore:ingotIron>]]);
recipes.removeShaped(<betternether:reeds_block>, [[<ore:sugarcane>, <ore:sugarcane>, <ore:sugarcane>], [<ore:sugarcane>, <ore:sugarcane>, <ore:sugarcane>], [<ore:sugarcane>, <ore:sugarcane>, <ore:sugarcane>]]);
recipes.removeShaped(<immersiveintelligence:mechanical_device>, [[<ore:plateBrass>, <immersiveengineering:material:8>, <ore:plateBrass>], [<ore:stickIron>, <ore:scaffoldingTreatedWood>, <ore:stickIron>], [<ore:plateBrass>, null, <ore:plateBrass>]]);
recipes.removeShaped(<railcraft:cart_cargo>, [[<minecraft:trapped_chest>], [<minecraft:minecart>]]);
recipes.removeShaped(<pneumaticcraft:gas_lift>, [[null, <pneumaticcraft:pressure_tube>, null], [<pneumaticcraft:pressure_tube>, <ore:blockGlass>, <pneumaticcraft:pressure_tube>], [<ore:ingotIronCompressed>, <ore:ingotIronCompressed>, <ore:ingotIronCompressed>]]);
recipes.removeShaped(<minecraft:paper> * 3, [[<ore:sugarcane>, <ore:sugarcane>, <ore:sugarcane>]]);
recipes.removeShaped(<minecraft:paper> * 3, [[<ore:sugarcane>, <ore:sugarcane>, <ore:sugarcane>]]);
recipes.removeShaped(<minecraft:paper> * 3, [[<ore:sugarcane>, <ore:sugarcane>, <ore:sugarcane>]]);
recipes.removeShaped(<minecraft:paper> * 3, [[<betternether:nether_reed>, <betternether:nether_reed>, <betternether:nether_reed>]]);
recipes.removeShaped(<minecraft:paper> * 3, [[<betternether:nether_reed>, <betternether:nether_reed>, <betternether:nether_reed>]]);
recipes.removeShaped(<minecraft:paper> * 3, [[<betternether:nether_reed>, <betternether:nether_reed>, <betternether:nether_reed>]]);
recipes.removeShaped(<ic2:wrench_new>, [[null, <ore:ingotBronze>, null], [<ore:ingotBronze>, <ore:ingotBronze>, <ore:ingotBronze>], [<ore:ingotBronze>, null, <ore:ingotBronze>]]);
recipes.removeShaped(<tfc:blast_furnace>, [[<ore:sheetDoubleWroughtIron>, <ore:sheetDoubleWroughtIron>, <ore:sheetDoubleWroughtIron>], [<ore:sheetDoubleWroughtIron>, <tfc:crucible>, <ore:sheetDoubleWroughtIron>], [<ore:sheetDoubleWroughtIron>, <ore:sheetDoubleWroughtIron>, <ore:sheetDoubleWroughtIron>]]);
recipes.removeShaped(<minecraft:heavy_weighted_pressure_plate>, [[<ore:ingotIron>, <ore:ingotIron>]]);
recipes.removeShaped(<tfc:bloomery>, [[<ore:sheetDoubleAnyBronze>, <ore:sheetDoubleAnyBronze>, <ore:sheetDoubleAnyBronze>], [<ore:sheetDoubleAnyBronze>, null, <ore:sheetDoubleAnyBronze>], [<ore:sheetDoubleAnyBronze>, <ore:sheetDoubleAnyBronze>, <ore:sheetDoubleAnyBronze>]]);
recipes.removeShaped(<minecraft:rotten_flesh> * 9, [[<thaumcraft:flesh_block>]]);
recipes.removeShaped(<thaumcraft:flesh_block>, [[<minecraft:rotten_flesh>, <minecraft:rotten_flesh>, <minecraft:rotten_flesh>], [<minecraft:rotten_flesh>, <minecraft:rotten_flesh>, <minecraft:rotten_flesh>], [<minecraft:rotten_flesh>, <minecraft:rotten_flesh>, <minecraft:rotten_flesh>]]);
recipes.removeShaped(<quark:candle> * 2, [[<ore:string>], [<ore:tallow>], [<ore:tallow>]]);
recipes.removeShaped(<metallurgy:quicksilver_ingot>, [[<ore:nuggetQuicksilver>, <ore:nuggetQuicksilver>, <ore:nuggetQuicksilver>], [<ore:nuggetQuicksilver>, <ore:nuggetQuicksilver>, <ore:nuggetQuicksilver>], [<ore:nuggetQuicksilver>, <ore:nuggetQuicksilver>, <ore:nuggetQuicksilver>]]);
recipes.remove(<minecraft:piston>);
recipes.remove(<immersiveengineering:drill>);
recipes.remove(<metallurgy:ignatius_fuel>);
recipes.remove(<extrautils2:analogcrafter>);
recipes.remove(<extrautils2:crafter>);
recipes.removeByMod("buildinggadgets");
recipes.remove(<ore:gearBrass>);
recipes.remove(<ore:gearSteel>);
recipes.remove(<ore:gearIron>);
recipes.remove(<ore:gearGold>);
recipes.removeShaped(<mekanism:basicblock:14>, [[<ore:circuitAdvanced>, <ore:paneGlass>, <ore:circuitAdvanced>], [<mekanism:basicblock2>, <minecraft:bucket>, <mekanism:basicblock2>], [<mekanism:basicblock2>, <mekanism:basicblock2>, <mekanism:basicblock2>]]);
recipes.removeShaped(<magneticraft:connector> * 8, [[null, <ore:ingotIron>, null], [<ore:stone>, <ore:ingotCopper>, <ore:stone>]]);
recipes.remove(<ic2:cover>);
recipes.remove(<immersiveintelligence:mechanical_device1>);
recipes.remove(<extrautils2:user>);
recipes.remove(<extrautils2:miner>);
recipes.remove(<minecraft:fire_charge>);

// ================================================================================
//#MARKER ADD

// ================================================================================
//#MARKER ADD SHAPELESS

recipes.addShapeless(<railcraft:track_kit:9> * 4, [<ore:plankWood>, <ore:fenceGateWood>, <railcraft:rail:1>, <ore:dustRedstone>, <railcraft:track_parts>]);
recipes.addShapeless(<minecraft:carrot>, [<ore:knife>.transformDamage(1), <tfc:food/carrot>]);
recipes.addShapeless(<minecraft:wheat>, [<ore:axe>.transformDamage(1), <tfc:food/wheat>]);
recipes.addShapeless(<railcraft:circuit:2> * 2, [<tfc:brass_mechanisms>, <minecraft:repeater>, <ore:woolYellow>]);
recipes.addShapeless(<railcraft:circuit:3> * 2, [<tfc:brass_mechanisms>, <minecraft:repeater>, <ore:woolBlue>]);
recipes.addShapeless(<railcraft:circuit:1> * 2, [<tfc:brass_mechanisms>, <minecraft:repeater>, <ore:blockWoolGreen>]);
recipes.addShapeless(<railcraft:circuit> * 2, [<tfc:brass_mechanisms>, <minecraft:repeater>, <ore:woolRed>]);
recipes.addShapeless(<minecraft:stone_pressure_plate>, [<ore:pressurePlateStone>]);
recipes.addShapeless(<minecraft:anvil>, [<tfc:metal/anvil/wrought_iron>]);
recipes.addShapeless(<minecraft:anvil> * 2, [<tfc:metal/anvil/steel>]);
recipes.addShapeless(<railcraft:worldspike:3>, [<railcraft:worldspike:2>]);
recipes.addShapeless(<railcraft:worldspike:2>, [<railcraft:worldspike:1>]);
recipes.addShapeless(<railcraft:worldspike:1>, [<railcraft:worldspike:3>]);
recipes.addShapeless(<extrautils2:spike_wood>, [<ore:knife>.transformDamage(1), <ore:logWood>]);

recipes.addShapeless(<minecraft:fire_charge>, [<minecraft:lava_bucket>.transformReplace(<minecraft:bucket>), <ore:gunpowder>, <ore:mineralLignite>]);
recipes.addShapeless(<minecraft:fire_charge>, [<minecraft:lava_bucket>.transformReplace(<minecraft:bucket>), <ore:gunpowder>, <ore:mineralBituminousCoal>]);
recipes.addShapeless(<minecraft:fire_charge>, [<minecraft:lava_bucket>.transformReplace(<minecraft:bucket>), <ore:gunpowder>, <ore:fuelCoke>]);
recipes.addShapeless(<minecraft:fire_charge>, [<minecraft:lava_bucket>.transformReplace(<minecraft:bucket>), <ore:gunpowder>, <ore:itemCharcoal>]);
recipes.addShapeless(<minecraft:brown_mushroom>, [<ore:mushroombrown>]);
recipes.addShapeless(<minecraft:red_mushroom>, [<ore:mushroomRed>]);
recipes.addShapeless(<ic2:nuclear:9>, [<ore:dustCharcoal>, <ore:dustCharcoal>, <ore:dustCharcoal>, <ore:dustCharcoal>, <ic2:nuclear>, <ore:dustCharcoal>, <ore:dustCharcoal>, <ore:dustCharcoal>, <ore:dustCharcoal>]);
recipes.addShapeless(<ic2:nuclear:9>, [<ore:dustCoal>, <ore:dustCoal>, <ic2:nuclear>, <ore:dustCoal>, <ore:dustCoal>]);
recipes.addShapeless(<minecraft:rabbit_foot>, [<tfc:food/rabbit>, <ore:knife>.transformDamage(1)]);
recipes.addShapeless(<metallurgy:thermite_dust> * 6, [<ore:dustAluminum>, <ore:dustAluminum>, <thaumcraft:alumentum>, <ore:dustPigIron>, <thaumcraft:alumentum>]);
recipes.addShapeless(<metallurgy:thermite_dust> * 3, [<ore:dustAluminum>, <ore:dustAluminum>, <thaumcraft:alumentum>, <ore:dustWroughtIron>, <thaumcraft:alumentum>]);
recipes.addShapeless(<metallurgy:thermite_dust> * 4, [<ore:dustAluminum>, <ore:dustAluminum>, <ore:dustCoke>, <ore:dustPigIron>]);
recipes.addShapeless(<metallurgy:thermite_dust> * 2, [<ore:dustAluminum>, <ore:dustAluminum>, <ore:dustCoke>, <ore:dustWroughtIron>]);
recipes.addShapeless(<metallurgy:thermite_dust> * 2, [<ore:dustAluminum>, <ore:dustAluminum>, <ore:dustCoal>, <ore:dustWroughtIron>, <ore:dustCoal>]);
recipes.addShapeless(<metallurgy:thermite_dust> * 4, [<ore:dustAluminum>, <ore:dustAluminum>, <ore:dustCoal>, <ore:dustPigIron>, <ore:dustCoal>]);
recipes.addShapeless(<metallurgy:thermite_dust> * 2, [<ore:dustAluminum>, <ore:dustAluminum>, <ore:dustCharcoal>, <ore:dustPigIron>, <ore:dustCharcoal>]);
recipes.addShapeless(<metallurgy:thermite_dust>, [<ore:dustAluminum>, <ore:dustAluminum>, <ore:dustCharcoal>, <ore:dustWroughtIron>, <ore:dustCharcoal>]);
recipes.addShapeless(<ic2:nuclear:9>, [<ic2:nuclear>, <ore:dustCoke>, <ore:dustCoke>]);
recipes.addShapeless(<ic2:nuclear:9>*5, [<ic2:nuclear:4>, <ore:dustCoke>, <ore:dustCoke>]);
recipes.addShapeless(<ic2:nuclear:9>*5, [<ore:dustCoal>, <ore:dustCoal>, <ic2:nuclear:4>, <ore:dustCoal>, <ore:dustCoal>]);
recipes.addShapeless(<ic2:nuclear:9>*5, [<ore:dustCharcoal>, <ore:dustCharcoal>, <ore:dustCharcoal>, <ore:dustCharcoal>, <ic2:nuclear:4>, <ore:dustCharcoal>, <ore:dustCharcoal>, <ore:dustCharcoal>, <ore:dustCharcoal>]);
recipes.addShapeless(<tfc:metal/dust/pig_iron> * 2, [<ore:dustWroughtIron>, <ore:dustWroughtIron>, <ore:dustManganese>, <ore:dustManganese>, <ore:dustManganese>, <ore:dustFlux>, <ore:dustFlux>, <ore:dustFlux>, <ore:dustCharcoal>]);
recipes.addShapeless(<tfc:metal/dust/pig_iron> * 2, [<ore:dustWroughtIron>, <ore:dustWroughtIron>, <ore:dustManganese>, <ore:dustManganese>, <ore:dustManganese>, <ore:dustFlux>, <ore:dustFlux>, <ore:dustFlux>, <ore:dustCoal>]);
recipes.addShapeless(<minecraft:crafting_table>, [<ore:workbench>]);
recipes.addShapeless(<railcraft:rail> * 30, [<ore:stickLongBlackSteel>]);
recipes.addShapeless(<railcraft:rail> * 12, [<ore:stickLongSteel>]);
recipes.addShapeless(<railcraft:rail> * 6, [<ore:stickLongWroughtIron>]);
recipes.addShapeless(<camping:logseat>, [<ore:logWood>, <camping:knife>]);
recipes.addShapeless(<tconstruct:soil> * 3, [<ore:gravel>, <ore:dustSkyStone>, <ore:dustAsh>, <ore:fireClay>, <ore:fireClay>]);
recipes.addShapeless(<tconstruct:seared_glass>, [<ore:blockSeared>, <ore:blockGlass>]);
recipes.addShapeless(<minecraft:cobblestone> * 3, [<ore:cobblestone>, <ore:mortar>, <ore:cobblestone>, <ore:cobblestone>]);
recipes.addShapeless(<minecraft:rabbit_hide>, [<tfc:hide/prepared/small>]);
recipes.addShapeless(<bloodmagic:soul_snare> * 8, [<ore:string>, <quark:soul_bead>]);
recipes.addShapeless(<ic2:nuclear:2>, [<ic2:nuclear:6>, <ic2:nuclear:6>, <ic2:nuclear:6>, <ic2:nuclear:6>, <ic2:nuclear:6>, <ic2:nuclear:6>, <ic2:nuclear:6>, <ic2:nuclear:6>, <ic2:nuclear:6>]);

recipes.addShapeless(<ic2:cover>, [<ore:barsIron>, <mysticalmechanics:gear_fan>, <tfc:brass_mechanisms>]);

recipes.addShapeless(<immersiveintelligence:material:40> * 12, [<ore:sand>, <ore:clothHighQuality>]);
recipes.addShapeless(<immersiveintelligence:material:40> * 12, [<ore:sand>, <tfc:crop/product/burlap_cloth>]);
recipes.addShapeless(<minecraft:rotten_flesh> * 8, [<thaumcraft:flesh_block>]);
recipes.addShapeless(<thebetweenlands:ancient_remnant_block>, [<ore:stonePolished>, <tfc:powder/malachite>]);
recipes.addShapeless(<magneticraft:steam_boiler>, [<magneticraft:multiblock_parts:5>]);

recipes.addShapeless(<tfc:metal/nugget/red_steel> * 9, [<ore:ingotRedSteel>]);
recipes.addShapeless(<tfc:metal/nugget/blue_steel> * 9, [<ore:ingotBlueSteel>]);


recipes.addShapeless(<minecraft:blaze_powder>, [<thebetweenlands:pyrad_flame>]);
recipes.addShapeless(<tfc:metal/nugget/tungsten_steel> * 9, [<ore:ingotTungstenSteel>]);
recipes.addShapeless(<minecraft:iron_nugget>, [<ore:nuggetWroughtIron>]);
recipes.remove(<embers:archaic_circuit>);





recipes.addShapeless(<immersiveintelligence:metal_device>, [<immersiveintelligence:small_crate:5>]);
recipes.addShapeless(<immersiveintelligence:small_crate:5>, [<immersiveintelligence:small_crate:3>]);
recipes.addShapeless(<immersiveintelligence:small_crate:3>, [<immersiveintelligence:small_crate:4>]);
recipes.addShapeless(<immersiveintelligence:small_crate:4>, [<immersiveintelligence:metal_device>]);
recipes.addShapeless(<immersiveengineering:wooden_device0>, [<immersiveintelligence:small_crate:2>]);
recipes.addShapeless(<immersiveintelligence:small_crate:2>, [<immersiveintelligence:small_crate>]);
recipes.addShapeless(<immersiveintelligence:small_crate>, [<immersiveintelligence:small_crate:1>]);
recipes.addShapeless(<immersiveintelligence:small_crate:1>, [<immersiveengineering:wooden_device0>]);
recipes.addShapeless(<immersiveengineering:wooden_device0:5>, [<immersiveintelligence:small_crate:8>]);
recipes.addShapeless(<immersiveintelligence:small_crate:8>, [<immersiveintelligence:small_crate:6>]);
recipes.addShapeless(<immersiveintelligence:small_crate:6>, [<immersiveintelligence:small_crate:7>]);
recipes.addShapeless(<immersiveintelligence:small_crate:7>, [<immersiveengineering:wooden_device0:5>]);
recipes.addShapeless(<minecraft:ender_eye>, [<ore:enderpearl>, <thaumcraft:void_seed>, <ore:powderBlaze>]);
recipes.remove(<metallurgy:thermite_dust>);
recipes.addShapeless(<metallurgy:thermite_dust> * 8, [<ore:dustAluminium>, <ore:dustPigIron>, <thaumcraft:alumentum>]);
recipes.addShapeless(<camping:parts> * 2, [<ore:leatherArtificial>, <minecraft:rabbit_hide>, <camping:knife>.reuse()]);


// ================================================================================
//#MARKER ADD SHAPED
recipes.addShaped(<tfc:metal/scrap/copper>, [[<ore:boltCopper>, <ore:boltCopper>], [<ore:boltCopper>, <ore:boltCopper>]]);
recipes.addShaped(<tfc:metal/saw_blade/copper>, [[<ore:scrapPigIron>, <ore:scrapCopper>], [null, <ore:scrapPigIron>]]);
recipes.addShaped(<tfc:metal/shovel_head/copper>, [[<ore:scrapCopper>, <ore:scrapCopper>], [<ore:scrapCopper>, <ore:scrapCopper>]]);
recipes.addShaped(<tfc:metal/pick_head/copper>, [[<ore:scrapPigIron>, <ore:scrapCopper>], [null, <ore:scrapCopper>]]);
recipes.addShaped(<railcraft:tool_spike_maul_steel>, [[<tfc:metal/pick_head/steel>, <ore:stickWood>, <tfc:metal/pick_head/steel>], [null, <ore:stickWood>, null], [null, <ore:stickWood>, null]]);
recipes.addShaped(<railcraft:tool_spike_maul_iron>, [[<tfc:metal/pick_head/wrought_iron>, <ore:stickWood>, <tfc:metal/pick_head/wrought_iron>], [null, <ore:stickWood>, null], [null, <ore:stickWood>, null]]);
recipes.addShaped(<pneumaticcraft:remote>, [[null, <pneumaticcraft:network_component:3>, null], [<ore:oc:materialTransistor>, <pneumaticcraft:gps_tool>, <ore:oc:materialTransistor>], [<ore:oc:materialTransistor>, <pneumaticcraft:network_component:2>, <ore:oc:materialTransistor>]]);
recipes.addShaped(<pneumaticcraft:network_component:5> * 16, [[<ore:oc:materialTransistor>, <ore:oc:materialTransistor>, <ore:oc:materialTransistor>], [<ore:oc:materialTransistor>, <ore:chestWood>, <ore:oc:materialTransistor>], [<ore:oc:materialTransistor>, <ore:oc:materialTransistor>, <ore:oc:materialTransistor>]]);
recipes.addShaped(<railcraft:rail:4> * 6, [[<railcraft:rail>, <ore:dustObsidian>, <railcraft:rail>], [<railcraft:rail>, <ore:dustObsidian>, <railcraft:rail>], [<railcraft:rail>, <ore:dustObsidian>, <railcraft:rail>]]);
recipes.addShaped(<railcraft:tie:1>, [[<ore:mortar>, <ore:mortar>, <ore:mortar>], [<ore:mortar>, <ore:stickIron>, <ore:mortar>], [<ore:mortar>, <ore:mortar>, <ore:mortar>]]);
recipes.addShaped(<mekanism:machineblock3:6>, [[null, <ore:plateSteel>, null], [<ore:plateSteel>, <mekanism:transmitter:6>, <ore:plateSteel>], [<ore:plateSteel>, <minecraft:furnace>, <ore:plateSteel>]]);
recipes.addShaped(<mystgears:gear_flywheel_heavy>, [[<ore:ingotDoubleLead>, <ore:ingotDoubleLead>, <ore:ingotDoubleLead>], [<ore:ingotDoubleLead>, <ore:sleeveBrass>, <ore:ingotDoubleLead>], [<ore:ingotDoubleLead>, <ore:ingotDoubleLead>, <ore:ingotDoubleLead>]]);
recipes.addShaped(<mystgears:gear_flywheel_light>, [[<ore:ingotIron>, <ore:ingotIron>, <ore:ingotIron>], [<ore:ingotIron>, <ore:sleeveBrass>, <ore:ingotIron>], [<ore:ingotIron>, <ore:ingotIron>, <ore:ingotIron>]]);
recipes.addShaped(<clothesline:crank>, [[<minecraft:lever>, <ore:stickWood>]]);
recipes.addShaped(<immersiveengineering:wirecoil:3> * 4, [[null, <tfc:crop/product/jute_fiber>, null], [<tfc:crop/product/jute_fiber>, <ore:stickWood>, <tfc:crop/product/jute_fiber>], [null, <tfc:crop/product/jute_fiber>, null]]);
recipes.addShaped(<quark:rope> * 3, [[<tfc:crop/product/jute_fiber>, <tfc:crop/product/jute_fiber>, <tfc:crop/product/jute_fiber>], [<tfc:crop/product/jute_fiber>, null, <tfc:crop/product/jute_fiber>], [<tfc:crop/product/jute_fiber>, <tfc:crop/product/jute_fiber>, <tfc:crop/product/jute_fiber>]]);
recipes.addShaped(<projectred-core:screwdriver>, [[null, <ore:rodIron>], [<ore:dyeBlue>, null]]);
recipes.addShaped(<quark:chain> * 2, [[null, <ore:nuggetIron>, <ore:nuggetIron>], [<ore:nuggetIron>, <ore:nuggetIron>, <ore:nuggetIron>], [<ore:nuggetIron>, <ore:nuggetIron>, null]]);
recipes.addShaped(<quark:chain> * 2, [[<ore:nuggetIron>, <ore:nuggetIron>, null], [<ore:nuggetIron>, <ore:nuggetIron>, <ore:nuggetIron>], [null, <ore:nuggetIron>, <ore:nuggetIron>]]);
recipes.addShaped(<immersiveengineering:wooden_device0:7>, [[<thaumcraft:mind>], [<ore:scaffoldingTreatedWood>], [<minecraft:bucket>]]);
recipes.addShaped(<immersiveengineering:wooden_device0:3>, [[<thaumcraft:mind>], [<ore:scaffoldingTreatedWood>], [<immersiveengineering:material:8>]]);
recipes.addShaped(<tfc:metal/rod/steel>, [[<ore:nuggetSteel>], [<ore:stickIron>], [<ore:nuggetSteel>]]);
recipes.addShaped(<tfc:metal/rod/wrought_iron>, [[<ore:nuggetIron>], [<ore:stickIron>], [<ore:nuggetIron>]]);
recipes.addShaped(<tfc:metal/rod/gold>, [[<ore:nuggetGold>], [<ore:stickGold>], [<ore:nuggetGold>]]);
recipes.addShaped(<minecraft:minecart>, [[<ore:naggetAnyBronze>, null, <ore:naggetAnyBronze>], [<ore:naggetAnyBronze>, <ore:naggetAnyBronze>, <ore:naggetAnyBronze>]]);
recipes.addShaped(<minecraft:minecart>*2, [[<ore:nuggetIron>, null, <ore:nuggetIron>], [<ore:nuggetIron>, <ore:nuggetIron>, <ore:nuggetIron>]]);
recipes.addShaped(<minecraft:minecart>*3, [[<ore:nuggetSteel>, null, <ore:nuggetSteel>], [<ore:nuggetSteel>, <ore:nuggetSteel>, <ore:nuggetSteel>]]);
recipes.addShaped(<railcraft:mow_undercutter>, [[<ore:dyeYellow>, <ore:lamp>, <ore:dyeYellow>], [<ore:shovel>, <minecraft:minecart>, <ore:shovel>]]);
recipes.addShaped(<railcraft:worldspike:3>, [[null, <ore:enderpearl>, null], [<ore:nuggetGold>, <ore:obsidian>, <ore:nuggetGold>], [<ore:dustDiamond>, <ore:nuggetGold>, <ore:dustDiamond>]]);
recipes.addShaped(<railcraft:bore>, [[null, <immersiveintelligence:metal_decoration:4>], [<minecraft:minecart>, <minecraft:minecart>]]);
recipes.addShaped(<railcraft:bore>, [[<immersiveintelligence:metal_decoration:4>, null], [<minecraft:minecart>, <minecraft:minecart>]]);
recipes.addShaped(<railcraft:mow_track_relayer>, [[<ore:dyeYellow>, <ore:lamp>, <ore:dyeYellow>], [<ore:toolCrowbar>, <minecraft:minecart>, <ore:hammer>]]);
recipes.addShaped(<railcraft:mow_track_relayer>, [[<ore:dyeYellow>, <ore:lamp>, <ore:dyeYellow>], [<ore:hammer>, <minecraft:minecart>, <ore:toolCrowbar>]]);
recipes.addShaped(<railcraft:mow_track_layer>, [[<ore:dyeYellow>, <ore:lamp>, <ore:dyeYellow>], [<ore:hammer>, <minecraft:minecart>, <ore:hammer>]]);
recipes.addShaped(<railcraft:mow_track_remover>, [[<ore:dyeYellow>, <ore:lamp>, <ore:dyeYellow>], [<ore:toolCrowbar>, <minecraft:minecart>, <ore:toolCrowbar>]]);
recipes.addShaped(<railcraft:borehead_diamond>, [[<ore:dustDiamond>, <ore:dustDiamond>, <ore:dustDiamond>], [<ore:dustDiamond>, <railcraft:borehead_steel>, <ore:dustDiamond>], [<ore:dustDiamond>, <ore:dustDiamond>, <ore:dustDiamond>]]);
recipes.addShaped(<railcraft:borehead_bronze>, [[<ore:dyeBlue>, <tfc:metal/mace_head/black_bronze>], [<ore:sheetAnyBronze>, <tfc:metal/mace_head/black_bronze>], [<ore:dyeBlue>, <tfc:metal/mace_head/black_bronze>]]);
recipes.addShaped(<railcraft:borehead_bronze>, [[<ore:dyeBlue>, <tfc:metal/mace_head/bismuth_bronze>], [<ore:sheetAnyBronze>, <tfc:metal/mace_head/bismuth_bronze>], [<ore:dyeBlue>, <tfc:metal/mace_head/bismuth_bronze>]]);
recipes.addShaped(<railcraft:borehead_bronze>, [[<ore:dyeBlue>, <tfc:metal/mace_head/bronze>], [<ore:sheetAnyBronze>, <tfc:metal/mace_head/bronze>], [<ore:dyeBlue>, <tfc:metal/mace_head/bronze>]]);
recipes.addShaped(<railcraft:borehead_iron>, [[<ore:dyeBlue>, <tfc:metal/mace_head/wrought_iron>], [<ore:plateIron>, <tfc:metal/mace_head/wrought_iron>], [<ore:dyeBlue>, <tfc:metal/mace_head/wrought_iron>]]);
recipes.addShaped(<railcraft:borehead_steel>, [[<ore:dyeBlue>, <tfc:metal/mace_head/steel>], [<ore:plateSteel>, <tfc:metal/mace_head/steel>], [<ore:dyeBlue>, <tfc:metal/mace_head/steel>]]);
recipes.addShaped(<railcraft:tool_crowbar_steel>, [[null, <ore:nuggetSteel>, <ore:rodSteel>], [null, <ore:rodSteel>, <ore:dyeRed>], [<ore:rodSteel>, <ore:dyeRed>, null]]);
recipes.addShaped(<railcraft:tool_crowbar_iron>, [[null, <ore:nuggetIron>, <ore:rodWroughtIron>], [null, <ore:rodWroughtIron>, <ore:dyeRed>], [<ore:rodWroughtIron>, <ore:dyeRed>, null]]);
recipes.addShaped(<minecraft:furnace>, [[<ore:stonePolished>, <ore:stonePolished>, <ore:stonePolished>], [<ore:brickStone>, <minecraft:fire_charge>, <ore:brickStone>], [<ore:brickStone>, <ore:brickStone>, <ore:brickStone>]]);
recipes.addShaped(<extrautils2:spike_stone>, [[<ore:knifeHead>, <ore:knifeHead>], [<ore:itemClay>, <ore:cobblestone>]]);
recipes.addShaped(<mekanism:walkietalkie>, [[null, null, <ore:nuggetCopper>], [<ore:brick>, <ore:clothHighQuality>, <ore:brick>], [null, <ore:brick>, null]]);
recipes.addShaped(<buildinggadgets:copypastetool>, [[<ore:plateTitanium>, <appliedenergistics2:material:43>], [<ore:plateTitanium>, <appliedenergistics2:material:23>], [<ore:plateTitanium>, <appliedenergistics2:material:23>]]);
recipes.addShaped(<buildinggadgets:exchangertool>, [[<ore:plateTitanium>, <appliedenergistics2:material:44>], [<ore:plateTitanium>, <appliedenergistics2:material:43>], [<ore:plateTitanium>, <appliedenergistics2:material:24>]]);
recipes.addShaped(<buildinggadgets:exchangertool>, [[<ore:plateTitanium>, <appliedenergistics2:material:43>], [<ore:plateTitanium>, <appliedenergistics2:material:44>], [<ore:plateTitanium>, <appliedenergistics2:material:24>]]);
recipes.addShaped(<buildinggadgets:buildingtool>, [[<ore:plateTitanium>, <appliedenergistics2:material:43>], [<ore:plateTitanium>, <appliedenergistics2:material:22>], [<ore:plateTitanium>, <appliedenergistics2:material:22>]]);
recipes.addShaped(<buildinggadgets:destructiontool>, [[<ore:plateTitanium>, <appliedenergistics2:material:44>], [<ore:plateTitanium>, <appliedenergistics2:material:22>], [<ore:plateTitanium>, <appliedenergistics2:material:22>]]);
recipes.addShaped(<buildinggadgets:copypastetool>, [[<ore:plateTin>, <embers:intelligent_apparatus>], [<ore:plateTin>, <embers:ancient_motive_core>], [<ore:plateTin>, <ore:plateTin>]]);
recipes.addShaped(<buildinggadgets:copypastetool>, [[<ore:sheetZinc>, <embers:intelligent_apparatus>], [<ore:sheetZinc>, <embers:ancient_motive_core>], [<ore:sheetZinc>, <ore:sheetZinc>]]);
recipes.addShaped(<buildinggadgets:exchangertool>, [[<ore:sheetZinc>, <thaumcraft:morphic_resonator>], [<ore:sheetZinc>, <embers:ancient_motive_core>], [<ore:sheetZinc>, <ore:sheetZinc>]]);
recipes.addShaped(<buildinggadgets:exchangertool>, [[<ore:plateTin>, <thaumcraft:morphic_resonator>], [<ore:plateTin>, <embers:ancient_motive_core>], [<ore:plateTin>, <ore:plateTin>]]);
recipes.addShaped(<buildinggadgets:destructiontool>, [[<ore:plateSteel>, <ore:dustRedstone>], [<ore:plateSteel>, <mekanism:obsidiantnt>], [<ore:plateSteel>, <ore:plateSteel>]]);
recipes.addShaped(<buildinggadgets:templatemanager>, [[<ore:sheetZinc>, <cyberware:brain_upgrades:5>, <ore:sheetZinc>], [<ore:sheetZinc>, <ore:chestWood>, <ore:sheetZinc>]]);
recipes.addShaped(<buildinggadgets:templatemanager>, [[<ore:plateTin>, <cyberware:brain_upgrades:5>, <ore:plateTin>], [<ore:plateTin>, <ore:chestWood>, <ore:plateTin>]]);
recipes.addShaped(<thermalfoundation:material:512>, [[<ore:nuggetRedSteel>, <ore:springSteel>, <ore:nuggetRedSteel>], [<ore:nuggetRedSteel>, <ore:springSteel>, <ore:nuggetRedSteel>]]);
recipes.addShaped(<minecraft:arrow> * 32, [[<ore:javelinHead>], [<ore:stickWood>], [<ore:knifeBlade>]]);
recipes.addShaped(<railcraft:signal_lamp>, [[<ore:dyeLime>, null], [<ore:dyeYellow>, <ore:lamp>], [<ore:dyeRed>, <ore:dustRedstone>]]);

recipes.addShaped(<magneticraft:gasification_unit>, [[<ore:sheetInvar>, <ore:sheetInvar>, <ore:sheetInvar>], [<ore:sheetInvar>, null, <ore:sheetInvar>], [<ore:ingotIron>, <ore:ingotIron>, <ore:ingotIron>]]);
recipes.addShaped(<ic2:te:24>, [[<ore:stickFerroboron>, <ore:stickFerroboron>, <ore:stickFerroboron>], [<ore:plateLead>, <ore:machineBlock>, <ore:plateLead>], [<ore:plateLead>, <ore:plateLead>, <ore:plateLead>]]);
recipes.addShaped(<ic2:te:22>, [[<ore:plateDenseLead>, <ore:circuitAdvanced>, <ore:plateDenseLead>], [<ic2:te:24>, <ic2:te:24>, <ic2:te:24>], [<ore:plateDenseLead>, <ic2:te:9>, <ore:plateDenseLead>]]);
recipes.addShaped(<ic2:te:5>, [[<ic2:resource:12>, <ic2:crafting:6>, <ic2:crafting:30>]]);
recipes.addShaped(<ic2:te:4>, [[<ic2:fluid_cell>], [<ic2:te:9>]]);
recipes.addShaped(<ic2:te:9>, [[<ic2:casing:3>, <ore:craftingPiston>, <ic2:casing:3>], [<minecraft:glass_bottle>, <ic2:crafting:6>, <minecraft:glass_bottle>], [<ic2:casing:3>, <ore:craftingPiston>, <ic2:casing:3>]]);
recipes.addShaped(<railcraft:tie:1> * 6, [[<fluid:concrete>*1000], [<ore:stickSteel>]]);
recipes.addShaped(<immersiveengineering:metal_decoration2>, [[<ore:fenceSteel>], [<ore:fenceSteel>], [<ore:brickStone>]]);
recipes.addShaped(<immersiveengineering:metal_decoration2:2>, [[<ore:fenceAluminum>], [<ore:fenceAluminum>], [<ore:brickStone>]]);
recipes.addShaped(<immersiveengineering:wooden_device1:3>, [[<ore:fenceTreatedWood>], [<ore:fenceTreatedWood>], [<ore:brickStone>]]);

recipes.addShaped(<immersiveengineering:cloth_device:2>, [[<ore:stickAluminium>, <ore:stickAluminium>, <ore:stickAluminium>], [<tfc:crop/product/jute_fiber>, <tfc:crop/product/jute_fiber>, <tfc:crop/product/jute_fiber>], [<tfc:crop/product/jute_fiber>, <tfc:crop/product/jute_fiber>, <tfc:crop/product/jute_fiber>]]);
recipes.addShaped(<immersiveengineering:cloth_device:2>, [[<ore:stickIron>, <ore:stickIron>, <ore:stickIron>], [<tfc:crop/product/jute_fiber>, <tfc:crop/product/jute_fiber>, <tfc:crop/product/jute_fiber>], [<tfc:crop/product/jute_fiber>, <tfc:crop/product/jute_fiber>, <tfc:crop/product/jute_fiber>]]);

recipes.addShaped(<tconstruct:tooltables>, [[<ore:lumber>, <ore:leather>, <ore:lumber>], [<ore:lumber>, <ore:workbench>, <ore:lumber>], [<ore:lumber>, null, <ore:lumber>]]);
recipes.addShaped(<thermalfoundation:storage_alloy:3>, [[<ore:ingotBronze>, <ore:ingotBronze>, <ore:ingotBronze>], [<ore:ingotBronze>, <ore:ingotBronze>, <ore:ingotBronze>], [<ore:ingotBronze>, <ore:ingotBronze>, <ore:ingotBronze>]]);
recipes.addShaped(<tfc:metal/ingot/bronze>, [[<ore:nuggetBronze>, <ore:nuggetBronze>, <ore:nuggetBronze>], [<ore:nuggetBronze>, <ore:nuggetBronze>, <ore:nuggetBronze>], [<ore:nuggetBronze>, <ore:nuggetBronze>, <ore:nuggetBronze>]]);
recipes.addShaped(<railcraft:rail:5> * 3, [[<ore:nuggetCopper>, <ore:nuggetCopper>], [<ore:nuggetCopper>, <ore:nuggetCopper>], [<ore:nuggetCopper>, <ore:nuggetCopper>]]);
recipes.addShaped(<railcraft:rail:3> * 3, [[<railcraft:rail>, <ore:nuggetRoseGold>], [<railcraft:rail>, <ore:nuggetRoseGold>], [<railcraft:rail>, <ore:nuggetRoseGold>]]);
recipes.addShaped(<railcraft:rail:1> * 3, [[<railcraft:rail>, <ore:nuggetGold>], [<railcraft:rail>, <ore:nuggetGold>], [<railcraft:rail>, <ore:nuggetGold>]]);
recipes.addShaped(<railcraft:rail:4> * 3, [[<railcraft:rail>, <ore:nuggetBlackBronze>], [<railcraft:rail>, <ore:nuggetBlackBronze>], [<railcraft:rail>, <ore:nuggetBlackBronze>]]);
recipes.addShaped(<railcraft:track_parts> * 12, [[<ore:nuggetTungsten>, <ore:nuggetTungsten>]]);
recipes.addShaped(<railcraft:track_parts> * 2, [[<ore:nuggetSteel>, <ore:nuggetSteel>]]);
recipes.addShaped(<railcraft:track_parts>, [[<ore:nuggetWroughtIron>, <ore:nuggetWroughtIron>]]);
recipes.addShaped(<railcraft:track_parts>, [[<ore:naggetAnyBronze>, <ore:naggetAnyBronze>], [<ore:naggetAnyBronze>, null]]);
recipes.addShaped(<ic2:crafting:6> * 2, [[<ic2:casing:6>, <ic2:crafting:5>, <ic2:casing:6>], [<ic2:casing:6>, <ore:rodSteel>, <ore:rodSteel>], [<ic2:casing:6>, <ic2:crafting:5>, <ic2:casing:6>]]);
recipes.addShaped(<immersiveengineering:connector:6> * 8, [[<ore:stickIron>], [<ore:plateIron>]]);
recipes.addShaped(<immersiveengineering:connector:6> * 16, [[<ore:stickSteel>], [<ore:plateSteel>]]);
recipes.addShaped(<immersiveengineering:skyhook>, [[null, <immersiveengineering:material:8>, null], [<ore:gungripWood>, null, <ore:gungripWood>]]);
recipes.addShaped(<immersiveengineering:material:13>, [[<ore:stickWood>, <ore:stickWood>], [<ore:ingotCopper>, <ore:leather>], [<ore:stickWood>, <ore:stickWood>]]);
recipes.addShaped(<magneticraft:multiblock_parts:5>, [[<ore:sheetWroughtIron>, <immersiveengineering:metal_device0:4>, <ore:sheetWroughtIron>]]);
recipes.addShaped(<railcraft:locomotive_steam_solid>, [[<embers:steam_engine>], [<minecraft:minecart>]]);
recipes.addShaped(<ic2:crafting:5>, [[<ore:itemCopperCable>, <ore:itemCopperCable>, <ore:itemCopperCable>], [<ore:itemCopperCable>, <ore:rodSteel>, <ore:itemCopperCable>], [<ore:itemCopperCable>, <ore:itemCopperCable>, <ore:itemCopperCable>]]);
recipes.addShaped(<railcraft:cart_cargo>, [[<thermalexpansion:cache>], [<minecraft:minecart>]]);
recipes.addShaped(<railcraft:cart_cargo>, [[<ore:drawerBasic>], [<minecraft:minecart>]]);
recipes.addShaped(<immersiveintelligence:mechanical_device>, [[<immersiveengineering:material:8>], [<ore:scaffoldingTreatedWood>], [<ore:plateBrass>]]);
recipes.addShaped(<embers:fluid_transfer> * 2, [[<ore:stickWroughtIron>, <ore:plateWroughtIron>, <ore:stickWroughtIron>], [<ore:stickWroughtIron>, <ore:paper>, <ore:stickWroughtIron>]]);
recipes.addShaped(<pneumaticcraft:gas_lift>, [[<ore:ingotIronCompressed>, <ore:ingotIronCompressed>, <ore:ingotIronCompressed>], [<ore:itemRubber>, <pneumaticcraft:pressure_tube>, <ore:itemRubber>], [<ore:itemRubber>, <pneumaticcraft:pressure_tube>, <ore:itemRubber>]]);
recipes.addShaped(<minecraft:speckled_melon>, [[<ore:nuggetGold>, <ore:nuggetGold>, <ore:nuggetGold>], [<ore:nuggetGold>, <ore:melon>, <ore:nuggetGold>], [<ore:nuggetGold>, <ore:nuggetGold>, <ore:nuggetGold>]]);
recipes.addShaped(<tconstruct:seared_tank:2>, [[<tconstruct:seared_tank:1>]]);
recipes.addShaped(<tconstruct:seared_tank:1>, [[<tconstruct:seared_tank>]]);
recipes.addShaped(<tconstruct:seared_tank>, [[<tconstruct:seared_tank:2>]]);

recipes.addShaped(<libvulpes:coil0:7>, [[<ore:wireTitanium>, <ore:wireTitanium>, <ore:wireTitanium>], [<ore:wireTitanium>, <ore:ingotIron>, <ore:wireTitanium>], [<ore:wireTitanium>, <ore:wireTitanium>, <ore:wireTitanium>]]);
recipes.addShaped(<ic2:te:52>, [[<ic2:crafting:5>, <ic2:mining_laser:26>, <ic2:crafting:5>], [<ic2:crafting:6>, <ore:gunpartRevolver>, <ic2:crafting:6>], [<ore:circuitAdvanced>, <ic2:resource:13>, <ore:circuitAdvanced>]]);
recipes.addShaped(<extrautils2:grocket:5>, [[<tetra:metal_scrap>, <extrautils2:pipe>, <tetra:metal_scrap>]]);
recipes.addShaped(<extrautils2:grocket:1>, [[<tetra:metal_scrap>, <ore:sheetBlackSteel>, <tetra:metal_scrap>]]);
recipes.addShaped(<extrautils2:filter>, [[null, <ore:stickPigIron>, null], [<ore:stickPigIron>, <tetra:forged_mesh>, <ore:stickPigIron>], [null, <ore:stickPigIron>, null]]);
recipes.addShaped(<extrautils2:filterfluids>, [[null, <ore:stickPigIron>, null], [<ore:stickPigIron>, <tetra:vent_plate>, <ore:stickPigIron>], [null, <ore:stickPigIron>, null]]);
recipes.addShaped(<pneumaticcraft:electrostatic_compressor> * 2, [[<ore:stickSteel>, <ore:stickLongSteel>, <ore:stickSteel>], [<pneumaticcraft:advanced_air_compressor>, <ore:coilCopper>, <pneumaticcraft:advanced_air_compressor>], [<ore:plasticLightGray>, <ore:stickLongSteel>, <ore:plasticLightGray>]]);
recipes.addShaped(<extrautils2:grocket:4> * 2, [[null, <ore:plateBlackSteel>, <tetra:quick_latch>], [<tetra:metal_scrap>, <ore:fanSteel>, <tetra:metal_scrap>]]);
recipes.addShaped(<extrautils2:grocket:4> * 2, [[<tetra:quick_latch>, <ore:plateBlackSteel>, null], [<tetra:metal_scrap>, <ore:fanSteel>, <tetra:metal_scrap>]]);
recipes.addShaped(<extrautils2:grocket:2> * 2, [[<tetra:forged_bolt>, <ore:plateBlackSteel>, null], [<tetra:metal_scrap>, <ore:fanSteel>, <tetra:metal_scrap>]]);
recipes.addShaped(<extrautils2:grocket:2> * 2, [[null, <ore:plateBlackSteel>, <tetra:forged_bolt>], [<tetra:metal_scrap>, <ore:fanSteel>, <tetra:metal_scrap>]]);
recipes.addShaped(<extrautils2:grocket:3> * 2, [[null, <ore:plateBlackSteel>, <tetra:quick_latch>], [<tetra:metal_scrap>, <ore:springSteel>, <tetra:metal_scrap>]]);
recipes.addShaped(<extrautils2:grocket:3> * 2, [[<tetra:quick_latch>, <ore:plateBlackSteel>, null], [<tetra:metal_scrap>, <ore:springSteel>, <tetra:metal_scrap>]]);
recipes.addShaped(<extrautils2:grocket> * 2, [[<tetra:forged_bolt>, <ore:plateBlackSteel>, null], [<tetra:metal_scrap>, <ore:springSteel>, <tetra:metal_scrap>]]);
recipes.addShaped(<extrautils2:grocket> * 2, [[null, <ore:plateBlackSteel>, <tetra:forged_bolt>], [<tetra:metal_scrap>, <ore:springSteel>, <tetra:metal_scrap>]]);
recipes.addShaped(<extrautils2:pipe> * 12, [[<ore:nuggetBlackSteel>, <ore:nuggetBlackSteel>, <ore:nuggetBlackSteel>], [<tetra:metal_scrap>, <tetra:forged_beam>, <tetra:metal_scrap>], [<ore:nuggetBlackSteel>, <ore:nuggetBlackSteel>, <ore:nuggetBlackSteel>]]);
recipes.addShaped(<ic2:iridium_reflector>, [[<ic2:thick_neutron_reflector>, <ore:sheetDoubleBeryllium>, <ic2:thick_neutron_reflector>], [<ore:sheetDoubleBeryllium>, <ic2:crafting:4>, <ore:sheetDoubleBeryllium>], [<ic2:thick_neutron_reflector>, <ore:sheetDoubleBeryllium>, <ic2:thick_neutron_reflector>]]);
recipes.addShaped(<immersiveengineering:metal_device0:2>, [[<cyberware:dense_battery>, <ore:plateSteel>, <cyberware:dense_battery>], [<cyberware:dense_battery>, <ore:plankTreatedWood>, <cyberware:dense_battery>], [<cyberware:dense_battery>, <ore:plateAluminum>, <cyberware:dense_battery>]]);
recipes.addShaped(<immersiveengineering:metal_device0:2>, [[<cyberware:dense_battery>, <ore:plateAluminum>, <cyberware:dense_battery>], [<cyberware:dense_battery>, <ore:plankTreatedWood>, <cyberware:dense_battery>], [<cyberware:dense_battery>, <ore:plateSteel>, <cyberware:dense_battery>]]);
recipes.addShaped(<immersiveengineering:metal_device0:1>, [[<ore:plankTreatedWood>, <ore:plateElectrum>, <ore:plankTreatedWood>], [<cyberware:dense_battery>, null, <cyberware:dense_battery>], [<ore:plankTreatedWood>, <ore:plateElectrum>, <ore:plankTreatedWood>]]);
recipes.addShaped(<immersiveengineering:metal_device0>, [[<ore:plankTreatedWood>, <ore:plateCopper>, <ore:plankTreatedWood>], [<cyberware:lower_organs_upgrades:2>, null, <cyberware:lower_organs_upgrades:2>], [<ore:plankTreatedWood>, <ore:plateCopper>, <ore:plankTreatedWood>]]);
recipes.addShaped(<tconstruct:soil> * 12, [[<tfc:fire_clay_block>, <tfc:fire_clay_block>, <ore:gravel>], [<ore:gravel>, <ore:dustAsh>, <ore:dustSkyStone>], [<ore:dustSkyStone>, <ore:dustSkyStone>, <ore:dustSkyStone>]]);
recipes.addShaped(<tconstruct:smeltery_controller>, [[<ore:ingotBrickSeared>, <ore:ingotBrickSeared>, <ore:ingotBrickSeared>], [<tetra:vent_plate>, <ore:circuitBasic>, <ore:plateTungstenSteel>], [<tetra:forged_bolt>, <ore:ingotBrickSeared>, <ore:ingotBrickSeared>]]);
recipes.addShaped(<tconstruct:smeltery_controller>, [[<ore:ingotBrickSeared>, <ore:ingotBrickSeared>, <ore:ingotBrickSeared>], [<tetra:vent_plate>, <ore:circuitBasic>, <ore:plateTungsten>], [<tetra:forged_bolt>, <ore:ingotBrickSeared>, <ore:ingotBrickSeared>]]);
recipes.addShaped(<tconstruct:seared:3> * 2, [[<ore:ingotBrickSeared>, <tetra:metal_scrap>, <ore:ingotBrickSeared>], [<ore:stickTungsten>, <ore:ingotBrickSeared>, <ore:stickTungsten>], [<ore:ingotBrickSeared>, <tetra:metal_scrap>, <ore:ingotBrickSeared>]]);
recipes.addShaped(<tconstruct:seared:3> * 2, [[<ore:ingotBrickSeared>, <tetra:metal_scrap>, <ore:ingotBrickSeared>], [<ore:stickTungstenSteel>, <ore:ingotBrickSeared>, <ore:stickTungstenSteel>], [<ore:ingotBrickSeared>, <tetra:metal_scrap>, <ore:ingotBrickSeared>]]);
recipes.addShaped(<tconstruct:seared:3> * 2, [[<ore:ingotBrickSeared>, <ore:stickTungsten>, <ore:ingotBrickSeared>], [<tetra:metal_scrap>, <ore:ingotBrickSeared>, <tetra:metal_scrap>], [<ore:ingotBrickSeared>, <ore:stickTungsten>, <ore:ingotBrickSeared>]]);
recipes.addShaped(<tconstruct:seared:3> * 2, [[<ore:ingotBrickSeared>, <ore:stickTungstenSteel>, <ore:ingotBrickSeared>], [<tetra:metal_scrap>, <ore:ingotBrickSeared>, <tetra:metal_scrap>], [<ore:ingotBrickSeared>, <ore:stickTungstenSteel>, <ore:ingotBrickSeared>]]);
recipes.addShaped(<tconstruct:seared_tank>, [[null, <ore:plateTungsten>, null], [<tetra:forged_beam>, <tconstruct:seared_glass>, <tetra:forged_beam>]]);
recipes.addShaped(<tconstruct:seared_tank>, [[null, <ore:plateTungstenSteel>, null], [<tetra:forged_beam>, <tconstruct:seared_glass>, <tetra:forged_beam>]]);
recipes.addShaped(<tconstruct:casting>, [[<tetra:metal_scrap>, <tetra:metal_scrap>, <tetra:metal_scrap>], [<ore:ingotBrickSeared>, <ore:plateTungsten>, <ore:ingotBrickSeared>], [<ore:ingotBrickSeared>, null, <ore:ingotBrickSeared>]]);
recipes.addShaped(<tconstruct:casting>, [[<tetra:metal_scrap>, <tetra:metal_scrap>, <tetra:metal_scrap>], [<ore:ingotBrickSeared>, <ore:plateTungstenSteel>, <ore:ingotBrickSeared>], [<ore:ingotBrickSeared>, null, <ore:ingotBrickSeared>]]);
recipes.addShaped(<tconstruct:casting:1>, [[<ore:ingotBrickSeared>, null, <ore:ingotBrickSeared>], [<tetra:metal_scrap>, null, <tetra:metal_scrap>], [<ore:ingotBrickSeared>, <ore:plateTungsten>, <ore:ingotBrickSeared>]]);
recipes.addShaped(<tconstruct:casting:1>, [[<ore:ingotBrickSeared>, null, <ore:ingotBrickSeared>], [<tetra:metal_scrap>, null, <tetra:metal_scrap>], [<ore:ingotBrickSeared>, <ore:plateTungstenSteel>, <ore:ingotBrickSeared>]]);
recipes.addShaped(<tconstruct:smeltery_io> * 2, [[<ore:ingotBrickSeared>, <tetra:metal_scrap>, <ore:ingotBrickSeared>], [<ore:ingotBrickSeared>, <tfc:metal/tuyere/tungsten_steel>, <ore:ingotBrickSeared>], [<ore:ingotBrickSeared>, <tetra:metal_scrap>, <ore:ingotBrickSeared>]]);
recipes.addShaped(<tconstruct:smeltery_io> * 2, [[<ore:ingotBrickSeared>, <tetra:metal_scrap>, <ore:ingotBrickSeared>], [<ore:ingotBrickSeared>, <tfc:metal/tuyere/tungsten>, <ore:ingotBrickSeared>], [<ore:ingotBrickSeared>, <tetra:metal_scrap>, <ore:ingotBrickSeared>]]);
recipes.addShaped(<ic2:wrench_new>, [[<ore:ingetAnyBronze>, null, <ore:ingetAnyBronze>], [null, <tfc:brass_mechanisms>, <ore:ingetAnyBronze>], [null, <ore:ingetAnyBronze>, null]]);
recipes.addShaped(<embers:ember_gauge> * 3, [[<minecraft:clock>], [<ore:plateCopper>]]);
recipes.addShaped(<embers:fluid_gauge> * 3, [[<minecraft:clock>], [<ore:sheetIron>]]);
recipes.addShaped(<mystgears:mechanical_dial> * 3, [[<minecraft:clock>], [<ore:plateGold>]]);
recipes.addShaped(<embers:clockwork_attenuator> * 3, [[<minecraft:clock>], [<ore:sheetBrass>]]);
recipes.addShaped(<pneumaticcraft:pressure_gauge>, [[<ore:dustRedstone>], [<ore:paper>], [<ore:ingotIronCompressed>]]);

recipes.addShaped(<pneumaticcraft:assembly_platform>, [[<pneumaticcraft:pneumatic_cylinder>, <pneumaticcraft:plastic:14>, <pneumaticcraft:pneumatic_cylinder>], [<ore:ingotIronCompressed>, <ore:ingotIronCompressed>, <ore:ingotIronCompressed>]]);
recipes.addShaped(<pneumaticcraft:assembly_laser>, [[null, <thaumcraft:focus_2>, <thaumcraft:vis_resonator>], [null, <pneumaticcraft:plastic:14>, <pneumaticcraft:pneumatic_cylinder>], [<ore:ingotIronCompressed>, <ore:ingotIronCompressed>, <ore:ingotIronCompressed>]]);
recipes.addShaped(<pneumaticcraft:assembly_drill>, [[null, <immersiveintelligence:drillhead:1>, <pneumaticcraft:turbine_rotor>], [null, <pneumaticcraft:plastic:14>, <pneumaticcraft:pneumatic_cylinder>], [<ore:ingotIronCompressed>, <ore:ingotIronCompressed>, <ore:ingotIronCompressed>]]);
recipes.addShaped(<pneumaticcraft:assembly_io_unit>, [[null, <tfctech:metal/iron_tongs>, <pneumaticcraft:pneumatic_cylinder>], [null, <pneumaticcraft:plastic:14>, <pneumaticcraft:pneumatic_cylinder>], [<ore:ingotIronCompressed>, <ore:ingotIronCompressed>, <ore:ingotIronCompressed>]]);
recipes.addShaped(<pneumaticcraft:assembly_controller>, [[null, <thaumcraft:brain_box>, null], [<pneumaticcraft:pressure_tube>, <thaumcraft:mechanism_simple>, null], [<ore:ingotIronCompressed>, <ore:ingotIronCompressed>, <ore:ingotIronCompressed>]]);
recipes.addShaped(<questionablyimmersive:metal_device>, [[<ore:dustRedstone>], [<ore:paper>], [<ore:plateRedAlloy>]]);
recipes.addShaped(<tconstruct:dried_clay:1> * 2, [[<tconstruct:materials:2>, <ore:mortar>, <tconstruct:materials:2>], [<ore:mortar>, <tconstruct:materials:2>, <ore:mortar>], [<tconstruct:materials:2>, <ore:mortar>, <tconstruct:materials:2>]]);
recipes.addShaped(<tfctech:smeltery_firebox>, [[<tconstruct:materials:2>, <tconstruct:materials:2>, <tconstruct:materials:2>], [<tconstruct:materials:2>, <ore:mortar>, <tconstruct:materials:2>]]);
recipes.addShaped(<tfctech:smeltery_cauldron>, [[<thaumcraft:slab_arcane_stone>], [<minecraft:cauldron>]]);
recipes.addShaped(<immersiveengineering:chemthrower>, [[null, <immersiveengineering:toolupgrade>, <ore:gungripWood>], [<immersiveengineering:toolupgrade>, <thaumcraft:metal_alchemical>, <ore:gungripWood>], [<immersiveengineering:material:8>, null, <ore:bucket>]]);
recipes.addShaped(<immersiveengineering:metal_device0:5> * 2, [[null, <ore:plateIron>, null], [<ore:barsIron>, <immersiveengineering:material:8>, <ore:barsIron>], [<ore:plateIron>, <ore:barsIron>, <ore:plateIron>]]);
recipes.addShaped(<embers:bin> * 2, [[<ore:nuggetIron>, null, <ore:nuggetIron>], [<ore:nuggetIron>, null, <ore:nuggetIron>], [<ore:nuggetIron>, <ore:nuggetIron>, <ore:nuggetIron>]]);
recipes.addShaped(<extrautils2:miner>, [[<thaumcraft:stone_arcane_brick>, <tfc:metal/pick/wrought_iron>, <thaumcraft:stone_arcane_brick>], [<thaumcraft:stone_arcane_brick>, <thaumcraft:mechanism_complex>, <thaumcraft:stone_arcane_brick>], [<thaumcraft:stone_arcane_brick>, <thaumcraft:brain_box>, <thaumcraft:stone_arcane_brick>]]);
recipes.addShaped(<extrautils2:user>, [[<thaumcraft:stone_arcane_brick>, <tfctech:metal/iron_tongs>, <thaumcraft:stone_arcane_brick>], [<thaumcraft:stone_arcane_brick>, <thaumcraft:mechanism_complex>, <thaumcraft:stone_arcane_brick>], [<thaumcraft:stone_arcane_brick>, <thaumcraft:brain_box>, <thaumcraft:stone_arcane_brick>]]);
recipes.addShaped(<embers:ember_pipe> * 16, [[null, <ore:wireCopper>, <ore:screwSilver>], [<ore:wireCopper>, <ore:stickLongRedSteel>, <ore:wireCopper>], [<ore:screwSilver>, <ore:wireCopper>, null]]);

recipes.addShaped(<embers:catalytic_plug> * 3, [[<minecraft:glass_bottle>, <minecraft:glass_bottle>, null], [null, <ore:gunpartRevolver>, <ore:plateSilver>], [<minecraft:glass_bottle>, <minecraft:glass_bottle>, null]]);
recipes.addShaped(<quark:iron_rod> * 4, [[<immersiveengineering:drillhead:1>], [<ore:rodWroughtIron>]]);
recipes.addShaped(<immersiveintelligence:sawblade:2>, [[null, <tfc:metal/saw_blade/tungsten>, null], [<tfc:metal/saw_blade/tungsten>, <ore:sleeveSteel>, <tfc:metal/saw_blade/tungsten>], [null, <tfc:metal/saw_blade/tungsten>, null]]);
recipes.addShaped(<immersiveintelligence:sawblade:1>, [[null, <tfc:metal/saw_blade/steel>, null], [<tfc:metal/saw_blade/steel>, <ore:sleeveBrass>, <tfc:metal/saw_blade/steel>], [null, <tfc:metal/saw_blade/steel>, null]]);
recipes.addShaped(<immersiveintelligence:sawblade>, [[null, <tfc:metal/saw_blade/wrought_iron>, null], [<tfc:metal/saw_blade/wrought_iron>, <ore:sleeveTin>, <tfc:metal/saw_blade/wrought_iron>], [null, <tfc:metal/saw_blade/wrought_iron>, null]]);
//recipes.addShaped(<adpother:aerometer>, [[<ore:nuggetCopper>, <ore:nuggetCopper>, <ore:nuggetCopper>], [<ore:nuggetCopper>, <tfc:brass_mechanisms>, <ore:nuggetCopper>], [null, <ore:stickWood>, null]]);
recipes.addShaped(<embers:item_transfer> * 2, [[<ore:stickLead>, <ore:sheetLead>, <ore:stickLead>], [<ore:stickLead>, <ore:paper>, <ore:stickLead>]]);
recipes.addShaped(<embers:vacuum>, [[<ore:sheetLead>, <thaumcraft:grapple_gun_tip>, <ore:sheetLead>], [<ore:sheetLead>, <mysticalmechanics:gear_fan>, <ore:sheetLead>], [null, <ore:blockHopper>, null]]);
recipes.addShaped(<firmalife:climate_station_4>, [[<ore:blockQuartzGlass>, <ore:blockQuartzGlass>, <ore:blockQuartzGlass>], [<thaumcraft:lamp_growth>, <firmalife:climate_station_3>, <thaumcraft:lamp_growth>], [<ore:ingotBlackSteel>, <ore:ingotBlackSteel>, <ore:ingotBlackSteel>]]);
recipes.addShaped(<firmalife:climate_station_3>, [[<ore:blockQuartzGlass>, <ore:blockQuartzGlass>, <ore:blockQuartzGlass>], [<ore:rodBlaze>, <firmalife:climate_station_2>, <ore:rodBlaze>], [<ore:ingotSteel>, <ore:ingotSteel>, <ore:ingotSteel>]]);
recipes.addShaped(<firmalife:climate_station_2>, [[<ore:blockGlassColorless>, <ore:blockGlassColorless>, <ore:blockGlassColorless>], [<magneticraft:thermometer>, <firmalife:climate_station_1>, <magneticraft:thermometer>], [<tfc:powder/fertilizer>, <tfc:powder/fertilizer>, <tfc:powder/fertilizer>]]);
recipes.addShaped(<firmalife:climate_station_1>, [[<ore:blockGlassColorless>, <ore:blockGlassColorless>, <ore:blockGlassColorless>], [<minecraft:observer>, <firmalife:climate_station>, <minecraft:observer>], [<immersivepetroleum:schematic>, <immersivepetroleum:schematic>, <immersivepetroleum:schematic>]]);
recipes.addShaped(<firmalife:climate_station>, [[<ore:blockGlassColorless>, <ore:blockGlassColorless>, <ore:blockGlassColorless>], [<ore:dustRedstone>, <ore:plateIron>, <ore:dustRedstone>], [<ore:lumber>, <ore:lumber>, <ore:lumber>]]);
recipes.addShaped(<minecraft:heavy_weighted_pressure_plate> * 16, [[<ore:plateIron>, <ore:plateIron>]]);
recipes.addShaped(<firmalife:sprinkler>, [[null, <ore:ingotDoubleRoseGold>, null], [<ore:screwRoseGold>, <tfc:brass_mechanisms>, <ore:screwRoseGold>], [null, <ore:screwRoseGold>, null]]);
recipes.addShaped(<firmalife:spout>, [[<ore:ingotLead>], [<ore:screwLead>]]);
recipes.addShaped(<mekanism:basicblock:8>, [[<ore:heavyPlateSteel>, <ore:heavyPlateSteel>, <ore:heavyPlateSteel>], [<ore:ingotCrudeSteel>, null, <ore:ingotCrudeSteel>], [<ore:heavyPlateSteel>, <ore:heavyPlateSteel>, <ore:heavyPlateSteel>]]);

recipes.addShaped(<appliedenergistics2:inscriber>, [[<ore:ingotSteel>, <cyberware:component>, <ore:ingotSteel>], [null, null, <ore:ingotSteel>], [<ore:ingotSteel>, <cyberware:component>, <ore:ingotSteel>]]);
recipes.addShaped(<extrautils2:analogcrafter>, [[<immersiveengineering:treated_wood>, <ore:ingotDoubleCopper>, <immersiveengineering:treated_wood>], [<immersiveengineering:treated_wood>, <thaumcraft:pattern_crafter>, <immersiveengineering:treated_wood>], [<immersiveengineering:treated_wood>, <thaumcraft:brain_box>, <immersiveengineering:treated_wood>]]);
recipes.addShaped(<extrautils2:crafter>, [[<thaumcraft:stone_arcane_brick>, <ore:ingotDoubleElectrum>, <thaumcraft:stone_arcane_brick>], [<thaumcraft:stone_arcane_brick>, <thaumcraft:pattern_crafter>, <thaumcraft:stone_arcane_brick>], [<thaumcraft:stone_arcane_brick>, <thaumcraft:brain_box>, <thaumcraft:stone_arcane_brick>]]);
recipes.addShaped(<tfc:blast_furnace>, [[<tetra:metal_scrap>, <tetra:metal_scrap>, <tetra:metal_scrap>], [<embers:archaic_brick>, <tetra:vent_plate>, <embers:archaic_brick>], [<embers:archaic_brick>, <embers:archaic_circuit>, <embers:archaic_brick>]]);
recipes.addShaped(<embers:archaic_circuit> * 2, [[null, <embers:archaic_brick>, null], [<ore:wireCopper>, <ore:fireClay>, <ore:wireCopper>], [null, <embers:archaic_brick>, null]]);
recipes.addShaped(<bloodmagic:soul_forge>, [[<embers:aspectus_silver>, null, <embers:aspectus_silver>], [<ore:ingotColdIron>, <embers:seed_silver>, <ore:ingotColdIron>], [<ore:ingotColdIron>, null, <ore:ingotColdIron>]]);
recipes.addShaped(<immersiveintelligence:mechanical_device1>, [[<tfc:bellows>, <ore:rodIron>, <tfc:bellows>], [<ore:barsIron>, <tfc:brass_mechanisms>, <ore:barsIron>], [<ore:plateBrass>, <ore:barsIron>, <ore:plateBrass>]]);
recipes.addShaped(<immersiveintelligence:motor_gear>, [[<ore:rackwheelPieceCopper>, null], [null, <ore:rackwheelPieceCopper>]]);
recipes.addShaped(<immersiveintelligence:motor_gear:1>, [[<ore:rackwheelPieceBrass>, null], [null, <ore:rackwheelPieceBrass>]]);
recipes.addShaped(<immersiveintelligence:motor_gear:2>, [[<ore:rackwheelPieceWroughtIron>, null], [null, <ore:rackwheelPieceWroughtIron>]]);
recipes.addShaped(<immersiveintelligence:motor_gear:3>, [[<ore:rackwheelPieceSteel>, null], [null, <ore:rackwheelPieceSteel>]]);
recipes.addShaped(<immersiveintelligence:motor_gear:4>, [[<ore:rackwheelPieceTungsten>, null], [null, <ore:rackwheelPieceTungsten>]]);
recipes.addShaped(<embers:cinder_plinth>, [[<ore:plateLead>, null, <ore:plateLead>], [<ore:ingotSilver>, <ore:powderBlaze>, <ore:ingotSilver>], [<embers:plate_caminite>, <embers:plate_caminite>, <embers:plate_caminite>]]);
recipes.addShaped(<tfc:bloomery>, [[<ore:sheetDoubleAnyBronze>, null, <ore:sheetDoubleAnyBronze>], [<ore:sheetDoubleAnyBronze>, null, <ore:sheetDoubleAnyBronze>], [<ore:tuyere>, <ore:tuyere>, <ore:tuyere>]]);

recipes.addShaped(<thaumcraft:flesh_block>, [[<minecraft:rotten_flesh>, <minecraft:rotten_flesh>, <minecraft:rotten_flesh>], [<minecraft:rotten_flesh>, <ore:bone>, <minecraft:rotten_flesh>], [<minecraft:rotten_flesh>, <minecraft:rotten_flesh>, <minecraft:rotten_flesh>]]);

recipes.addShaped(<tfc:metal/scythe/boron>, [[<tfc:metal/scythe_blade/boron>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/knife/boron>, [[<tfc:metal/knife_blade/boron>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/propick/boron>, [[<tfc:metal/propick_head/boron>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/hammer/boron>, [[<tfc:metal/hammer_head/boron>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/javelin/boron>, [[<tfc:metal/javelin_head/boron>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/saw/boron>, [[<tfc:metal/saw_blade/boron>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/mace/boron>, [[<tfc:metal/mace_head/boron>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/sword/boron>, [[<tfc:metal/sword_blade/boron>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/chisel/boron>, [[<tfc:metal/chisel_head/boron>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/hoe/boron>, [[<tfc:metal/hoe_head/boron>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/axe/boron>, [[<tfc:metal/axe_head/boron>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/shovel/boron>, [[<tfc:metal/shovel_head/boron>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/pick/boron>, [[<tfc:metal/pick_head/boron>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/scythe/manyullyn>, [[<tfc:metal/scythe_blade/manyullyn>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/knife/manyullyn>, [[<tfc:metal/knife_blade/manyullyn>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/propick/manyullyn>, [[<tfc:metal/propick_head/manyullyn>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/hammer/manyullyn>, [[<tfc:metal/hammer_head/manyullyn>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/javelin/manyullyn>, [[<tfc:metal/javelin_head/manyullyn>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/saw/manyullyn>, [[<tfc:metal/saw_blade/manyullyn>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/mace/manyullyn>, [[<tfc:metal/mace_head/manyullyn>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/sword/manyullyn>, [[<tfc:metal/sword_blade/manyullyn>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/chisel/manyullyn>, [[<tfc:metal/chisel_head/manyullyn>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/hoe/manyullyn>, [[<tfc:metal/hoe_head/manyullyn>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/axe/manyullyn>, [[<tfc:metal/axe_head/manyullyn>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/shovel/manyullyn>, [[<tfc:metal/shovel_head/manyullyn>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/pick/manyullyn>, [[<tfc:metal/pick_head/manyullyn>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/scythe/cobalt>, [[<tfc:metal/scythe_blade/cobalt>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/knife/cobalt>, [[<tfc:metal/knife_blade/cobalt>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/propick/cobalt>, [[<tfc:metal/propick_head/cobalt>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/hammer/cobalt>, [[<tfc:metal/hammer_head/cobalt>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/javelin/cobalt>, [[<tfc:metal/javelin_head/cobalt>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/saw/cobalt>, [[<tfc:metal/saw_blade/cobalt>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/mace/cobalt>, [[<tfc:metal/mace_head/cobalt>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/sword/cobalt>, [[<tfc:metal/sword_blade/cobalt>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/chisel/cobalt>, [[<tfc:metal/chisel_head/cobalt>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/hoe/cobalt>, [[<tfc:metal/hoe_head/cobalt>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/axe/cobalt>, [[<tfc:metal/axe_head/cobalt>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/shovel/cobalt>, [[<tfc:metal/shovel_head/cobalt>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/pick/cobalt>, [[<tfc:metal/pick_head/cobalt>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/scythe/aluminium>, [[<tfc:metal/scythe_blade/aluminium>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/knife/aluminium>, [[<tfc:metal/knife_blade/aluminium>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/propick/aluminium>, [[<tfc:metal/propick_head/aluminium>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/hammer/aluminium>, [[<tfc:metal/hammer_head/aluminium>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/javelin/aluminium>, [[<tfc:metal/javelin_head/aluminium>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/saw/aluminium>, [[<tfc:metal/saw_blade/aluminium>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/mace/aluminium>, [[<tfc:metal/mace_head/aluminium>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/sword/aluminium>, [[<tfc:metal/sword_blade/aluminium>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/chisel/aluminium>, [[<tfc:metal/chisel_head/aluminium>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/hoe/aluminium>, [[<tfc:metal/hoe_head/aluminium>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/axe/aluminium>, [[<tfc:metal/axe_head/aluminium>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/shovel/aluminium>, [[<tfc:metal/shovel_head/aluminium>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/pick/aluminium>, [[<tfc:metal/pick_head/aluminium>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/scythe/zircaloy>, [[<tfc:metal/scythe_blade/zircaloy>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/knife/zircaloy>, [[<tfc:metal/knife_blade/zircaloy>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/propick/zircaloy>, [[<tfc:metal/propick_head/zircaloy>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/hammer/zircaloy>, [[<tfc:metal/hammer_head/zircaloy>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/javelin/zircaloy>, [[<tfc:metal/javelin_head/zircaloy>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/saw/zircaloy>, [[<tfc:metal/saw_blade/zircaloy>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/mace/zircaloy>, [[<tfc:metal/mace_head/zircaloy>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/sword/zircaloy>, [[<tfc:metal/sword_blade/zircaloy>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/chisel/zircaloy>, [[<tfc:metal/chisel_head/zircaloy>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/hoe/zircaloy>, [[<tfc:metal/hoe_head/zircaloy>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/axe/zircaloy>, [[<tfc:metal/axe_head/zircaloy>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/shovel/zircaloy>, [[<tfc:metal/shovel_head/zircaloy>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/pick/zircaloy>, [[<tfc:metal/pick_head/zircaloy>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/scythe/tungsten_steel>, [[<tfc:metal/scythe_blade/tungsten_steel>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/knife/tungsten_steel>, [[<tfc:metal/knife_blade/tungsten_steel>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/propick/tungsten_steel>, [[<tfc:metal/propick_head/tungsten_steel>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/hammer/tungsten_steel>, [[<tfc:metal/hammer_head/tungsten_steel>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/javelin/tungsten_steel>, [[<tfc:metal/javelin_head/tungsten_steel>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/saw/tungsten_steel>, [[<tfc:metal/saw_blade/tungsten_steel>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/mace/tungsten_steel>, [[<tfc:metal/mace_head/tungsten_steel>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/sword/tungsten_steel>, [[<tfc:metal/sword_blade/tungsten_steel>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/chisel/tungsten_steel>, [[<tfc:metal/chisel_head/tungsten_steel>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/hoe/tungsten_steel>, [[<tfc:metal/hoe_head/tungsten_steel>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/axe/tungsten_steel>, [[<tfc:metal/axe_head/tungsten_steel>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/shovel/tungsten_steel>, [[<tfc:metal/shovel_head/tungsten_steel>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/pick/tungsten_steel>, [[<tfc:metal/pick_head/tungsten_steel>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/scythe/tungsten>, [[<tfc:metal/scythe_blade/tungsten>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/knife/tungsten>, [[<tfc:metal/knife_blade/tungsten>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/propick/tungsten>, [[<tfc:metal/propick_head/tungsten>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/hammer/tungsten>, [[<tfc:metal/hammer_head/tungsten>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/javelin/tungsten>, [[<tfc:metal/javelin_head/tungsten>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/saw/tungsten>, [[<tfc:metal/saw_blade/tungsten>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/mace/tungsten>, [[<tfc:metal/mace_head/tungsten>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/sword/tungsten>, [[<tfc:metal/sword_blade/tungsten>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/chisel/tungsten>, [[<tfc:metal/chisel_head/tungsten>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/hoe/tungsten>, [[<tfc:metal/hoe_head/tungsten>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/axe/tungsten>, [[<tfc:metal/axe_head/tungsten>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/shovel/tungsten>, [[<tfc:metal/shovel_head/tungsten>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/pick/tungsten>, [[<tfc:metal/pick_head/tungsten>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/scythe/invar>, [[<tfc:metal/scythe_blade/invar>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/knife/invar>, [[<tfc:metal/knife_blade/invar>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/propick/invar>, [[<tfc:metal/propick_head/invar>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/hammer/invar>, [[<tfc:metal/hammer_head/invar>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/javelin/invar>, [[<tfc:metal/javelin_head/invar>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/saw/invar>, [[<tfc:metal/saw_blade/invar>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/mace/invar>, [[<tfc:metal/mace_head/invar>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/sword/invar>, [[<tfc:metal/sword_blade/invar>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/chisel/invar>, [[<tfc:metal/chisel_head/invar>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/hoe/invar>, [[<tfc:metal/hoe_head/invar>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/axe/invar>, [[<tfc:metal/axe_head/invar>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/shovel/invar>, [[<tfc:metal/shovel_head/invar>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/pick/invar>, [[<tfc:metal/pick_head/invar>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/scythe/osmium>, [[<tfc:metal/scythe_blade/osmium>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/knife/osmium>, [[<tfc:metal/knife_blade/osmium>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/propick/osmium>, [[<tfc:metal/propick_head/osmium>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/hammer/osmium>, [[<tfc:metal/hammer_head/osmium>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/javelin/osmium>, [[<tfc:metal/javelin_head/osmium>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/saw/osmium>, [[<tfc:metal/saw_blade/osmium>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/mace/osmium>, [[<tfc:metal/mace_head/osmium>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/sword/osmium>, [[<tfc:metal/sword_blade/osmium>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/chisel/osmium>, [[<tfc:metal/chisel_head/osmium>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/hoe/osmium>, [[<tfc:metal/hoe_head/osmium>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/axe/osmium>, [[<tfc:metal/axe_head/osmium>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/shovel/osmium>, [[<tfc:metal/shovel_head/osmium>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/pick/osmium>, [[<tfc:metal/pick_head/osmium>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/scythe/titanium>, [[<tfc:metal/scythe_blade/titanium>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/knife/titanium>, [[<tfc:metal/knife_blade/titanium>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/propick/titanium>, [[<tfc:metal/propick_head/titanium>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/hammer/titanium>, [[<tfc:metal/hammer_head/titanium>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/javelin/titanium>, [[<tfc:metal/javelin_head/titanium>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/saw/titanium>, [[<tfc:metal/saw_blade/titanium>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/mace/titanium>, [[<tfc:metal/mace_head/titanium>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/sword/titanium>, [[<tfc:metal/sword_blade/titanium>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/chisel/titanium>, [[<tfc:metal/chisel_head/titanium>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/hoe/titanium>, [[<tfc:metal/hoe_head/titanium>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/axe/titanium>, [[<tfc:metal/axe_head/titanium>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/shovel/titanium>, [[<tfc:metal/shovel_head/titanium>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/pick/titanium>, [[<tfc:metal/pick_head/titanium>], [<ore:stickWood>]]);
recipes.addShaped(<cyberware:beacon_large>, [[<ore:rodWroughtIron>, <ore:enderpearl>, <ore:rodWroughtIron>], [<ore:rodWroughtIron>, <ore:circuitBasic>, <ore:rodWroughtIron>], [<cyberware:component:2>, <ore:plateBismuth>, <cyberware:component:2>]]);
recipes.addShaped(<tfc:metal/saw/nickel_silver>, [[<tfc:metal/saw_blade/nickel_silver>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/scythe/nickel_silver>, [[<tfc:metal/scythe_blade/nickel_silver>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/propick/nickel_silver>, [[<tfc:metal/propick_head/nickel_silver>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/sword/nickel_silver>, [[<tfc:metal/sword_blade/nickel_silver>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/hammer/nickel_silver>, [[<tfc:metal/hammer_head/nickel_silver>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/javelin/nickel_silver>, [[<tfc:metal/javelin_head/nickel_silver>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/chisel/nickel_silver>, [[<tfc:metal/chisel_head/nickel_silver>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/hoe/nickel_silver>, [[<tfc:metal/hoe_head/nickel_silver>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/axe/nickel_silver>, [[<tfc:metal/axe_head/nickel_silver>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/shovel/nickel_silver>, [[<tfc:metal/shovel_head/nickel_silver>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/pick/nickel_silver>, [[<tfc:metal/pick_head/nickel_silver>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/scythe/beryllium_copper>, [[<tfc:metal/scythe_blade/beryllium_copper>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/knife/beryllium_copper>, [[<tfc:metal/knife_blade/beryllium_copper>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/propick/beryllium_copper>, [[<tfc:metal/propick_head/beryllium_copper>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/hammer/beryllium_copper>, [[<tfc:metal/hammer_head/beryllium_copper>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/sword/beryllium_copper>, [[<tfc:metal/sword_blade/beryllium_copper>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/mace/beryllium_copper>, [[<tfc:metal/mace_head/beryllium_copper>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/saw/beryllium_copper>, [[<tfc:metal/saw_blade/beryllium_copper>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/javelin/beryllium_copper>, [[<tfc:metal/javelin_head/beryllium_copper>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/chisel/beryllium_copper>, [[<tfc:metal/chisel_head/beryllium_copper>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/hoe/beryllium_copper>, [[<tfc:metal/hoe_head/beryllium_copper>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/axe/beryllium_copper>, [[<tfc:metal/axe_head/beryllium_copper>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/shovel/beryllium_copper>, [[<tfc:metal/shovel_head/beryllium_copper>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/pick/beryllium_copper>, [[<tfc:metal/pick_head/beryllium_copper>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/scythe/mithril>, [[<tfc:metal/scythe_blade/mithril>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/knife/mithril>, [[<tfc:metal/knife_blade/mithril>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/propick/mithril>, [[<tfc:metal/propick_head/mithril>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/hammer/mithril>, [[<tfc:metal/hammer_head/mithril>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/javelin/mithril>, [[<tfc:metal/javelin_head/mithril>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/saw/mithril>, [[<tfc:metal/saw_blade/mithril>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/mace/mithril>, [[<tfc:metal/mace_head/mithril>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/sword/mithril>, [[<tfc:metal/sword_blade/mithril>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/chisel/mithril>, [[<tfc:metal/chisel_head/mithril>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/hoe/mithril>, [[<tfc:metal/hoe_head/mithril>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/axe/mithril>, [[<tfc:metal/axe_head/mithril>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/shovel/mithril>, [[<tfc:metal/shovel_head/mithril>], [<ore:stickWood>]]);
recipes.addShaped(<tfc:metal/pick/mithril>, [[<tfc:metal/pick_head/mithril>], [<ore:stickWood>]]);
recipes.addShaped(<immersiveintelligence:metal_decoration:1> * 3, [[<ore:ingotShadowSteel>, <ore:circuitBasic>, <ore:ingotShadowSteel>], [<ore:circuitBasic>, <ore:scaffoldingAluminum>, <ore:circuitBasic>], [<ore:ingotShadowSteel>, <ore:circuitBasic>, <ore:ingotShadowSteel>]]);
recipes.addShaped(<metallurgy:orichalcum_buckler>, [[null, <ore:gemJade>, null], [<ore:gemJade>, <tfc:metal/shield/bismuth_bronze>, <ore:gemJade>], [null, <ore:gemJade>, null]]);
recipes.addShaped(<thermalexpansion:frame> * 2, [[<ore:sheetDoubleTitanium>, <ic2:glass>, <ore:sheetDoubleTitanium>], [<ic2:glass>, <ore:circuitAdvanced>, <ic2:glass>], [<ore:heavyPlateSteel>, <ic2:glass>, <ore:heavyPlateSteel>]]);
recipes.addShaped(<extrautils2:spike_diamond>, [[null, <tfc:metal/knife_blade/cobalt>, null], [<ore:dustDiamond>, <tfc:gem/diamond:3>, <ore:dustDiamond>]]);
recipes.addShaped(<extrautils2:spike_gold>, [[null, <tfc:metal/knife_blade/bronze>, null], [<ore:nuggetGold>, <ore:blockSheetmetalGold>, <ore:nuggetGold>]]);
recipes.addShaped(<extrautils2:spike_iron>, [[null, <tfc:metal/knife_blade/wrought_iron>, null], [<ore:nuggetWroughtIron>, <quark:iron_plate>, <ore:nuggetWroughtIron>]]);
recipes.addShaped(<tfc:metal/anvil/zircaloy>, [[<ore:ingotDoubleZircaloy>, <ore:ingotDoubleZircaloy>, <ore:ingotDoubleZircaloy>], [null, <ore:ingotDoubleZircaloy>, null], [<ore:ingotDoubleZircaloy>, <ore:ingotDoubleZircaloy>, <ore:ingotDoubleZircaloy>]]);
recipes.addShaped(<tfc:metal/anvil/invar>, [[<ore:ingotDoubleInvar>, <ore:ingotDoubleInvar>, <ore:ingotDoubleInvar>], [null, <ore:ingotDoubleInvar>, null], [<ore:ingotDoubleInvar>, <ore:ingotDoubleInvar>, <ore:ingotDoubleInvar>]]);
recipes.addShaped(<tfc:metal/anvil/mithril>, [[<ore:ingotDoubleMithril>, <ore:ingotDoubleMithril>, <ore:ingotDoubleMithril>], [null, <ore:ingotDoubleMithril>, null], [<ore:ingotDoubleMithril>, <ore:ingotDoubleMithril>, <ore:ingotDoubleMithril>]]);
recipes.addShaped(<tfc:metal/anvil/tungsten>, [[<ore:ingotDoubleTungsten>, <ore:ingotDoubleTungsten>, <ore:ingotDoubleTungsten>], [null, <ore:ingotDoubleTungsten>, null], [<ore:ingotDoubleTungsten>, <ore:ingotDoubleTungsten>, <ore:ingotDoubleTungsten>]]);
recipes.addShaped(<tfc:metal/anvil/manyullyn>, [[<ore:ingotDoubleManyullyn>, <ore:ingotDoubleManyullyn>, <ore:ingotDoubleManyullyn>], [null, <ore:ingotDoubleManyullyn>, null], [<ore:ingotDoubleManyullyn>, <ore:ingotDoubleManyullyn>, <ore:ingotDoubleManyullyn>]]);
recipes.addShaped(<tfc:metal/anvil/boron>, [[<ore:ingotDoubleBoron>, <ore:ingotDoubleBoron>, <ore:ingotDoubleBoron>], [null, <ore:ingotDoubleBoron>, null], [<ore:ingotDoubleBoron>, <ore:ingotDoubleBoron>, <ore:ingotDoubleBoron>]]);
recipes.addShaped(<tfc:metal/anvil/aluminium>, [[<ore:ingotDoubleAluminium>, <ore:ingotDoubleAluminium>, <ore:ingotDoubleAluminium>], [null, <ore:ingotDoubleAluminium>, null], [<ore:ingotDoubleAluminium>, <ore:ingotDoubleAluminium>, <ore:ingotDoubleAluminium>]]);
recipes.addShaped(<tfc:metal/anvil/osmium>, [[<ore:ingotDoubleOsmium>, <ore:ingotDoubleOsmium>, <ore:ingotDoubleOsmium>], [null, <ore:ingotDoubleOsmium>, null], [<ore:ingotDoubleOsmium>, <ore:ingotDoubleOsmium>, <ore:ingotDoubleOsmium>]]);
recipes.addShaped(<tfc:metal/anvil/beryllium_copper>, [[<ore:ingotDoubleBerylliumCopper>, <ore:ingotDoubleBerylliumCopper>, <ore:ingotDoubleBerylliumCopper>], [null, <ore:ingotDoubleBerylliumCopper>, null], [<ore:ingotDoubleBerylliumCopper>, <ore:ingotDoubleBerylliumCopper>, <ore:ingotDoubleBerylliumCopper>]]);
recipes.addShaped(<tfc:metal/anvil/titanium>, [[<ore:ingotDoubleTitanium>, <ore:ingotDoubleTitanium>, <ore:ingotDoubleTitanium>], [null, <ore:ingotDoubleTitanium>, null], [<ore:ingotDoubleTitanium>, <ore:ingotDoubleTitanium>, <ore:ingotDoubleTitanium>]]);
recipes.addShaped(<tfc:metal/anvil/nickel_silver>, [[<ore:ingotDoubleNickelSilver>, <ore:ingotDoubleNickelSilver>, <ore:ingotDoubleNickelSilver>], [null, <ore:ingotDoubleNickelSilver>, null], [<ore:ingotDoubleNickelSilver>, <ore:ingotDoubleNickelSilver>, <ore:ingotDoubleNickelSilver>]]);
recipes.addShaped(<tfc:metal/anvil/cobalt>, [[<ore:ingotDoubleCobalt>, <ore:ingotDoubleCobalt>, <ore:ingotDoubleCobalt>], [null, <ore:ingotDoubleCobalt>, null], [<ore:ingotDoubleCobalt>, <ore:ingotDoubleCobalt>, <ore:ingotDoubleCobalt>]]);
recipes.addShaped(<tconstruct:pattern> * 6, [[<ore:stickWood>, <ore:lumber>, <ore:stickWood>], [<ore:lumber>, <ore:lumber>, <ore:lumber>], [<ore:stickWood>, <ore:lumber>, <ore:stickWood>]]);
recipes.addShaped(<mystgears:drill_diamond>, [ [<embers:mech_core>, <immersiveintelligence:drillhead:1>]]);
recipes.addShaped(<mystgears:drill>, [[<embers:mech_core>, <immersiveengineering:drillhead:1>]]);


recipes.addShaped(<thaumcraft:phial> * 8, [[<ore:itemClay>], [<ore:gemJade>]]);
recipes.addShaped(<thaumcraft:phial> * 8, [[null, <ore:itemClay>, null], [<ore:gemChippedJade>, null, <ore:gemChippedJade>], [null, <ore:gemChippedJade>, null]]);
recipes.addShaped(<thaumcraft:phial> * 8, [[<ore:itemClay>], [<ore:gemFlawedJade>], [<ore:gemFlawedJade>]]);
recipes.addShaped(<mystgears:windup_box>, [[<quark:iron_plate_slab>, <quark:iron_plate_slab>, <quark:iron_plate_slab>], [<ore:springBrass>, <ore:springBrass>, <ore:craftingPiston>], [<quark:iron_plate_slab>, <quark:iron_plate_slab>, <quark:iron_plate_slab>]]);
recipes.addShaped(<embers:block_tank>, [[<ore:brick>, null, <ore:brick>], [<ore:brick>, <minecraft:cauldron>, <ore:brick>]]);
recipes.addShaped(<immersiveengineering:tool:1>, [[<ore:stickWood>, <ore:shears>], [null, <ore:stickWood>]]);
recipes.addShaped(<extrautils2:drum> * 2, [[<quark:sturdy_stone>, <thaumcraft:slab_arcane_stone>, <quark:sturdy_stone>], [<quark:sturdy_stone>, <minecraft:cauldron>, <quark:sturdy_stone>], [<quark:sturdy_stone>, <thaumcraft:slab_arcane_stone>, <quark:sturdy_stone>]]);
recipes.addShaped(<quark:iron_plate>, [[null, <ore:nuggetIron>, null], [<ore:nuggetIron>, null, <ore:nuggetIron>]]);
recipes.addShaped(<embers:clockwork_attenuator>, [[<ore:dustRedstone>], [<ore:paper>], [<ore:sheetBrass>]]);
recipes.addShaped(<mysticalmechanics:mergebox_frame> * 2, [[<ore:rodGold>, <tfc:brass_mechanisms>, <ore:rodGold>], [null, <ore:ingotDoubleIron>, null], [<ore:rodGold>, <tfc:brass_mechanisms>, <ore:rodGold>]]);
recipes.addShaped(<mysticalmechanics:gearbox_frame> * 2, [[<ore:rodWroughtIron>, null, <ore:rodWroughtIron>], [null, <ore:ingotDoubleIron>, null], [<ore:rodWroughtIron>, null, <ore:rodWroughtIron>]]);
recipes.addShaped(<travelersbackpack:travelers_backpack>, [[<thaumcraft:baubles:2>, <ore:leather>, <thaumcraft:baubles:2>], [<minecraft:glass_bottle>, <ore:chest>, <minecraft:glass_bottle>], [<ore:leather>, <ore:clothHighQuality>, <ore:leather>]]);
recipes.addShaped(<thermalexpansion:satchel>, [[null, <ore:leather>, null], [null, <ore:nuggetCopper>, null], [<ore:leather>, <ore:clothHighQuality>, <ore:leather>]]);
recipes.addShaped(<ic2:dust:6> * 9, [[<ore:dustRedstone>, <ore:dustLithium>, <ore:dustRedstone>], [<ore:dustLithium>, <ore:dustRedstone>, <ore:dustLithium>], [<ore:dustRedstone>, <ore:dustLithium>, <ore:dustRedstone>]]);
recipes.addShaped(<metallurgy:rubracium_gauntlet>*2, [[<ore:leather>, <ore:leather>], [<ore:ingotRedSteel>, <ore:ingotRedSteel>]]);
recipes.addShaped(<tetra:journal>, [[null, <embers:archaic_brick>, null], [<embers:archaic_brick>, <ore:dustBedrock>, <embers:archaic_brick>], [null, <embers:archaic_brick>, null]]);
recipes.addShaped(<tetra:toolbelt_modular>.withTag({"toolbelt/belt_material": "belt/rope", "toolbelt/belt": "toolbelt/belt", "toolbelt/slot1": "toolbelt/strap_slot1", "toolbelt/strap_slot1_material": "strap1/leather"}), [[null, <tfc:crop/product/jute_fiber>, null], [<tfc:crop/product/jute_fiber>, null, <tfc:crop/product/jute_fiber>], [null, <tfc:crop/product/jute_fiber>, null]]);
recipes.addShaped(<tetra:toolbelt_modular>.withTag({"toolbelt/belt_material": "belt/rope", "toolbelt/belt": "toolbelt/belt", "toolbelt/slot1": "toolbelt/strap_slot1", "toolbelt/strap_slot1_material": "strap1/leather"}), [[null, <ore:string>, null], [<ore:string>, null, <ore:string>], [null, <ore:string>, null]]);
recipes.addShaped(<tetra:duplex_tool_modular>.withTag({"duplex/basic_hammer_right_material": "basic_hammer/log", "duplex/basic_hammer_left_material": "basic_hammer/log", "duplex/handle": "duplex/basic_handle", "duplex/head_left": "duplex/basic_hammer_left", "duplex/basic_handle_material": "basic_handle/stick", "duplex/head_right": "duplex/basic_hammer_right"}), [[null, <ore:logWood>], [<ore:stickWood>, <ore:slimeball>]]);
recipes.addShaped(<minecraft:wooden_sword>, [[<ore:lumber>, null], [<ore:lumber>, <ore:slimeball>], [<ore:stickWood>, <ore:slimeball>]]);
recipes.addShaped(<immersiveengineering:toolupgrade:1>, [[<liquid:olive_oil>*1000, <ore:ingotIron>, null], [<ore:ingotIron>, <liquid:olive_oil>*1000, <ore:ingotIron>], [null, <ore:ingotIron>, <immersiveengineering:material:8>]]);
recipes.addShaped(<immersiveengineering:drill>, [[null, <embers:fluid_gauge>, <ore:gungripWood>], [null, <embers:blasting_core>, <ore:gungripWood>], [<ore:rodIron>, null, null]]);
recipes.addShaped(<tfctech:induction_crucible>, [[<ore:ingotElectricalSteel>, null, <ore:ingotElectricalSteel>], [<ic2:crafting:5>, <tfc:crucible>, <ic2:crafting:5>], [<ore:ingotElectricalSteel>, <ore:circuitBasic>, <ore:ingotElectricalSteel>]]);
recipes.addShaped(<tfctech:fridge>, [[<ic2:casing:6>, <magneticraft:heat_sink>], [<ic2:casing:6>, <ic2:te:43>], [<ic2:casing:6>, <ore:doorIron>]]);
recipes.addShaped(<tfctech:electric_forge>, [[<ore:ingotElectricalSteel>, null, <ore:ingotElectricalSteel>], [<ic2:crafting:5>, <tfc:fire_bricks>, <ic2:crafting:5>], [<ore:ingotElectricalSteel>, <ore:circuitBasic>, <ore:ingotElectricalSteel>]]);
recipes.addShaped(<minecraft:compass>, [[<tfc:ore/small/magnetite>], [<tfc:ceramics/fired/bowl>]]);
recipes.addShaped(<minecraft:compass>, [[<ore:torchRedstoneActive>], [<tfc:ceramics/fired/bowl>]]);
recipes.addShaped(<ic2:ingot> * 2, [[<ore:ingotDuraluminium>], [<ore:ingotArdite>], [<ore:ingotPlatinum>]]);
recipes.addShaped(<ic2:glass> * 7, [[<immersiveengineering:stone_decoration:8>, <ore:plateAdvancedAlloy>, <immersiveengineering:stone_decoration:8>], [<immersiveengineering:stone_decoration:8>, <immersiveengineering:stone_decoration:8>, <immersiveengineering:stone_decoration:8>], [<immersiveengineering:stone_decoration:8>, <ore:plateAdvancedAlloy>, <immersiveengineering:stone_decoration:8>]]);
recipes.addShaped(<thermalfoundation:material:515> * 4, [[null, <ore:wireRedSteel>, <ic2:dust:6>], [<ore:wireRedSteel>, <ore:stickElectrum>, <ore:wireRedSteel>], [<ic2:dust:6>, <ore:wireRedSteel>, null]]);
recipes.addShaped(<thermalfoundation:material:514> * 4, [[null, <ore:wireRedSteel>, <ic2:dust:6>], [<ore:wireRedSteel>, <ore:stickSilver>, <ore:wireRedSteel>], [<ic2:dust:6>, <ore:wireRedSteel>, null]]);
recipes.addShaped(<thermalfoundation:material:513> * 4, [[null, <ore:wireRedSteel>, <ic2:dust:6>], [<ore:wireRedSteel>, <ore:stickGold>, <ore:wireRedSteel>], [<ic2:dust:6>, <ore:wireRedSteel>, null]]);
recipes.addShaped(<firmalife:greenhouse_wall> * 16, [[<ore:ingotPigIron>, <ore:ingotPigIron>], [<ore:ingotPigIron>, <ore:ingotPigIron>]]);
recipes.addShaped(<firmalife:greenhouse_roof> * 12, [[null, null, <ore:ingotPigIron>], [null, <ore:ingotPigIron>, null], [<ore:ingotPigIron>, null, <ore:ingotPigIron>]]);
recipes.addShaped(<mekanism:basicblock:14>, [[<ore:circuitUltimate>, <ore:circuitUltimate>, <ore:circuitUltimate>], [<mekanism:basicblock2>, <mekanism:basicblock:8>, <mekanism:basicblock2>], [<mekanism:basicblock2>, <mekanism:basicblock2>, <mekanism:basicblock2>]]);

recipes.addShaped(<embers:boiler>, [[<ore:ingotCopper>, <ore:ingotCopper>, <ore:ingotCopper>], [<ore:rodWroughtIron>, <ore:grill>, <ore:rodWroughtIron>], [<ore:rodWroughtIron>, <tfc:metal/lamp/copper>, <ore:rodWroughtIron>]]);
recipes.addShaped(<minecraft:piston>, [[<ore:lumber>,<ore:lumber>,<ore:lumber>],[<ore:cobblestone>,<ore:rodWroughtIron>,<ore:cobblestone>],[<ore:cobblestone>,<tfc:brass_mechanisms>,<ore:cobblestone>]]);
recipes.addShaped(<magneticraft:connector> * 4, [[<ore:nuggetTungsten>, <ore:nuggetTungsten>, <ore:nuggetTungsten>], [null, <ore:nuggetTungsten>, null], [null, <ore:ingotIron>, null]]);
recipes.addShaped(<metallurgy:bimetal_structure_block> * 2, [[<ore:ingotBrass>, <ore:ingotWroughtIron>, <ore:ingotBrass>], [<ore:ingotWroughtIron>, null, <ore:ingotWroughtIron>], [<ore:ingotBrass>, <ore:ingotWroughtIron>, <ore:ingotBrass>]]);
recipes.addShaped(<metallurgy:bimetal_structure_block> * 16, [[<ore:ingotZirconium>, <ore:ingotNickel>, <ore:ingotZirconium>], [<ore:ingotNickel>, null, <ore:ingotNickel>], [<ore:ingotZirconium>, <ore:ingotNickel>, <ore:ingotZirconium>]]);
recipes.addShaped(<advancedrocketry:thermitetorch> * 4, [[<ore:dustThermite>], [<ore:stickWood>]]);
recipes.addShaped(<mekanism:machineblock:8>, [[<ore:alloyBasic>, <ore:circuitBasic>, <ore:alloyBasic>], [<minecraft:compass>, <mekanism:basicblock:8>, <minecraft:compass>], [<ore:alloyBasic>, <ore:circuitBasic>, <ore:alloyBasic>]]);
recipes.addShaped(<ic2:te:81>, [[null, <ore:plateAluminum>, null], [<ore:plateAluminum>, <ic2:fluid_cell>, <ore:plateAluminum>], [null, <ore:plateAluminum>, null]]);








