// File generated by MineTweakerRecipeMaker
//                     READ THIS HEADER BEFORE EDITING ANYTHING
// ================================================================================
//     This file is read and changed by the mod.
//     If you remove/edit any of the markers, IT WILL STOP WORKING!
//     If you want to make manual edits, make a backup of this file!
//     Markers look like this: "//#MARKER something"
//     They indicate where calls should be placed, so that MineTweaker does them in the correct order.
//     Removes come first, then stuff is added.
// ================================================================================
//

// ================================================================================
//#MARKER REMOVE

// ================================================================================
//#MARKER REMOVE SHAPELESS
recipes.removeShapeless(<thaumcraft:plank_greatwood> * 4, [<thaumcraft:log_greatwood>]);
recipes.removeShapeless(<thaumcraft:plank_silverwood> * 4, [<thaumcraft:log_silverwood>]);
recipes.remove(<minecraft:detector_rail>);
recipes.remove(<minecraft:golden_rail>);
recipes.remove(<thebetweenlands:items_misc:47>);
recipes.remove(<travelersbackpack:hose_nozzle>);
recipes.remove(<tfc:metal/sheet/brass>);
recipes.remove(<minecraft:bucket>);
recipes.remove(<minecraft:beacon>);
recipes.remove(<embers:fluid_transfer>);
recipes.remove(<tfc:powder/flux>);
recipes.remove(<botania:opencrate:1>);
// ================================================================================
//#MARKER REMOVE SHAPED
recipes.removeShaped(<minecraft:chest>, [[<ore:plankWood>, <ore:plankWood>, <ore:plankWood>], [<ore:plankWood>, null, <ore:plankWood>], [<ore:plankWood>, <ore:plankWood>, <ore:plankWood>]]);
recipes.removeShaped(<minecraft:chest> * 4, [[<ore:logWood>, <ore:logWood>, <ore:logWood>], [<ore:logWood>, null, <ore:logWood>], [<ore:logWood>, <ore:logWood>, <ore:logWood>]]);
recipes.removeShaped(<tfctech:wire_draw_bench>, [[<tfctech:wiredraw/winch>, <tfctech:wiredraw/leather_belt>, <ore:tongsWroughtIron>], [<ore:sheetWroughtIron>, <ore:sheetWroughtIron>, <ore:sheetWroughtIron>], [<ore:sheetWroughtIron>, null, <ore:sheetWroughtIron>]]);
recipes.removeShaped(<travelersbackpack:travelers_backpack>, [[<ore:leather>, <ore:ingotGold>, <ore:leather>], [<travelersbackpack:backpack_tank>, <ore:chest>, <travelersbackpack:backpack_tank>], [<ore:leather>, <travelersbackpack:sleeping_bag_bottom>, <ore:leather>]]);
recipes.removeShaped(<mysticalmechanics:axle_iron> * 8, [[<ore:ingotIron>], [<ore:nuggetWroughtIron>], [<ore:ingotIron>]]);
recipes.removeShaped(<tfc:metal/sheet/brass> * 3, [[<ore:ingotBrass>, <ore:ingotBrass>, <ore:ingotBrass>]]);
recipes.removeShaped(<tfc:metal/sheet/wrought_iron> * 3, [[<ore:ingotIron>, <ore:ingotIron>, <ore:ingotIron>]]);
recipes.removeShaped(<immersiveengineering:metal_device0:6>, [[<ore:plateIron>, <ore:barsIron>, <ore:plateIron>], [<ore:barsIron>, null, <ore:barsIron>], [<ore:plateIron>, <ore:barsIron>, <ore:plateIron>]]);
recipes.removeShaped(<camping:knife>, [[<minecraft:dye:1>, <minecraft:iron_ingot>, <minecraft:dye:1>], [<minecraft:dye:1>, <minecraft:iron_ingot>, <minecraft:dye:1>], [<minecraft:dye:1>, <minecraft:iron_ingot>, <minecraft:dye:1>]]);
recipes.removeShaped(<immersiveengineering:jerrycan>, [[null, <ore:plateIron>, <ore:plateIron>], [<ore:plateIron>, <minecraft:bucket>, <minecraft:bucket>], [<ore:plateIron>, <minecraft:bucket>, <minecraft:bucket>]]);
recipes.removeShaped(<thaumcraft:baubles:6>, [[null, <ore:leather>, null], [<ore:leather>, <ore:gemDiamond>, <ore:leather>], [null, <ore:ingotGold>, null]]);
recipes.removeShaped(<thaumcraft:baubles:4>, [[null, <ore:string>, null], [<ore:string>, <ore:gemDiamond>, <ore:string>], [null, <ore:ingotGold>, null]]);
recipes.remove(<immersiveengineering:metal_device1:6>);
recipes.removeShaped(<thaumcraft:plank_greatwood> * 4, [[<thaumcraft:log_greatwood>]]);
recipes.removeShaped(<thaumcraft:plank_silverwood> * 4, [[<thaumcraft:log_silverwood>]]);

// ================================================================================
//#MARKER ADD

// ================================================================================
//#MARKER ADD SHAPELESS
recipes.addShapeless(<quark:diamond_heart>, [<ore:gemExquisiteDiamond>, <ore:ingotUnstable>]);
recipes.addShapeless(<immersiveintelligence:material_ingot:5> * 2, [<thaumcraft:nugget:10>, <ore:ingotIron>, <ore:ingotIron>]);
recipes.addShapeless(<tfc:fire_bricks>, [<tfc:ceramics/fired/fire_brick>, <tfc:ceramics/fired/fire_brick>, <ore:ingotBrickNether>, <ore:ingotBrickNether>, <tfc:mortar>]);
recipes.addShapeless(<projectred-core:resource_item:251>, [<ore:ingotCopper>, <ore:dustRedstone>, <ore:dustRedstone>, <ore:dustRedstone>, <ore:dustRedstone>,<ore:dustRedstone>, <ore:dustRedstone>, <ore:dustRedstone>, <ore:dustRedstone>]);

recipes.addShapeless(<minecraft:poisonous_potato> * 4, [<tfc:food/potato>, <tfc:food/potato>, <tfc:food/potato>, <tfc:food/potato>, <minecraft:fermented_spider_eye>]);
recipes.addShapeless(<tfc:ore/malachite/basalt> * 8, [<ore:blockCopper>, <ore:stoneBasalt>]);
recipes.addShapeless(<tfc:ore/microcline/basalt> * 8, [<thebetweenlands:ancient_remnant_block>, <ore:stoneBasalt>]);
recipes.addShapeless(<tfc:ore/microcline/basalt>, [<ore:gemMicrocline>, <ore:stoneBasalt>]);
recipes.addShapeless(<quark:polished_stone>, [<ore:stonePolished>, <thebetweenlands:items_misc:32>]);
recipes.addShapeless(<minecraft:stone:5>, [<ore:stoneAndesite>]);
recipes.addShapeless(<minecraft:stone:3>, [<ore:stoneDiorite>]);
recipes.addShapeless(<minecraft:stone:1>, [<ore:stoneGranite>]);

recipes.addShapeless(<immersiveengineering:material:1>, [<ore:rodIron>]);
recipes.addShapeless(<camping:sleeping_bag>, [<ore:clothHighQuality>, <ore:dyeRed>, <camping:knife>.reuse()]);
recipes.addShapeless(<camping:parts:2>, [<ore:pickHead>, <ore:hammer>.transformDamage(1)]);
recipes.addShapeless(<minecraft:pumpkin>, [<firmalife:lit_pumpkin_face>]);
recipes.addShapeless(<tfc:metal/sheet/brass>, [<ore:sheetmetalBrass>]);
recipes.addShapeless(<minecraft:slime_ball>, [<ore:glue>, <ore:dyeLime>]);
recipes.addShapeless(<tfc:metal/nugget/wrought_iron> * 9, [<ore:ingotWroughtIron>]);
recipes.addShapeless(<tfc:metal/ingot/wrought_iron>, [<minecraft:iron_ingot>]);
recipes.addShapeless(<tfc:metal/ingot/gold>, [<minecraft:gold_ingot>]);
recipes.addShapeless(<minecraft:gold_ingot>, [<tfc:metal/ingot/gold>, <ore:paper>]);
recipes.addShapeless(<minecraft:iron_ingot>, [<ore:ingotWroughtIron>, <ore:paper>]);

recipes.addShapeless(<minecraft:glowstone_dust> * 3, [<ore:hammer>.transformDamage(1), <ore:gemSelenite>]);
recipes.addShapeless(<tfc:metal/nugget/gold> * 9, [<ore:ingotGold>]);
recipes.addShapeless(<immersiveengineering:material:17>, [<ore:dustGraphite>]);

recipes.addShapeless(<bountifulbaubles:reforger>, [<minecraft:cauldron>, <ore:anvil>, <ore:workbench>, <thaumcraft:phial:1>.withTag({Aspects: [{amount: 10, key: "ignis"}]})]);
recipes.addShapeless(<thaumcraft:plate:1>, [<ore:sheetIron>]);
recipes.addShapeless(<thaumcraft:plate>, [<ore:sheetBrass>]);

recipes.addShapeless(<immersiveintelligence:material:31>, [<tfctech:latex/vulcanizing_agents>, <tfctech:latex/vulcanizing_agents>]);
recipes.addShapeless(<projectred-core:resource_item>, [<ore:brick>, <ore:hammer>.transformDamage(1)]);
recipes.addShapeless(<projectred-core:resource_item:250>, [<ore:charcoal>, <ore:charcoal>, <ore:sandSilica>, <ore:sandSilica>]);
recipes.addShapeless(<projectred-core:resource_item:250>, [<ore:fuelCoke>, <ore:sandSilica>]);
recipes.addShapeless(<thaumcraft:plank_silverwood> * 2, [<thaumcraft:log_silverwood>, <ore:saw>.transformDamage(1)]);
recipes.addShapeless(<thaumcraft:plank_greatwood> * 2, [<thaumcraft:log_greatwood>, <ore:saw>.transformDamage(1)]);
recipes.addShapeless(<immersiveengineering:stone_decoration:2> * 3, [<ore:plateBlackSteel>, <tfc:fire_bricks>,<tfc:fire_bricks>, <ore:brickNether>]);
recipes.addShapeless(<minecraft:dirt>, [<ore:sand>, <ore:dustAsh>,<ore:dustAsh>,<ore:dustAsh>]);
recipes.addShapeless(<minecraft:dirt>, [<ore:dirt>]);
recipes.addShapeless(<quark:arrow_explosive>, [<minecraft:arrow>, <thaumcraft:alumentum>,<thaumcraft:alumentum> ]);
recipes.addShapeless(<quark:polished_stone>, [<ore:stonePolished>, <tfcthings:whetstone>.transformDamage(1)]);
recipes.addShapeless(<tfc:raw/limestone>, [<thebetweenlands:limestone>]);



// ================================================================================
//#MARKER ADD SHAPED
recipes.addShaped(<tfc:metal/sheet/wrought_iron>, [[<ore:blockSheetmetalIron>]]);
recipes.addShaped(<tfc:metal/sheet/brass>, [[<ore:sheetmetalBrass>]]);
recipes.addShaped(<thaumcraft:primordial_pearl:7>, [[<extrautils2:decorativesolid:8>]]);
recipes.addShaped(<quark:diamond_heart>, [[<ore:gemDiamond>, <ore:gemDiamond>, <ore:gemDiamond>], [<ore:gemDiamond>, <ore:ingotUnstable>, <ore:gemDiamond>], [<ore:gemDiamond>, <ore:gemDiamond>, <ore:gemDiamond>]]);
recipes.addShaped(<minecraft:dye:4>, [[<ore:gemLapis>]]);
recipes.addShaped(<extrautils2:decorativesolid:2>, [[<ore:stonePolished>]]);
recipes.addShaped(<minecraft:coal_block>, [[<ore:mineralLignite>, <ore:mineralLignite>, <ore:mineralLignite>], [<ore:mineralLignite>, <ore:mineralLignite>, <ore:mineralLignite>], [<ore:mineralLignite>, <ore:mineralLignite>, <ore:mineralLignite>]]);
recipes.addShaped(<minecraft:coal_block>, [[<ore:mineralBituminousCoal>, <ore:mineralBituminousCoal>, <ore:mineralBituminousCoal>], [<ore:mineralBituminousCoal>, <ore:mineralBituminousCoal>, <ore:mineralBituminousCoal>], [<ore:mineralBituminousCoal>, <ore:mineralBituminousCoal>, <ore:mineralBituminousCoal>]]);
recipes.addShaped(<tfc:ceramics/fire_clay>, [[<embers:blend_caminite>, <embers:blend_caminite>, <ore:dustGraphite>], [<ore:dustGraphite>, <ore:dustGraphite>, <ore:dustKaolinite>], [<ore:dustKaolinite>, <ore:dustKaolinite>, null]]);
recipes.addShaped(<thebetweenlands:ancient_remnant_block> * 8, [[<ore:gemPrismarine>, <ore:gemPrismarine>, <ore:gemPrismarine>], [<ore:gemPrismarine>, <tfc:metal/ingot/copper>, <ore:gemPrismarine>], [<ore:gemPrismarine>, <ore:gemPrismarine>, <ore:gemPrismarine>]]);
recipes.addShaped(<minecraft:sea_lantern>, [[<ore:gemPrismarine>, <ore:dustPrismarine>, <ore:gemPrismarine>], [<ore:dustPrismarine>, <ore:dustPrismarine>, <ore:dustPrismarine>], [<ore:gemPrismarine>, <ore:dustPrismarine>, <ore:gemPrismarine>]]);
recipes.addShaped(<minecraft:golden_apple>, [[null, <ore:sheetGold>, null], [<ore:sheetGold>, <tfc:food/red_apple>, <ore:sheetGold>], [null, <ore:sheetGold>, null]]);
recipes.addShaped(<thaumcraft:stone_arcane> * 12, [[null, <ore:stoneBasalt>, null], [<ore:stoneBasalt>, <thaumcraft:crystal_essence>, <ore:stoneBasalt>], [null, <ore:stoneBasalt>, null]]);
recipes.addShaped(<tfctech:wire_draw_bench>, [[<tfctech:wiredraw/winch>, <tfctech:wiredraw/leather_belt>, <ore:tongsWroughtIron>], [null, <thaumcraft:table_stone>, null]]);
recipes.addShaped(<cyberware:surgery_chamber>, [[<ore:chiselHead>, <ore:sawBlade>], [<ore:barsIron>, <ore:barsIron>], [<ore:barsIron>, <ore:barsIron>]]);
recipes.addShaped(<immersiveengineering:metal_device0:6> * 4, [[<ore:plateIron>, <ore:barsIron>, <ore:plateIron>], [<ore:barsIron>, <minecraft:bucket>, <ore:barsIron>], [<ore:plateIron>, <ore:barsIron>, <ore:plateIron>]]);
recipes.addShaped(<embers:golems_eye>, [[<embers:archaic_brick>, <embers:archaic_circuit>, <embers:archaic_brick>]]);
recipes.addShaped(<chisel:factory> * 24, [[null, <ore:stone>, null], [<ore:stone>, <ore:ingotDoubleAnyBronze>, <ore:stone>], [null, <ore:stone>, null]]);
recipes.addShaped(<chisel:factory> * 12, [[null, <ore:stone>, null], [<ore:stone>, <tfc:metal/double_ingot/copper>, <ore:stone>], [null, <ore:stone>, null]]);
recipes.addShaped(<chisel:factory> * 64, [[null, <ore:stone>, null], [<ore:stone>, <tfc:metal/ingot/steel>, <ore:stone>], [null, <ore:stone>, null]]);
recipes.addShaped(<chisel:factory> * 64, [[null, <ore:stone>, null], [<ore:stone>, <ore:ingotDoubleWroughtIron>, <ore:stone>], [null, <ore:stone>, null]]);
recipes.addShaped(<chisel:chisel_iron>, [[<ore:chiselHead>, null], [null, <ore:nuggetCopper>]]);
recipes.addShaped(<tfc:peat>, [[<ore:dustAsh>, <ore:dustAsh>, <ore:dustAsh>], [<ore:dustAsh>, <ore:dustAsh>, <ore:dustAsh>], [<ore:dustAsh>, <ore:dustAsh>, <ore:dustAsh>]]);
recipes.addShaped(<embers:heat_coil>, [[<ore:wireCopper>, <ore:wireCopper>, <ore:wireCopper>], [<embers:brick_caminite>, <embers:mech_core>, <embers:brick_caminite>]]);
recipes.addShaped(<camping:tent:3>, [[null, <tfc:crop/product/burlap_cloth>, null], [<camping:parts:2>, null, <camping:parts:2>]]);
recipes.addShaped(<camping:tent:15>, [[null, <ore:clothHighQuality>, null], [<camping:parts:2>, null, <camping:parts:2>]]);
recipes.addShaped(<camping:knife>, [[<ore:knife>, <ore:dyeRed>], [<ore:saw>, <ore:dyeRed>], [<ore:chisel>, <ore:dyeRed>]]);
recipes.addShaped(<scannable:scanner>, [[<ore:propickHead>, <ore:propickHead>, <ore:propickHead>], [null, <ore:ingotBismuth>, null], [<ore:ingotUnknown>, <ore:ingotUnknown>, <ore:ingotUnknown>]]);
recipes.addShaped(<minecraft:beacon>, [[<ore:blockGlassColorless>, <ore:blockGlassColorless>, <ore:blockGlassColorless>], [<ore:blockGlassColorless>, <ore:gemExquisiteDiamond>, <ore:blockGlassColorless>], [<ore:obsidian>, <thaumcraft:alumentum>, <ore:obsidian>]]);
recipes.addShaped(<travelersbackpack:hose_nozzle>, [[<ore:sheetGold>], [<minecraft:bucket>], [<ore:sheetGold>]]);
recipes.addShaped(<immersiveengineering:jerrycan>, [[<ore:tuyere>, <ore:dyeGreen>], [<ore:plateWroughtIron>, <minecraft:bucket>], [<ore:plateWroughtIron>, <ore:plateWroughtIron>]]);
recipes.addShaped(<thaumcraft:baubles:6>, [[null, <ore:leather>, null], [<ore:leather>, null, <ore:leather>], [<ore:sheetRoseGold>, <ore:gemExquisite>, <ore:sheetRoseGold>]]);
recipes.addShaped(<thaumcraft:baubles:4>, [[<ore:string>, <ore:string>, <ore:string>], [<ore:sheetRoseGold>, <ore:gemExquisite>, <ore:sheetRoseGold>], [null, <ore:sheetRoseGold>, null]]);

recipes.addShaped(<testdummy:dummy>, [[null, <ore:thatch>, null], [<ore:straw>, <tfc:crop/product/burlap_cloth>, <ore:straw>], [null, <minecraft:armor_stand>, null]]);
recipes.addShaped(<immersiveengineering:blueprint>.withTag({blueprint: "vulcanizer_molds"}), [[<ore:dustVulcanizationCompound>, <ore:dustVulcanizationCompound>, <ore:dustVulcanizationCompound>], [<ore:dyeBlue>, <ore:dyeBlue>, <ore:dyeBlue>], [<ore:paper>, <ore:paper>, <ore:paper>]]);
recipes.addShaped(<thaumcraft:ore_cinnabar>, [[<ore:gemCinnabar>, <ore:gemCinnabar>], [<ore:gemCinnabar>, <ore:gemCinnabar>]]);
recipes.addShaped(<tfc:metal/anvil/tungsten_steel>, [[<ore:ingotDoubleTungstenSteel>, <ore:ingotDoubleTungstenSteel>, <ore:ingotDoubleTungstenSteel>], [null, <ore:ingotDoubleTungstenSteel>, null], [<ore:ingotDoubleTungstenSteel>, <ore:ingotDoubleTungstenSteel>, <ore:ingotDoubleTungstenSteel>]]);
recipes.addShaped(<minecraft:brewing_stand>, [[null, <ore:bowl>, null], [<ore:springBrass>, <ore:rodBlaze>, null], [<ore:brick>, <ore:brick>, <ore:brick>]]);
recipes.addShaped(<immersiveengineering:conveyor>.withTag({conveyorType: "immersiveengineering:dropper"}), [[<immersiveengineering:conveyor>.withTag({conveyorType: "immersiveengineering:conveyor"})], [<ore:trapdoormetal>]]);

