//This file was created via CT-GUI! Editing it is not advised!
//Don't touch me!
//#Remove
recipes.removeShaped(<mekanism:basicblock2> * 4, [[null, <ore:ingotSteel>, null],[<ore:ingotSteel>, <ore:ingotCopper>, <ore:ingotSteel>], [null, <ore:ingotSteel>, null]]);
recipes.removeShaped(<ic2:thick_neutron_reflector>, [[<ore:plateCopper>, <ic2:neutron_reflector>, <ore:plateCopper>],[<ic2:neutron_reflector>, <ore:plateCopper>, <ic2:neutron_reflector>], [<ore:plateCopper>, <ic2:neutron_reflector>, <ore:plateCopper>]]);
recipes.removeShaped(<ic2:neutron_reflector>, [[<ore:dustTin>, <ore:dustCoal>, <ore:dustTin>],[<ore:dustCoal>, <ore:plateCopper>, <ore:dustCoal>], [<ore:dustTin>, <ore:dustCoal>, <ore:dustTin>]]);
//Don't touch me!
//#Add
recipes.addShaped(<mekanism:machineblock2:9>, [[<ore:scaffoldingAluminum>, <cyberware:leg_upgrades>.withTag({cyberwareQuality: "cyberware.quality.scavenged"}).onlyWithTag({cyberwareQuality: "cyberware.quality.scavenged"}), <ore:scaffoldingAluminum>],[<ore:scaffoldingAluminum>, <tfc:metal/hammer_head/wrought_iron>, <ore:scaffoldingAluminum>], [<ore:scaffoldingAluminum>, null, <ore:scaffoldingAluminum>]]);
recipes.addShaped(<mekanism:seismicreader>, [[null, null, null],[<tfc:metal/nugget/wrought_iron>, <cyberware:cybereye_upgrades:3>.withTag({cyberwareQuality: "cyberware.quality.scavenged"}).onlyWithTag({cyberwareQuality: "cyberware.quality.scavenged"}), <tfc:metal/nugget/wrought_iron>], [<tfc:metal/nugget/wrought_iron>, <tfc:metal/nugget/wrought_iron>, <tfc:metal/nugget/wrought_iron>]]);
recipes.addShaped(<mekanism:energycube>.withTag({tier: 3}), [[<tfc:metal/ingot/osmium>, <ic2:te:80>, <tfc:metal/ingot/osmium>],[<ic2:charging_lapotron_crystal:*>, <mekanism:basicblock:8>, <ic2:charging_lapotron_crystal:*>], [<tfc:metal/ingot/osmium>, <libvulpes:coil0:10>, <tfc:metal/ingot/osmium>]]);
recipes.addShaped(<mekanism:energycube>.withTag({tier: 2}), [[<tfc:metal/ingot/osmium>, <ic2:te:79>, <tfc:metal/ingot/osmium>],[<ic2:charging_energy_crystal:*>, <thermalexpansion:frame>, <ic2:charging_energy_crystal:*>], [<tfc:metal/ingot/osmium>, <immersiveengineering:metal_decoration0:2>, <tfc:metal/ingot/osmium>]]);
recipes.addShaped(<mekanism:energycube>.withTag({tier: 1, mekData: {energyStored: 0.0}}), [[<tfc:metal/ingot/osmium>, <ic2:te:78>, <tfc:metal/ingot/osmium>],[<ic2:advanced_charging_re_battery:*>, <ic2:resource:13>, <ic2:advanced_charging_re_battery:*>], [<tfc:metal/ingot/osmium>, <immersiveengineering:metal_decoration0:1>, <tfc:metal/ingot/osmium>]]);
recipes.addShaped(<mekanism:energycube>.withTag({tier: 0, mekData: {energyStored: 0.0}}), [[<tfc:metal/ingot/osmium>, <ic2:te:77>, <tfc:metal/ingot/osmium>],[<ic2:charging_re_battery:*>, <ic2:resource:12>, <ic2:charging_re_battery:*>], [<tfc:metal/ingot/osmium>, <immersiveengineering:metal_decoration0>, <tfc:metal/ingot/osmium>]]);
recipes.addShaped(<ic2:quad_mox_fuel_rod>.withTag({advDmg: 0}), [[null, <tfc:metal/sheet/zircaloy>, null],[<ic2:dual_mox_fuel_rod>.withTag({advDmg: 0}).onlyWithTag({advDmg: 0}), <tfc:metal/sheet/zircaloy>, <ic2:dual_mox_fuel_rod>.withTag({advDmg: 0}).onlyWithTag({advDmg: 0})], [null, <tfc:metal/sheet/zircaloy>, null]]);
recipes.addShaped(<ic2:quad_mox_fuel_rod>.withTag({advDmg: 0}), [[<ic2:mox_fuel_rod>.withTag({advDmg: 0}).onlyWithTag({advDmg: 0}), <tfc:metal/sheet/zircaloy>, <ic2:mox_fuel_rod>.withTag({advDmg: 0}).onlyWithTag({advDmg: 0})],[<tfc:metal/sheet/zircaloy>, <tfc:metal/sheet/zircaloy>, <tfc:metal/sheet/zircaloy>], [<ic2:mox_fuel_rod>.withTag({advDmg: 0}).onlyWithTag({advDmg: 0}), <tfc:metal/sheet/zircaloy>, <ic2:mox_fuel_rod>.withTag({advDmg: 0}).onlyWithTag({advDmg: 0})]]);
recipes.addShaped(<ic2:quad_uranium_fuel_rod>.withTag({advDmg: 0}), [[<ic2:uranium_fuel_rod>.withTag({advDmg: 0}).onlyWithTag({advDmg: 0}), <tfc:metal/sheet/zircaloy>, <ic2:uranium_fuel_rod>.withTag({advDmg: 0}).onlyWithTag({advDmg: 0})],[<tfc:metal/sheet/zircaloy>, <tfc:metal/sheet/zircaloy>, <tfc:metal/sheet/zircaloy>], [<ic2:uranium_fuel_rod>.withTag({advDmg: 0}).onlyWithTag({advDmg: 0}), <tfc:metal/sheet/zircaloy>, <ic2:uranium_fuel_rod>.withTag({advDmg: 0}).onlyWithTag({advDmg: 0})]]);
recipes.addShaped(<ic2:quad_uranium_fuel_rod>.withTag({advDmg: 0}), [[null, <tfc:metal/sheet/zircaloy>, null],[<ic2:dual_uranium_fuel_rod>.withTag({advDmg: 0}).onlyWithTag({advDmg: 0}), <tfc:metal/sheet/zircaloy>, <ic2:dual_uranium_fuel_rod>.withTag({advDmg: 0}).onlyWithTag({advDmg: 0})], [null, <tfc:metal/sheet/zircaloy>, null]]);
recipes.addShaped(<ic2:dual_mox_fuel_rod>.withTag({advDmg: 0}), [[<ic2:mox_fuel_rod>.withTag({advDmg: 0}).onlyWithTag({advDmg: 0}), <tfc:metal/sheet/zircaloy>, <ic2:mox_fuel_rod>.withTag({advDmg: 0}).onlyWithTag({advDmg: 0})]]);
recipes.addShaped(<ic2:dual_uranium_fuel_rod>.withTag({advDmg: 0}), [[<ic2:uranium_fuel_rod>.withTag({advDmg: 0}).onlyWithTag({advDmg: 0}), <tfc:metal/sheet/zircaloy>, <ic2:uranium_fuel_rod>.withTag({advDmg: 0}).onlyWithTag({advDmg: 0})]]);
recipes.addShaped(<cyberware:scanner>, [[<tfc:metal/rod/wrought_iron>, <cyberware:cybereyes>.withTag({cyberwareQuality: "cyberware.quality.scavenged"}).onlyWithTag({cyberwareQuality: "cyberware.quality.scavenged"}), <tfc:metal/rod/wrought_iron>],[<tfc:metal/rod/wrought_iron>, <tfc:gem/diamond:3>, <tfc:metal/rod/wrought_iron>], [<tfc:metal/sheet/wrought_iron>, <tfc:metal/sheet/wrought_iron>, <tfc:metal/sheet/wrought_iron>]]);
recipes.addShaped(<cyberware:scanner>, [[<tfc:metal/rod/wrought_iron>, <cyberware:cybereyes>, <tfc:metal/rod/wrought_iron>],[<tfc:metal/rod/wrought_iron>, <tfc:gem/diamond:3>, <tfc:metal/rod/wrought_iron>], [<tfc:metal/sheet/wrought_iron>, <tfc:metal/sheet/wrought_iron>, <tfc:metal/sheet/wrought_iron>]]);
furnace.addRecipe(<minecraft:deadbush>, <ore:treeSapling>, 0.0);
recipes.addShaped(<mystgears:ember_gatling_gun>, [[<thaumcraft:vis_resonator>, <embers:aspectus_dawnstone>, <embers:aspectus_dawnstone>],[<thaumcraft:focus_1>.withTag({package: {complexity: 15, nodes: [{type: "MEDIUM", key: "ROOT"}, {type: "MEDIUM", key: "thaumcraft.BOLT"}, {"setting.duration": 0, "setting.power": 5, type: "EFFECT", key: "thaumcraft.FIRE"}], index: 0, power: 1.0 as float}, color: -42495, display: {Name: "Blank Lesser Focus"}}).onlyWithTag({package: {complexity: 15, nodes: [{type: "MEDIUM", key: "ROOT"}, {type: "MEDIUM", key: "thaumcraft.BOLT"}, {"setting.duration": 0, "setting.power": 5, type: "EFFECT", key: "thaumcraft.FIRE"}], index: 0, power: 1.0 as float}, color: -42495, display: {Name: "Blank Lesser Focus"}}), <embers:aspectus_dawnstone>, <embers:aspectus_dawnstone>], [<ore:plateIron>, <embers:aspectus_dawnstone>, <embers:aspectus_dawnstone>]]);
recipes.addShaped(<tfcthings:grindstone_diamond>.withTag({Unbreakable: 1, display: {Name: "Cosmic Gear"}}), [[<botania:manaresource:4>, <tfcthings:grindstone_diamond>, <botania:manaresource:4>]]);
recipes.addShaped(<tfcthings:grindstone_diamond>.withTag({Unbreakable: 1, display: {Name: "Cosmic Gear"}}), [[<thaumcraft:ingot:1>, <tfcthings:grindstone_diamond>, <thaumcraft:ingot:1>]]);
recipes.addShapeless(<ic2:cable:4>.withTag({type: 4 as byte, insulation: 0 as byte}) * 3, [<ore:wireTin>,<ore:wireTin>]);
recipes.addShapeless(<ic2:cable:2>.withTag({type: 2 as byte, insulation: 0 as byte}) * 3, [<ore:wireGold>,<ore:wireGold>]);
recipes.addShapeless(<ic2:cable>.withTag({type: 0 as byte, insulation: 0 as byte}) * 3, [<ore:wireCopper>,<ore:wireCopper>]);

//File End
