#  Main header!
#  Line 2

[songs]
	[songs.chriszabriskie_whatdoesanybodyknowaboutanything]
		triggers = [ "mob-taint" ]
		volume = "1.0"
	[songs.kevinmcleod_bluesizzle]
		play_once = 1
		triggers = [ "dimension-space" ]
		volume = "1.0"
	[songs.kevinmcleod_giantwyrm]
		triggers = [ "mob-taint" ]
		volume = "1.0"
	[songs.kevinmcleod_itislost]
		triggers = [ "dimension-overworld" ]
		volume = "1.0"
	[songs.kevinmcleod_martiancowboy]
		triggers = [ "mob-taint" ]
		volume = "1.0"
	[songs.kevinmcleod_thedread]
		triggers = [ "dimension-space" ]
		volume = "1.0"

[triggers]
	[[triggers.dimension]]
		identifier = "space"
		priority = "2"
		resource_matcher = "exact"
		resource_name = [ "-3" ]
	[[triggers.dimension]]
		identifier = "overworld"
		priority = "2"
		resource_matcher = "exact"
		resource_name = [ "0" ]
	[triggers.mob]
		detection_range = "40"
		fade_in = "100"
		fade_out = "100"
		identifier = "taint"
		mob_targeting = false
		priority = "10"
		resource_name = "taintacle"
	[triggers.universal]
		active_cooldown = "0"
		fade_in = "0"
		fade_out = "0"
		persistence = "0"
		ticks_before_active = "0"
		ticks_before_audio = "0"
		ticks_between_audio = "0"

