// File generated by MineTweakerRecipeMaker
//                     READ THIS HEADER BEFORE EDITING ANYTHING
// ================================================================================
//     This file is read and changed by the mod.
//     If you remove/edit any of the markers, IT WILL STOP WORKING!
//     If you want to make manual edits, make a backup of this file!
//     Markers look like this: "//#MARKER something"
//     They indicate where calls should be placed, so that MineTweaker does them in the correct order.
//     Removes come first, then stuff is added.
// ================================================================================
//

// ================================================================================
//#MARKER REMOVE

// ================================================================================
//#MARKER REMOVE SHAPELESS

// ================================================================================
//#MARKER REMOVE SHAPED

// ================================================================================
//#MARKER ADD

// ================================================================================
//#MARKER ADD SHAPELESS
recipes.addShapeless(<thermaldynamics:duct_16:7>, [<thermaldynamics:duct_16:6>]);
recipes.addShapeless(<thermaldynamics:duct_16:6>, [<thermaldynamics:duct_16:7>, <railcraft:glass:*>]);
recipes.addShapeless(<thermaldynamics:duct_16:6>, [<immersiveengineering:metal_device1:6>, <ore:plateBlackSteel>, <ore:plateBlackSteel>, <railcraft:glass:*>, <railcraft:glass:*>]);
recipes.addShapeless(<thermaldynamics:duct_16:7>, [<immersiveengineering:metal_device1:6>, <ore:plateBlackSteel>, <ore:plateBlackSteel>, <railcraft:glass:*>]);
recipes.addShapeless(<minecraft:fermented_spider_eye>, [<betternether:eye_seed>, <betternether:gray_mold>]);
recipes.addShapeless(<thebetweenlands:fumigant>, [<ore:categoryGrain>, <ore:dustFlux>, <ore:dustFlux>, <thebetweenlands:sap_ball>]);
recipes.addShapeless(<thebetweenlands:glowing_goop> * 2, [<thebetweenlands:sludge_ball>, <thebetweenlands:wisp>]);
recipes.addShapeless(<ic2:reactor_heat_vent>, [<ic2:heat_vent>, <ic2:crafting:7>]);

// ================================================================================
//#MARKER ADD SHAPED
recipes.addShaped(<thermaldynamics:duct_16:1> * 8, [[<thermaldynamics:duct_16>, <thermaldynamics:duct_16>, <thermaldynamics:duct_16>], [<thermaldynamics:duct_16>, <ore:ingetAnyBronze>, <thermaldynamics:duct_16>], [<thermaldynamics:duct_16>, <thermaldynamics:duct_16>, <thermaldynamics:duct_16>]]);
recipes.addShaped(<thermaldynamics:duct_16> * 8, [[<thermaldynamics:duct_16:1>, <thermaldynamics:duct_16:1>, <thermaldynamics:duct_16:1>], [<thermaldynamics:duct_16:1>, <ore:blockGlassColorless>, <thermaldynamics:duct_16:1>], [<thermaldynamics:duct_16:1>, <thermaldynamics:duct_16:1>, <thermaldynamics:duct_16:1>]]);
recipes.addShaped(<thermaldynamics:duct_16:1> * 24, [[<ore:nuggetCopper>, <ore:nuggetCopper>, <ore:nuggetCopper>], [<ore:sheetAnyBronze>, null, <ore:sheetAnyBronze>], [<ore:nuggetCopper>, <ore:nuggetCopper>, <ore:nuggetCopper>]]);
recipes.addShaped(<clothesline:clothesline_anchor> * 16, [[<immersiveengineering:material:8>], [<ore:stickIron>]]);
recipes.addShaped(<immersiveengineering:metal_device1:6> * 24, [[<ore:plateSteel>, <ore:plateSteel>, <ore:plateSteel>],[null,null,null], [<ore:plateSteel>, <ore:plateSteel>, <ore:plateSteel>]]);
recipes.addShaped(<tconstruct:faucet>, [[<ore:brick>, <ore:dustCharcoal>, <ore:brick>], [null, <ore:mortar>, null]]);
recipes.addShaped(<tconstruct:channel> * 3, [[<ore:brick>, <ore:dustCharcoal>, <ore:brick>], [<ore:mortar>, <ore:brick>, <ore:mortar>]]);
recipes.addShaped(<tconstruct:wooden_hopper>, [[<ore:lumberOak>, null, <ore:lumberOak>], [<ore:lumberOak>, <ore:gearWood>, <ore:lumberOak>], [null, <ore:lumberOak>, null]]);
recipes.addShaped(<ic2:te:22>, [[<ore:blockLead>, <embers:wildfire_core>, <ore:blockLead>], [<ic2:te:24>, <ic2:te:24>, <ic2:te:24>], [<ore:blockLead>, <ic2:crafting:8>, <ore:blockLead>]]);
recipes.addShaped(<ic2:nuclear:4>, [[<ore:blockUranium>, <ore:blockUranium>, <ore:blockUranium>], [<ore:blockUranium>, <ic2:nuclear:3>, <ore:blockUranium>], [<ore:blockUranium>, <ore:blockUranium>, <ore:blockUranium>]]);
recipes.addShaped(<ic2:te:24>, [[<ore:stickFerroboron>, <ore:stickFerroboron>, <ore:stickFerroboron>], [<ore:plateLead>, <immersiveintelligence:metal_device>, <ore:plateLead>], [<ore:plateLead>, <ore:plateLead>, <ore:plateLead>]]);
recipes.addShaped(<thermaldynamics:duct_16:2> * 3, [[<ore:nuggetInvar>, <ore:nuggetInvar>, <ore:nuggetInvar>], [<railcraft:glass>, null, <railcraft:glass>], [<ore:nuggetInvar>, <ore:nuggetInvar>, <ore:nuggetInvar>]]);
recipes.addShaped(<thermaldynamics:duct_16:3> * 3, [[<ore:nuggetInvar>, <ore:nuggetInvar>, <ore:nuggetInvar>], [<tfc:ceramics/fired/fire_brick>, null, <tfc:ceramics/fired/fire_brick>], [<ore:nuggetInvar>, <ore:nuggetInvar>, <ore:nuggetInvar>]]);
recipes.addShaped(<embers:steam_engine> * 4, [[<ic2:crafting:8>, <embers:blasting_core>, <embers:blasting_core>], [<embers:brick_caminite>, <embers:brick_caminite>, <embers:brick_caminite>]]);
recipes.addShaped(<ic2:overclocked_heat_vent> * 2, [[<ore:stickElectrum>, <cyberware:component:2>, <ore:stickElectrum>], [<ore:stickElectrum>, <ore:fanSteel>, <ore:stickElectrum>], [<ore:stickElectrum>, <cyberware:component:2>, <ore:stickElectrum>]]);
recipes.addShaped(<ic2:advanced_heat_exchanger>, [[null, <ic2:heat_exchanger>, null], [<ore:dustDiamond>, <ore:circuitBasic>, <ore:dustDiamond>], [null, <ic2:heat_exchanger>, null]]);
recipes.addShaped(<ic2:component_heat_exchanger> * 2, [[null, <tfc:ceramics/fired/fire_brick>, null], [<ic2:heat_exchanger>, <ore:plateElectrum>, <ic2:heat_exchanger>], [null, <tfc:ceramics/fired/fire_brick>, null]]);
recipes.addShaped(<ic2:reactor_heat_exchanger> * 2, [[<ic2:heat_exchanger>, <ic2:crafting:7>, <ic2:heat_exchanger>]]);
recipes.addShaped(<ic2:heat_exchanger> * 4, [[null, <ore:plateIron>, null], [<ore:plateIron>, <ic2:crafting:7>, <ore:plateIron>], [null, <ore:plateIron>, null]]);
recipes.addShaped(<ic2:component_heat_vent>, [[null, <ore:plasticLightGray>, null], [<ore:plasticLightGray>, <ic2:heat_vent>, <ore:plasticLightGray>], [null, <ore:plasticLightGray>, null]]);
recipes.addShaped(<ic2:advanced_heat_vent>, [[null, <ore:quicksilver>, null], [<ic2:heat_vent>, <ore:dustDiamond>, <ic2:heat_vent>], [null, <ore:quicksilver>, null]]);
recipes.addShaped(<ic2:heat_vent> * 2, [[<ore:barsIron>, <ore:barsIron>, <ore:barsIron>], [<ore:barsIron>, <mysticalmechanics:gear_fan>, <ore:barsIron>], [<ore:barsIron>, <ore:barsIron>, <ore:barsIron>]]);

