// File generated by MineTweakerRecipeMaker
//                     READ THIS HEADER BEFORE EDITING ANYTHING
// ================================================================================
//     This file is read and changed by the mod.
//     If you remove/edit any of the markers, IT WILL STOP WORKING!
//     If you want to make manual edits, make a backup of this file!
//     Markers look like this: "//#MARKER something"
//     They indicate where calls should be placed, so that MineTweaker does them in the correct order.
//     Removes come first, then stuff is added.
// ================================================================================
//

// ================================================================================
//#MARKER REMOVE
recipes.remove(<minecraft:rail>);
recipes.removeByMod("signals");
recipes.remove(<botania:fertilizer>);
recipes.remove(<botania:pylon>);
recipes.remove(<botania:spreader>);

// ================================================================================
//#MARKER REMOVE SHAPELESS
recipes.removeShapeless(<minecraft:wheat> * 9, [<minecraft:hay_block>]);
recipes.remove(<immersiveengineering:metal_decoration0:4>);
recipes.removeShapeless(<minecraft:stone_pressure_plate>, [<ore:concrete>, <ore:concrete>]);

// ================================================================================
//#MARKER REMOVE SHAPED
recipes.removeShaped(<minecraft:stone_pressure_plate>, [[<ore:concrete>, <ore:concrete>]]);
recipes.removeShaped(<thaumcraft:table_stone>, [[<minecraft:stone_slab>, <minecraft:stone_slab>, <minecraft:stone_slab>], [<ore:stone>, null, <ore:stone>]]);
recipes.removeShaped(<integrateddynamics:squeezer>, [[<ore:stickWood>, <ore:blockIron>, <ore:stickWood>], [<ore:stickWood>, null, <ore:stickWood>], [<ore:plankWood>, <ore:ingotIron>, <ore:plankWood>]]);

// ================================================================================
//#MARKER ADD

// ================================================================================
//#MARKER ADD SHAPELESS
recipes.addShapeless(<minecraft:book>, [<ore:paper>, <ore:paper>, <ore:paper>, <ore:lumber>, <ore:lumber>, <ore:string>]);
recipes.addShapeless(<tconevo:material>, [<ore:ingotBlueSteel>, <ore:ingotThaumium>, <ore:ingotThaumium>, <ore:ingotThaumium>, <appliedenergistics2:material:47>]);
recipes.addShapeless(<embers:shard_ember> * 6, [<embers:crystal_ember>]);
recipes.addShapeless(<minecraft:arrow> * 2, [<ore:stickWood>, <botania:petal:*>, <botania:petal:*>]);
recipes.addShapeless(<railcraft:track_kit:1>.withTag({railcraft: {kit: "railcraft_activator"}}) * 16, [<ore:plateIron>, <ore:dustRedstone>, <ore:dustRedstone>, <tfc:brass_mechanisms>]);
recipes.addShapeless(<signals:rail_network_controller>, [<minecraft:map>, <signals:block_signal>]);
recipes.addShapeless(<minecraft:fire_charge> * 3, [<thaumcraft:alumentum>, <thaumcraft:alumentum>, <minecraft:gunpowder>, <ore:powderBlaze>, <ore:powderBlaze>, <ore:powderBlaze>, <ore:powderBlaze>, <ore:powderBlaze>, <ore:powderBlaze>]);
recipes.addShapeless(<minecraft:fire_charge>, [<thaumcraft:alumentum>, <thaumcraft:alumentum>]);
recipes.addShapeless(<botania:fertilizer> * 2, [<botania:petal:*>, <botania:petal:*>, <minecraft:dye:15>]);

recipes.addShapeless(<embers:ember_cartridge>, [<embers:ember_jar>, <embers:ember_jar>, <embers:ember_jar>, <embers:ember_jar>]);
recipes.addShapeless(<embers:ember_jar>, [<embers:ember_bulb>, <embers:ember_bulb>, <embers:ember_bulb>, <embers:ember_bulb>]);
recipes.addShapeless(<clothesline:clothesline>, [<tfc:crop/product/jute_fiber>, <tfc:crop/product/jute_fiber>]);
recipes.addShapeless(<thermaldynamics:duct_16:7>, [<thermaldynamics:duct_16:6>]);
recipes.addShapeless(<thermaldynamics:duct_16:6>, [<thermaldynamics:duct_16:7>, <railcraft:glass:*>]);
recipes.addShapeless(<thermaldynamics:duct_16:6>, [<immersiveengineering:metal_device1:6>, <ore:plateBlackSteel>, <ore:plateBlackSteel>, <railcraft:glass:*>, <railcraft:glass:*>]);
recipes.addShapeless(<thermaldynamics:duct_16:7>, [<immersiveengineering:metal_device1:6>, <ore:plateBlackSteel>, <ore:plateBlackSteel>, <railcraft:glass:*>]);
recipes.addShapeless(<minecraft:fermented_spider_eye>, [<betternether:eye_seed>, <betternether:gray_mold>]);
recipes.addShapeless(<thebetweenlands:fumigant>, [<ore:categoryGrain>, <ore:dustFlux>, <ore:dustFlux>, <thebetweenlands:sap_ball>]);
recipes.addShapeless(<thebetweenlands:glowing_goop> * 2, [<thebetweenlands:sludge_ball>, <thebetweenlands:wisp>]);
recipes.addShapeless(<ic2:reactor_heat_vent>, [<ic2:heat_vent>, <ic2:crafting:7>]);

// ================================================================================
//#MARKER ADD SHAPED
recipes.addShaped(<botania:pylon>, [[<ore:powderMana>, <ore:powderMana>, <ore:powderMana>], [<ore:powderMana>, <ore:ingotGold>, <ore:powderMana>], [<ore:powderMana>, <ore:powderMana>, <ore:powderMana>]]);
recipes.addShaped(<minecraft:redstone_torch> * 3, [[<ore:dustRedstone>], [<ore:livingwoodTwig>]]);
recipes.addShaped(<immersiveengineering:wooden_device0:1>, [[<ore:livingwood>, null, <ore:livingwood>], [<ore:livingwood>, null, <ore:livingwood>], [<ore:livingwood>, <ore:livingwood>, <ore:livingwood>]]);
recipes.addShaped(<immersiveintelligence:mechanical_device1>, [[null, <tfc:bellows>, null], [<ore:plateBrass>, <ore:plateBrass>, <ore:plateBrass>]]);
recipes.addShaped(<firmalife:large_planter>, [[<ore:ingotBrick>, <ore:dirt>, <ore:ingotBrick>], [<ore:ingotBrick>, <ore:dirt>, <ore:ingotBrick>], [<ore:ingotBrick>, <ore:ingotBrick>, <ore:ingotBrick>]]);
recipes.addShaped(<firmalife:quad_planter>, [[<ore:ingotBrick>, <ore:dirt>, <ore:ingotBrick>], [<ore:ingotBrick>, <ore:ingotBrick>, <ore:ingotBrick>]]);
recipes.addShaped(<chisel:factory> * 32, [[<ore:concrete>, <ore:concrete>, <ore:concrete>], [null, <ore:ingetAnyBronze>, null], [<ore:concrete>, <ore:concrete>, <ore:concrete>]]);
recipes.addShaped(<chisel:factory> * 32, [[<ore:concrete>, <ore:concrete>, <ore:concrete>], [null, <ore:ingotIron>, null], [<ore:concrete>, <ore:concrete>, <ore:concrete>]]);
recipes.addShaped(<firmalife:climate_station_4>, [[<ore:blockGlass>, <ore:blockGlass>, <ore:blockGlass>], [<ore:blockGlass>, <ore:ingotIron>, <ore:blockGlass>], [<tfc:brass_mechanisms>, <tfc:brass_mechanisms>, <tfc:brass_mechanisms>]]);
recipes.addShaped(<railcraft:locomotive_steam_solid>, [[<ore:plateIron>, <ore:plateIron>, <ore:plateIron>], [<tfc:brass_mechanisms>, <minecraft:minecart>, <tfc:brass_mechanisms>]]);
recipes.addShaped(<botania:spreader>, [[<botania:livingwood:1>, <botania:livingwood:1>, <botania:livingwood:1>], [null, <botania:petalblock:4>, <botania:livingwood:1>], [<botania:livingwood:1>, <botania:livingwood:1>, <botania:livingwood:1>]]);
recipes.addShaped(<botania:spreader>, [[<botania:livingwood:1>, <botania:livingwood:1>, <botania:livingwood:1>], [<botania:livingwood:1>, <botania:petalblock:4>, null], [<botania:livingwood:1>, <botania:livingwood:1>, <botania:livingwood:1>]]);
recipes.addShaped(<metalchests:metal_chest:3> * 2, [[<ore:plateGold>, <ore:plateGold>, <ore:plateGold>], [<ore:plateGold>, null, <ore:plateGold>], [<ore:plateGold>, <ore:plateGold>, <ore:plateGold>]]);
recipes.addShaped(<metalchests:metal_chest:2> * 2, [[<ore:plateSilver>, <ore:plateSilver>, <ore:plateSilver>], [<ore:plateSilver>, null, <ore:plateSilver>], [<ore:plateSilver>, <ore:plateSilver>, <ore:plateSilver>]]);
recipes.addShaped(<metalchests:metal_chest:4> * 2, [[<ore:platePlatinum>, <ore:platePlatinum>, <ore:platePlatinum>], [<ore:platePlatinum>, null, <ore:platePlatinum>], [<ore:platePlatinum>, <ore:platePlatinum>, <ore:platePlatinum>]]);
recipes.addShaped(<metalchests:metal_chest:1> * 2, [[<ore:plateIron>, <ore:plateIron>, <ore:plateIron>], [<ore:plateIron>, null, <ore:plateIron>], [<ore:plateIron>, <ore:plateIron>, <ore:plateIron>]]);
recipes.addShaped(<metalchests:metal_chest> * 2, [[<ore:plateCopper>, <ore:plateCopper>, <ore:plateCopper>], [<ore:plateCopper>, null, <ore:plateCopper>], [<ore:plateCopper>, <ore:plateCopper>, <ore:plateCopper>]]);
recipes.addShaped(<botania:corporeaspark>, [[null, <botania:managlass>, null], [<botania:managlass>, <thaumcraft:salis_mundus>, <botania:managlass>], [null, <botania:managlass>, null]]);
recipes.addShaped(<thermalfoundation:material:23>, [[null, <ore:stone>, null], [<ore:stone>, <ore:stone>, <ore:stone>], [null, <ore:stone>, null]]);
recipes.addShaped(<quark:charred_nether_bricks> * 8, [[<minecraft:nether_brick>, <minecraft:nether_brick>, <minecraft:nether_brick>], [<minecraft:nether_brick>, <thaumcraft:alumentum>, <minecraft:nether_brick>], [<minecraft:nether_brick>, <minecraft:nether_brick>, <minecraft:nether_brick>]]);
recipes.addShaped(<railcraft:locomotive_electric>, [[null, <ore:circuitBasic>, null], [<railcraft:charge:5>, <ic2:resource:12>, <railcraft:charge:5>]]);
recipes.addShaped(<railcraft:charge:5>, [[null, <ore:wireCopper>, null], [<cyberware:component>, <thaumcraft:mechanism_simple>, <cyberware:component>], [null, <ore:wireCopper>, null]]);
recipes.addShaped(<railcraft:charge:5>, [[null, <cyberware:component>, null], [<ore:wireCopper>, <thaumcraft:mechanism_simple>, <ore:wireCopper>], [null, <cyberware:component>, null]]);
recipes.addShaped(<immersiveengineering:metal_decoration0:3>, [[null, <ore:ingotRedAlloy>, null], [<ore:circuitBasic>, <ore:machineBlock>, <ore:circuitBasic>], [null, <ore:ingotRedAlloy>, null]]);
recipes.addShaped(<immersiveengineering:metal_decoration0:3>, [[null, <ore:circuitBasic>, null], [<ore:ingotRedAlloy>, <ore:machineBlock>, <ore:ingotRedAlloy>], [null, <ore:circuitBasic>, null]]);
recipes.addShaped(<ic2:resource:12>, [[<cyberware:component:4>, <thaumcraft:mind:1>, <cyberware:component:4>], [<cyberware:component:5>, <ore:blockSteel>, <cyberware:component:5>], [<cyberware:component:4>, <thaumcraft:vis_resonator>, <cyberware:component:4>]]);
recipes.addShaped(<ic2:resource:12> * 2, [[<cyberware:component:4>, <tetra:forged_bolt>, <cyberware:component:4>], [<cyberware:component:5>, <ore:blockSteel>, <cyberware:component:5>], [<cyberware:component:4>, <thaumcraft:vis_resonator>, <cyberware:component:4>]]);
recipes.addShaped(<ic2:te:87>, [[<ore:plateIron>, <ic2:crafting:7>, <ore:plateIron>], [<embers:blasting_core>, null, <embers:blasting_core>], [<ore:plateIron>, <ore:plateIron>, <ore:plateIron>]]);
recipes.addShaped(<ic2:crafting:7>, [[<ore:concrete>, <ore:sheetDoubleCopper>, <ore:concrete>], [<ore:concrete>, <ore:sheetDoubleCopper>, <ore:concrete>], [<ore:concrete>, <ore:sheetDoubleCopper>, <ore:concrete>]]);
recipes.addShaped(<ic2:neutron_reflector>, [[<ore:nuggetBeryllium>, <ore:nuggetBeryllium>, <ore:nuggetBeryllium>], [<ore:nuggetBeryllium>, <ore:plateSteel>, <ore:nuggetBeryllium>], [<ore:nuggetBeryllium>, <ore:nuggetBeryllium>, <ore:nuggetBeryllium>]]);
recipes.addShaped(<chisel:factory> * 64, [[<ore:concrete>, <ore:concrete>, <ore:concrete>], [null, <ore:ingotSteel>, null], [<ore:concrete>, <ore:concrete>, <ore:concrete>]]);
recipes.addShaped(<minecraft:piston> * 4, [[<ore:plateIron>, <ore:plateIron>, <ore:plateIron>], [<ore:concrete>, <ore:stickIron>, <ore:concrete>], [<ore:concrete>, <tfc:brass_mechanisms>, <ore:concrete>]]);
recipes.addShaped(<buildinggadgets:templatemanager>, [[<ore:plateIron>, <ore:plateIron>, <ore:plateIron>], [<thaumcraft:mind:1>, null, <thaumcraft:mind:1>], [<ore:plateIron>, <ore:plateIron>, <ore:plateIron>]]);
recipes.addShaped(<buildinggadgets:destructiontool>, [[<ore:plateIron>, <embers:blasting_core>], [<ore:plateIron>, <embers:blasting_core>], [<ore:plateIron>, <thaumcraft:mind>]]);
recipes.addShaped(<buildinggadgets:exchangertool>, [[<ore:quicksilver>, <ore:quicksilver>, <ore:quicksilver>], [<embers:blasting_core>, <thaumcraft:mind>, <embers:blasting_core>], [<ore:plateIron>, <thaumcraft:mind>, <ore:plateIron>]]);
recipes.addShaped(<buildinggadgets:copypastetool>, [[<ore:plateIron>, <ore:quicksilver>], [<ore:plateIron>, <thaumcraft:mind>], [<ore:plateIron>, <ore:plateIron>]]);
recipes.addShaped(<buildinggadgets:buildingtool>, [[<ore:plateIron>, <tfc:brass_mechanisms>], [<ore:plateIron>, <tfc:brass_mechanisms>], [<ore:plateIron>, <ore:plateIron>]]);
recipes.addShaped(<buildinggadgets:buildingtool>, [[<ore:livingrock>, <ore:powderMana>, <ore:livingrock>], [<ore:livingrock>, <botania:sextant>, <ore:livingrock>], [<ore:livingrock>, <ore:powderMana>, <ore:livingrock>]]);
recipes.addShaped(<embers:auto_hammer>, [[<ore:concrete>, null, <ore:blockSteel>], [<embers:blasting_core>, <ore:ingotSteel>, null], [<ore:concrete>, null, null]]);
recipes.addShaped(<embers:auto_hammer>, [[<ore:concrete>, <ore:ingotCopper>, <tetra:hammer_head>], [<tetra:hammer_base>, <tetra:forged_beam>, null], [<ore:concrete>, <ore:ingotCopper>, null]]);
recipes.addShaped(<embers:dawnstone_anvil>, [[null, <tfc:metal/anvil/black_steel>, null], [<ore:concrete>, <ore:concrete>, <ore:concrete>]]);
recipes.addShaped(<embers:dawnstone_anvil>, [[null, <tetra:workbench:1>, null], [<ore:concrete>, <ore:concrete>, <ore:concrete>]]);
recipes.addShaped(<minecraft:repeater>, [[<minecraft:redstone_torch>, <ore:dustRedstone>, <minecraft:redstone_torch>], [<ore:brick>, <ore:brick>, <ore:brick>]]);
recipes.addShaped(<minecraft:comparator>, [[null, <minecraft:redstone_torch>, null], [<minecraft:redstone_torch>, <ore:dustRedstone>, <minecraft:redstone_torch>], [<ore:brick>, <ore:brick>, <ore:brick>]]);
recipes.addShaped(<botania:runealtar>, [[<ore:livingrock>, <ore:livingrock>, <ore:livingrock>], [<ore:powderMana>, <ore:powderMana>, <ore:powderMana>], [null, <ore:livingrock>, null]]);
recipes.addShaped(<modularmachinery:calcifier_t0_controller>, [[<ore:livingrock>, <ore:livingrock>, <ore:livingrock>], [<ore:gearWood>, <ore:powderMana>, <ore:gearWood>], [<ore:livingrock>, <ore:livingrock>, <ore:livingrock>]]);
recipes.addShaped(<modularmachinery:blockoutputbus>, [[<ore:livingrock>, <botania:livingrock>, <ore:livingrock>], [<ore:livingrock>, <ore:gearWood>, <ore:livingrock>], [<ore:livingrock>, <tconstruct:wooden_hopper>, <ore:livingrock>]]);
recipes.addShaped(<modularmachinery:blockinputbus>, [[<ore:livingrock>, <tconstruct:wooden_hopper>, <ore:livingrock>], [<ore:livingrock>, <ore:gearWood>, <ore:livingrock>], [<ore:livingrock>, <ore:livingrock>, <ore:livingrock>]]);
recipes.addShaped(<modularmachineryaddons:blockfluxprovideroutput>, [[<ore:livingrock>, <ore:dyePurple>, <ore:livingrock>], [<ore:livingrock>, <ore:dyePurple>, <ore:livingrock>], [<ore:livingrock>, <ore:gearWood>, <ore:livingrock>]]);
recipes.addShaped(<minecraft:sign> * 6, [[<ore:lumber>, <ore:lumber>, <ore:lumber>], [<ore:lumber>, <ore:lumber>, <ore:lumber>], [null, <ore:stickWood>, null]]);
recipes.addShaped(<botania:forestdrum>, [[<ore:livingwood>, <tfc:hide/raw/medium>, <ore:livingwood>], [<ore:livingwood>, <botania:grasshorn>, <ore:livingwood>], [<ore:livingwood>, <tfc:hide/raw/medium>, <ore:livingwood>]]);
recipes.addShaped(<botania:forestdrum:2>, [[<ore:livingwood>, <tfc:hide/raw/medium>, <ore:livingwood>], [<ore:livingwood>, <botania:grasshorn:1>, <ore:livingwood>], [<ore:livingwood>, <tfc:hide/raw/medium>, <ore:livingwood>]]);
recipes.addShaped(<tfc:sluice>, [[null, null, <ore:clay>], [<ore:clay>, <ore:clay>, <ore:lumber>], [<ore:lumber>, <ore:lumber>, <ore:lumber>]]);
recipes.addShaped(<tfc:sluice> * 2, [[null, null, <ore:concrete>], [<ore:concrete>, <ore:concrete>, <ore:concrete>]]);
recipes.addShaped(<embers:reactor>, [[<embers:blasting_core>, <ore:blockSilver>, <embers:blasting_core>], [<embers:blasting_core>, <thaumcraft:mechanism_simple>, <embers:blasting_core>], [<ore:blockSteel>, <thaumcraft:mechanism_simple>, <ore:blockSteel>]]);
recipes.addShaped(<embers:boiler>, [[<ore:ingotCopper>, <ore:ingotCopper>, <ore:ingotCopper>], [<ore:barsIron>, <embers:aspectus_dawnstone>, <ore:barsIron>], [<ore:concrete>, <embers:aspectus_dawnstone>, <ore:concrete>]]);
recipes.addShaped(<embers:ember_activator>, [[<ore:ingotCopper>, <ore:ingotCopper>, <ore:ingotCopper>], [<ore:barsIron>, <ore:ingotCopper>, <ore:barsIron>], [<ore:concrete>, <ore:concrete>, <ore:concrete>]]);
recipes.addShaped(<railcraft:track_flex_reinforced> * 32, [[<ore:ingotSteel>, <ore:concrete>, <ore:ingotSteel>], [<ore:ingotSteel>, <ore:rodWroughtIron>, <ore:ingotSteel>], [<ore:ingotSteel>, <ore:concrete>, <ore:ingotSteel>]]);
recipes.addShaped(<embers:ancient_motive_core>, [[<tetra:metal_scrap>, <tetra:metal_scrap>, <tetra:metal_scrap>], [<embers:blasting_core>, <tetra:quick_latch>, <embers:blasting_core>], [<tetra:metal_scrap>, <tetra:metal_scrap>, <tetra:metal_scrap>]]);
recipes.addShaped(<chisel:chisel_iron>, [[<ore:stickWood>, <ore:chiselHead>]]);
recipes.addShaped(<signals:cart_engine>, [[<embers:steam_engine>], [<ore:plateIron>]]);
recipes.addShaped(<signals:chunkloader_upgrade>, [[<railcraft:worldspike:3>], [<ore:plateIron>]]);
recipes.addShaped(<signals:block_signal> * 8, [[<ore:dustRedstone>, <ore:plateIron>], [<ore:dustRedstone>, <ore:blockGlass>]]);
recipes.addShaped(<signals:block_signal> * 8, [[<ore:plateIron>, <ore:dustRedstone>], [<ore:blockGlass>, <ore:dustRedstone>]]);
recipes.addShaped(<minecraft:paper>, [[<ore:petalWhite>, <ore:petalWhite>, <ore:petalWhite>], [<ore:petalWhite>, <ore:petalWhite>, <ore:petalWhite>]]);
recipes.addShaped(<projectred-integration:gate:4>, [[<ore:gemQuartz>, <ore:ingotRedAlloy>, <ore:gemQuartz>], [<ore:concrete>, <ore:concrete>, <ore:concrete>]]);
recipes.addShaped(<immersiveengineering:wirecoil:5> * 12, [[<ore:ingotRedAlloy>, <ore:ingotRedAlloy>, <ore:ingotRedAlloy>]]);
recipes.addShaped(<immersivepetroleum:speedboat>, [[<ore:plankTreatedWood>, null, <embers:blasting_core>], [<ore:plankTreatedWood>, <ore:plankTreatedWood>, <ore:plankTreatedWood>]]);
recipes.addShaped(<tfc:crucible>, [[<tfc:ceramics/fired/fire_brick>, null, <tfc:ceramics/fired/fire_brick>], [<tfc:ceramics/fired/fire_brick>, null, <tfc:ceramics/fired/fire_brick>], [<tfc:ceramics/fired/fire_brick>, <tfc:ceramics/fired/fire_brick>, <tfc:ceramics/fired/fire_brick>]]);
recipes.addShaped(<tfc:blast_furnace>, [[<tetra:metal_scrap>, <tetra:metal_scrap>, <tetra:metal_scrap>], [<tfc:ceramics/fired/fire_brick>, <tetra:vent_plate>, <tfc:ceramics/fired/fire_brick>], [<tfc:ceramics/fired/fire_brick>, <tetra:forged_bolt>, <tfc:ceramics/fired/fire_brick>]]);
recipes.addShaped(<tfc:alabaster_brick> * 24, [[<ore:concrete>, <ore:concrete>, <ore:concrete>], [<ore:gemQuartz>, <ore:gemQuartz>, <ore:gemQuartz>]]);
recipes.addShaped(<tfc:alabaster_brick> * 24, [[<ore:gemQuartz>, <ore:gemQuartz>, <ore:gemQuartz>], [<ore:concrete>, <ore:concrete>, <ore:concrete>]]);
recipes.addShaped(<tfc:alabaster/raw/plain> * 4, [[<ore:gemQuartz>, <ore:concrete>], [<ore:concrete>, <ore:gemQuartz>]]);
recipes.addShaped(<tfc:alabaster/raw/plain> * 4, [[<ore:concrete>, <ore:gemQuartz>], [<ore:gemQuartz>, <ore:concrete>]]);
recipes.addShaped(<tetra:journal>, [[null, <ore:ingotUnknown>, null], [<ore:ingotUnknown>, <ore:gearStone>, <ore:ingotUnknown>], [null, <ore:ingotUnknown>, null]]);
recipes.addShaped(<embers:codex>, [[<ore:ingotUnknown>], [<tetra:vent_plate>], [<ore:ingotUnknown>]]);
recipes.addShaped(<astralsorcery:blockmachine:1> * 2, [[null, <ore:livingrock>, <ore:livingwood>], [<ore:livingwoodTwig>, <ore:livingwoodTwig>, <ore:livingwood>]]);
recipes.addShaped(<ic2:scaffold> * 2, [[<ore:stickWood>, <ore:stickWood>, <ore:stickWood>], [null, <ore:stickWood>, null], [<ore:stickWood>, null, <ore:stickWood>]]);
recipes.addShaped(<ic2:scaffold> * 4, [[<ore:lumber>, <ore:lumber>, <ore:lumber>], [null, <ore:stickWood>, null], [<ore:stickWood>, null, <ore:stickWood>]]);
recipes.addShaped(<embers:stamper>, [[<ore:concrete>, <ore:plateIron>, <ore:concrete>], [<ore:ingotCopper>, <ore:plateIron>, <ore:ingotCopper>], [<ore:concrete>, null, <ore:concrete>]]);
recipes.addShaped(<embers:stamper_base>, [[<ore:plateIron>, null, <ore:plateIron>], [<ore:concrete>, <ore:plateIron>, <ore:concrete>]]);

recipes.addShaped(<thaumcraft:phial> * 64, [[null, <ore:clay>, null], [<ore:gemExquisiteJade>, null, <ore:gemExquisiteJade>], [null, <ore:gemExquisiteJade>, null]]);
recipes.addShaped(<thaumcraft:phial> * 32, [[null, <ore:clay>, null], [<ore:gemFlawlessJade>, null, <ore:gemFlawlessJade>], [null, <ore:gemFlawlessJade>, null]]);
recipes.addShaped(<thaumcraft:phial> * 16, [[null, <ore:clay>, null], [<ore:gemJade>, null, <ore:gemJade>], [null, <ore:gemJade>, null]]);
recipes.addShaped(<thaumcraft:phial> * 8, [[null, <ore:clay>, null], [<ore:gemFlawedJade>, null, <ore:gemFlawedJade>], [null, <ore:gemFlawedJade>, null]]);
recipes.addShaped(<thaumcraft:phial> * 4, [[null, <ore:clay>, null], [<ore:gemChippedJade>, null, <ore:gemChippedJade>], [null, <ore:gemChippedJade>, null]]);
recipes.addShaped(<ic2:resource:14> * 2, [[<ore:plateBlackSteel>, <ore:plateBlackSteel>], [<ore:plateBlackSteel>, <ore:plateBlackSteel>]]);
recipes.addShaped(<ic2:te:22>, [[<ore:plateLead>, <thaumcraft:mind>, <ore:plateLead>], [<ic2:te:24>, <ic2:te:24>, <ic2:te:24>], [<ore:plateLead>, <thaumcraft:mind>, <ore:plateLead>]]);
recipes.addShaped(<ic2:te:24>, [[<ore:plateLead>, <ore:plateLead>, <ore:plateLead>], [<ore:plateLead>, <thaumcraft:mechanism_simple>, <ore:plateLead>], [<ore:plateLead>, <ore:plateLead>, <ore:plateLead>]]);
recipes.addShaped(<ic2:te:23>, [[null, <thaumcraft:mechanism_simple>, null], [<thaumcraft:mechanism_simple>, <ic2:resource:14>, <thaumcraft:mechanism_simple>], [null, <thaumcraft:mechanism_simple>, null]]);
recipes.addShaped(<ic2:te:26>, [[null, <minecraft:redstone>, null], [<minecraft:redstone>, <ic2:resource:14>, <minecraft:redstone>], [null, <minecraft:redstone>, null]]);
recipes.addShaped(<ic2:te:25>, [[null, <tfc:brass_mechanisms>, null], [<ore:barsIron>, <ic2:resource:14>, <ore:barsIron>], [null, <tfc:brass_mechanisms>, null]]);
recipes.addShaped(<railcraft:tank_steel_valve>, [[null, <tfc:brass_mechanisms>, null], [<ore:barsIron>, <railcraft:tank_steel_wall>, <ore:barsIron>], [null, <tfc:brass_mechanisms>, null]]);
recipes.addShaped(<railcraft:tank_iron_valve>, [[null, <tfc:brass_mechanisms>, null], [<ore:barsIron>, <railcraft:tank_iron_wall>, <ore:barsIron>], [null, <tfc:brass_mechanisms>, null]]);
recipes.addShaped(<mekanism:basicblock:15>, [[null, <tfc:brass_mechanisms>, null], [<ore:barsIron>, <mekanism:basicblock2>, <ore:barsIron>], [null, <tfc:brass_mechanisms>, null]]);
recipes.addShaped(<mekanism:basicblock:14>, [[null, <ore:circuitAdvanced>, null], [<ore:circuitAdvanced>, <mekanism:basicblock2>, <ore:circuitAdvanced>], [null, <ore:circuitAdvanced>, null]]);
recipes.addShaped(<mekanism:basicblock2> * 16, [[<ore:ingotIgnatius>, <ore:sheetBerylliumCopper>, <ore:ingotIgnatius>], [<ore:sheetBerylliumCopper>, null, <ore:sheetBerylliumCopper>], [<ore:ingotIgnatius>, <ore:sheetBerylliumCopper>, <ore:ingotIgnatius>]]);
recipes.addShaped(<thermalexpansion:capacitor>, [[<ore:dustRedstone>, <ore:ingotCopper>, <ore:dustRedstone>], [<ore:ingotLead>, <ore:blockSulfur>, <ore:ingotLead>], [<ore:ingotLead>, <ore:dustRedstone>, <ore:ingotLead>]]);
recipes.addShaped(<thermalexpansion:capacitor>, [[<ore:alloyBasic>, <ore:ingotCopper>, <ore:alloyBasic>], [<ore:dustSulfur>, <ore:dustSulfur>, <ore:dustSulfur>], [<ore:ingotLead>, <cyberware:lower_organs_upgrades:2>, <ore:ingotLead>]]);
recipes.addShaped(<ic2:overclocked_heat_vent>, [[<railcraft:charge:5>, <ic2:heat_vent>], [<ore:gearLumium>, null]]);
recipes.addShaped(<ic2:component_heat_exchanger> * 2, [[null, <ic2:heat_exchanger>, null], [<ic2:heat_exchanger>, <ore:gearLumium>, <ic2:heat_exchanger>], [null, <ic2:heat_exchanger>, null]]);
recipes.addShaped(<ic2:te:34>, [[<ore:plateIron>, <ic2:crafting:7>, <ore:plateIron>], [<thermaldynamics:duct_16:1>, <thermaldynamics:duct_16:1>, <thermaldynamics:duct_16:1>], [<thermaldynamics:duct_16:1>, <thermaldynamics:duct_16:1>, <thermaldynamics:duct_16:1>]]);
recipes.addShaped(<ic2:te:31>, [[<thermaldynamics:duct_16:1>, <thermaldynamics:duct_16:1>, <thermaldynamics:duct_16:1>], [<thermaldynamics:duct_16:1>, <thermaldynamics:duct_16:1>, <thermaldynamics:duct_16:1>], [<ore:plateIron>, <ic2:crafting:7>, <ore:plateIron>]]);
recipes.addShaped(<mysticalmechanics:gear_fan> * 8, [[<ore:sheetIron>, null, <tfc:metal/sheet/wrought_iron>], [null, <ore:stickIron>, null], [<ore:sheetIron>, null, <ore:sheetIron>]]);
recipes.addShaped(<botania:manatablet>, [[<ore:livingrock>, <ore:powderMana>, <ore:livingrock>], [<ore:powderMana>, <ore:clothManaweave>, <ore:powderMana>], [<ore:livingrock>, <ore:powderMana>, <ore:livingrock>]]);
recipes.addShaped(<botania:manaresource:6>, [[<ore:dustRedstone>, <ore:straw>]]);
recipes.addShaped(<immersiveengineering:metal_decoration0:5>, [[<ore:plateSteel>, <embers:blasting_core>, <ore:plateSteel>], [<ore:ingotBlackSteel>, <thaumcraft:mechanism_simple>, <ore:ingotBlackSteel>], [<ore:plateSteel>, <embers:blasting_core>, <ore:plateSteel>]]);
recipes.addShaped(<immersiveengineering:metal_decoration1:1> * 6, [[<ore:ingotSteel>, <ore:ingotSteel>, <ore:ingotSteel>], [null, <ore:stickIron>, null], [<ore:stickIron>, <ore:ingotSteel>, <ore:stickIron>]]);
recipes.addShaped(<minecraft:glass>, [[<betternether:quartz_glass>]]);
recipes.addShaped(<embers:heat_coil>, [[<ore:ingotCopper>, <ore:ingotCopper>, <ore:ingotCopper>], [<ore:ingotCopper>, <ore:ingotCopper>, <ore:ingotCopper>], [<ore:concrete>, <ore:barsIron>, <ore:concrete>]]);
recipes.addShaped(<immersiveengineering:chemthrower>, [[null, <immersiveengineering:toolupgrade>, <ore:gungripWood>], [<immersiveengineering:toolupgrade>, <thaumcraft:metal_alchemical>, <ore:gungripWood>], [<thaumcraft:metal_alchemical>, null, null]]);
recipes.addShaped(<thermaldynamics:duct_32:1> * 4, [[<ore:plateTin>, <ore:circuitBasic>, <ore:plateTin>]]);
recipes.addShaped(<thermaldynamics:duct_32> * 4, [[<railcraft:glass:*>, <ore:circuitBasic>, <railcraft:glass:*>]]);
recipes.addShaped(<embers:steam_engine> * 4, [[<thermaldynamics:duct_16:1>, <thermaldynamics:duct_16:1>, <thermaldynamics:duct_16:1>], [<thermaldynamics:duct_16:1>, <embers:blasting_core>, <embers:blasting_core>], [<ore:concrete>, <ore:concrete>, <ore:concrete>]]);
recipes.addShaped(<tfctech:metal/copper_wire>, [[null, <ore:nuggetCopper>, <ore:nuggetCopper>], [null, <ore:nuggetCopper>, null], [<ore:nuggetCopper>, <ore:nuggetCopper>, null]]);
recipes.addShaped(<extrautils2:analogcrafter>, [[<ore:ingotCopper>, <mystgears:crafter_mechanical>, <ore:ingotCopper>], [<ore:ingotCopper>, <thaumcraft:mind>, <ore:ingotCopper>]]);
recipes.addShaped(<extrautils2:analogcrafter>, [[<ore:ingotCopper>, <thaumcraft:pattern_crafter>, <ore:ingotCopper>], [<ore:ingotCopper>, <thaumcraft:mind>, <ore:ingotCopper>]]);
recipes.addShaped(<embers:mini_boiler>, [[<thermaldynamics:duct_16:1>, <thermaldynamics:duct_16:1>, <ore:plateIron>], [<thermaldynamics:duct_16:1>, <thermaldynamics:duct_16:1>, <ore:ingotCopper>], [<thermaldynamics:duct_16:1>, <thermaldynamics:duct_16:1>, <ore:plateIron>]]);
recipes.addShaped(<clothesline:clothesline_anchor> * 2, [[<ore:barsIron>, <ore:stickIron>, <ore:barsIron>], [null, <ore:stickIron>, null]]);
recipes.addShaped(<railcraft:glass:7> * 5, [[<ore:stickIron>, <ore:blockGlass>, <ore:stickIron>], [<ore:dustSaltpeter>, <ore:blockGlass>, <ore:dustSaltpeter>], [<ore:stickIron>, <ore:blockGlass>, <ore:stickIron>]]);
recipes.addShaped(<railcraft:glass:7> * 3, [[<ore:stickIron>, <ore:blockGlass>, <ore:stickIron>], [<ore:gunpowder>, <ore:blockGlass>, <ore:gunpowder>], [<ore:stickIron>, <ore:blockGlass>, <ore:stickIron>]]);
recipes.addShaped(<quark:framed_glass> * 4, [[<ore:stickIron>, <ore:blockGlass>, <ore:stickIron>], [<ore:blockGlass>, <ore:blockGlass>, <ore:blockGlass>], [<ore:stickIron>, <ore:blockGlass>, <ore:stickIron>]]);
recipes.addShaped(<embers:mixer>, [[<ore:plateIron>, <ore:stickIron>, <ore:plateIron>], [<ore:plateIron>, <ore:stickIron>, <ore:plateIron>], [<ore:concrete>, <ore:stickIron>, <ore:concrete>]]);
recipes.addShaped(<embers:block_furnace>, [[<ore:concrete>, null, <ore:concrete>], [<ore:concrete>, <ore:plateIron>, <ore:concrete>], [<ore:plateIron>, <ore:ingotCopper>, <ore:plateIron>]]);

recipes.addShaped(<embers:copper_cell>, [[<ore:stickIron>, <ore:ingotCopper>, <ore:concrete>], [<ore:ingotCopper>, <ore:ingotCopper>, <ore:ingotCopper>], [<ore:concrete>, <ore:ingotCopper>, <ore:stickIron>]]);
recipes.addShaped(<embers:copper_cell>, [[<ore:concrete>, <ore:ingotCopper>, <ore:stickIron>], [<ore:ingotCopper>, <ore:ingotCopper>, <ore:ingotCopper>], [<ore:stickIron>, <ore:ingotCopper>, <ore:concrete>]]);
recipes.addShaped(<embers:ember_emitter> * 2, [[null, <ore:ingotCopper>, null], [<ore:stickIron>, <ore:ingotCopper>, <ore:stickIron>], [<ore:stickIron>, <ore:concrete>, <ore:stickIron>]]);
recipes.addShaped(<embers:ember_receiver> * 2, [[<ore:stickIron>, <ore:ingotCopper>, <ore:stickIron>], [null, <ore:concrete>, null]]);
recipes.addShaped(<embers:ember_relay> * 4, [[<ore:ingotCopper>], [<ore:stickIron>], [<ore:concrete>]]);
recipes.addShaped(<integrateddynamics:squeezer>, [[<ore:stickIron>, <ore:plateIron>, <ore:stickIron>], [<ore:stickIron>, null, <ore:stickIron>], [<ore:concrete>,<ore:concrete>,<ore:concrete>]]);
recipes.addShaped(<mystgears:windup_box> * 2, [[<ore:plateIron>, null, <ore:plateIron>], [<tfc:brass_mechanisms>, <tfc:brass_mechanisms>, <ore:stickIron>], [<ore:plateIron>, null, <ore:plateIron>]]);
recipes.addShaped(<immersiveintelligence:metal_decoration:4> * 3, [[<ore:plateBrass>, <ore:dustRedstone>, <ore:plateBrass>], [<ore:ingotIron>, <ore:ingotIron>, <ore:ingotIron>], [<ore:plateBrass>, <ore:dustRedstone>, <ore:plateBrass>]]);
recipes.addShaped(<immersiveengineering:metal_decoration0:4> * 3, [[<ore:plateIron>, <ore:itemEnchantedFabric>, <ore:plateIron>], [<ore:ingotCopper>, <ore:ingotCopper>, <ore:ingotCopper>], [<ore:plateIron>, <ore:itemEnchantedFabric>, <ore:plateIron>]]);
recipes.addShaped(<immersiveengineering:metal_decoration0:4> * 2, [[<ore:plateIron>, <ore:leather>, <ore:plateIron>], [<ore:ingotCopper>, <ore:ingotCopper>, <ore:ingotCopper>], [<ore:plateIron>, <ore:leather>, <ore:plateIron>]]);
recipes.addShaped(<immersiveintelligence:metal_decoration:3> * 3, [[<ore:plankTreatedWood>, <ore:ingotCopper>, <ore:plankTreatedWood>], [<tfc:brass_mechanisms>, <tfc:brass_mechanisms>, <tfc:brass_mechanisms>], [<ore:plankTreatedWood>, <ore:ingotCopper>, <ore:plankTreatedWood>]]);
recipes.addShaped(<embers:mech_accessor>, [[null, <ore:hopper>, null], [<ore:concrete>, <ore:concrete>, <ore:concrete>]]);
recipes.addShaped(<embers:mech_actuator_single>, [[null, <mysticalmechanics:gearbox_frame>, null], [<ore:concrete>, <ore:concrete>, <ore:concrete>]]);
recipes.addShaped(<embers:mech_actuator>, [[null, <ore:concrete>, null], [<ore:concrete>, <mysticalmechanics:gearbox_frame>, <ore:concrete>], [null, <ore:concrete>, null]]);
recipes.addShaped(<minecraft:rail> * 64, [[<ore:stickIron>, <ore:concrete>, <ore:stickIron>], [<ore:stickIron>, <ore:stickIron>, <ore:stickIron>], [<ore:stickIron>, <ore:concrete>, <ore:stickIron>]]);
recipes.addShaped(<embers:mech_core>, [[<ore:hopper>], [<mysticalmechanics:gearbox_frame>]]);
recipes.addShaped(<questionablyimmersive:metal_device>, [[<ore:nuggetCopper>, <ore:dustRedstone>, <ore:nuggetCopper>], [<ore:nuggetCopper>, <ore:nuggetCopper>, <ore:nuggetCopper>]]);

recipes.addShaped(<minecraft:lever> * 4, [[<ore:stickIron>], [<ore:concrete>]]);
recipes.addShaped(<magneticraft:inserter> * 3, [[null, <ore:stickIron>, <ore:stickIron>], [<ore:stickIron>, <thaumcraft:mechanism_simple>, null], [<ore:concrete>, <ore:concrete>, <ore:concrete>]]);
recipes.addShaped(<magneticraft:inserter> * 2, [[null, <ore:stickIron>, <ore:stickIron>], [<ore:stickIron>, <tfc:brass_mechanisms>, null], [<ore:concrete>, <ore:concrete>, <ore:concrete>]]);
recipes.addShaped(<tfc:bellows> * 2, [[<ore:stickIron>, <ore:stickIron>, <ore:stickIron>], [<ore:leather>, <ore:leather>, <ore:leather>], [<ore:stickIron>, <ore:stickIron>, <ore:stickIron>]]);
recipes.addShaped(<advancedrocketry:landingpad>*2, [[<ore:concrete>, <ore:concrete>, <ore:concrete>], [<ore:concrete>, <ore:concrete>, <ore:concrete>], [<ore:concrete>, <ore:concrete>, <ore:concrete>]]);
recipes.addShaped(<advancedrocketry:launchpad>, [[<ore:concrete>, <ore:concrete>, <ore:concrete>], [<ore:concrete>, <ore:concrete>, <ore:concrete>]]);
recipes.addShaped(<minecraft:repeater>, [[<minecraft:redstone_torch>, <ore:dustRedstone>, <minecraft:redstone_torch>], [<ore:concrete>, <ore:concrete>, <ore:concrete>]]);
recipes.addShaped(<minecraft:comparator>, [[null, <ore:dustRedstone>, null], [<ore:dustRedstone>, <ore:gemQuartz>, <ore:dustRedstone>], [<ore:concrete>, <ore:concrete>, <ore:concrete>]]);
recipes.addShaped(<minecraft:redstone_torch> * 4, [[<ore:dustRedstone>], [<ore:stickIron>]]);
recipes.addShaped(<embers:item_request> * 4, [[<ore:nuggetQuicksilver>, <ore:nuggetQuicksilver>, <ore:nuggetQuicksilver>], [<ore:nuggetQuicksilver>, <thaumcraft:mind>, <ore:nuggetQuicksilver>], [<ore:nuggetLead>, <ore:nuggetLead>, <ore:nuggetLead>]]);
recipes.addShaped(<pneumaticcraft:omnidirectional_hopper> * 2, [[<ore:plateSteel>, null, <ore:plateSteel>], [null, <ore:plateSteel>, null], [null, <ore:plateSteel>, null]]);
recipes.addShaped(<minecraft:hopper> * 4, [[<ore:plateWroughtIron>, null, <ore:plateWroughtIron>], [null, <ore:plateWroughtIron>, null], [null, <ore:plateWroughtIron>, null]]);

recipes.addShaped(<embers:clockwork_attenuator>, [[<ore:nuggetGold>, <minecraft:redstone>, <ore:nuggetGold>], [<ore:nuggetGold>, <ore:nuggetGold>, <ore:nuggetGold>]]);
recipes.addShaped(<mystgears:mechanical_dial>, [[<ore:nuggetBrass>, <tfc:brass_mechanisms>, <ore:nuggetBrass>], [<ore:nuggetBrass>, <ore:nuggetBrass>, <ore:nuggetBrass>]]);
recipes.addShaped(<embers:ember_bulb>, [[<ore:ingotCopper>, <ore:sheetWroughtIron>, <ore:ingotCopper>], [<ore:blockGlass>, <embers:crystal_ember>, <ore:blockGlass>], [<ore:blockGlass>, <ore:blockGlass>, <ore:blockGlass>]]);
recipes.addShaped(<embers:caster_orb>, [[<embers:crystal_ember>, <embers:crystal_ember>, <embers:crystal_ember>], [<ore:ingotDawnstone>, <embers:crystal_ember>, <ore:ingotDawnstone>], [null, <ore:ingotDawnstone>, null]]);
recipes.addShaped(<embers:diffraction_barrel>, [[<ore:barsIron>, <ore:ingotDawnstone>, null], [<ore:barsIron>, <ore:barsIron>, <ore:ingotDawnstone>], [<ore:barsIron>, <ore:ingotDawnstone>, null]]);
recipes.addShaped(<embers:jet_augment>, [[<ore:gunpowder>, <ore:ingotDawnstone>, null], [<ore:gunpowder>, <ore:gunpowder>, <ore:ingotDawnstone>], [<ore:gunpowder>, <ore:ingotDawnstone>, null]]);
recipes.addShaped(<embers:charger>, [[<ore:ingotCopper>, <ore:plateIron>, <ore:ingotCopper>], [<embers:aspectus_dawnstone>, null, <embers:aspectus_dawnstone>], [<ore:ingotCopper>, <ore:plateIron>, <ore:ingotCopper>]]);
recipes.addShaped(<embers:alchemy_pedestal>, [[<embers:aspectus_dawnstone>, <embers:aspectus_dawnstone>, <embers:aspectus_dawnstone>], [<minecraft:nether_brick>, <ore:blockCopper>, <minecraft:nether_brick>], [<minecraft:nether_brick>, <ore:blockCopper>, <minecraft:nether_brick>]]);
recipes.addShaped(<embers:alchemy_tablet>, [[null, <embers:aspectus_dawnstone>, null], [<embers:aspectus_dawnstone>, <embers:aspectus_dawnstone>, <embers:aspectus_dawnstone>], [<minecraft:nether_brick>, <embers:aspectus_dawnstone>, <minecraft:nether_brick>]]);
recipes.addShaped(<embers:beam_splitter>, [[<embers:aspectus_dawnstone>, <embers:ember_relay>, <embers:aspectus_dawnstone>]]);
recipes.addShaped(<embers:ember_pulser>, [[null, <embers:aspectus_dawnstone>, null], [<embers:aspectus_dawnstone>, <embers:ember_emitter>, <embers:aspectus_dawnstone>]]);
recipes.addShaped(<embers:ember_funnel>, [[<embers:aspectus_dawnstone>, <embers:ember_receiver>, <embers:aspectus_dawnstone>], [null, <embers:aspectus_dawnstone>, null]]);
recipes.addShaped(<minecraft:cauldron>, [[<ore:nuggetBlackBronze>, null, <ore:nuggetBlackBronze>], [<ore:nuggetBlackBronze>, null, <ore:nuggetBlackBronze>], [<ore:nuggetBlackBronze>, <ore:sheetBlackBronze>, <ore:nuggetBlackBronze>]]);
recipes.addShaped(<thaumcraft:table_stone>, [[<ore:slabStonePolished>, <ore:slabStonePolished>, <ore:slabStonePolished>], [<ore:stonePolished>, null, <ore:stonePolished>]]);
recipes.addShaped(<minecraft:glass_bottle>, [[<ore:blockGlass>, null, <ore:blockGlass>], [null, <ore:blockGlass>, null]]);
recipes.addShaped(<clothesline:clothesline_anchor>, [[<ore:nuggetIron>, <ore:nuggetIron>, <ore:nuggetIron>], [null, <ore:stickIron>, null]]);
recipes.addShaped(<botania:opencrate:1>, [[<ore:powderMana>, <ore:workbench>, <ore:powderMana>], [<ore:powderMana>, <botania:opencrate>, <ore:powderMana>], [<ore:powderMana>, <ore:powderMana>, <ore:powderMana>]]);

recipes.addShaped(<ic2:crafting:8>, [[<thermaldynamics:duct_16:1>, <thermaldynamics:duct_16:1>, <thermaldynamics:duct_16:1>], [<thermaldynamics:duct_16:1>, <thermaldynamics:duct_16:1>, <thermaldynamics:duct_16:1>]]);
recipes.addShaped(<thermaldynamics:duct_16:1> * 6, [[<ore:plateCopper>, <ore:plateCopper>, <ore:plateCopper>]]);
recipes.addShaped(<minecraft:cauldron>, [[<ore:nuggetIron>, null, <ore:nuggetIron>], [<ore:nuggetIron>, null, <ore:nuggetIron>], [<ore:nuggetIron>, <ore:plateIron>, <ore:nuggetIron>]]);
recipes.addShaped(<thermaldynamics:duct_16:1> * 8, [[<thermaldynamics:duct_16>, <thermaldynamics:duct_16>, <thermaldynamics:duct_16>], [<thermaldynamics:duct_16>, <ore:ingetAnyBronze>, <thermaldynamics:duct_16>], [<thermaldynamics:duct_16>, <thermaldynamics:duct_16>, <thermaldynamics:duct_16>]]);
recipes.addShaped(<thermaldynamics:duct_16> * 8, [[<thermaldynamics:duct_16:1>, <thermaldynamics:duct_16:1>, <thermaldynamics:duct_16:1>], [<thermaldynamics:duct_16:1>, <ore:blockGlassColorless>, <thermaldynamics:duct_16:1>], [<thermaldynamics:duct_16:1>, <thermaldynamics:duct_16:1>, <thermaldynamics:duct_16:1>]]);
recipes.addShaped(<immersiveengineering:metal_device1:6> * 24, [[<ore:plateSteel>, <ore:plateSteel>, <ore:plateSteel>],[null,null,null], [<ore:plateSteel>, <ore:plateSteel>, <ore:plateSteel>]]);
recipes.addShaped(<tconstruct:wooden_hopper>, [[<ore:lumberOak>, null, <ore:lumberOak>], [<ore:lumberOak>, <ore:gearWood>, <ore:lumberOak>], [null, <ore:lumberOak>, null]]);
recipes.addShaped(<ic2:nuclear:4>, [[<ore:blockUranium>, <ore:blockUranium>, <ore:blockUranium>], [<ore:blockUranium>, <ic2:nuclear:3>, <ore:blockUranium>], [<ore:blockUranium>, <ore:blockUranium>, <ore:blockUranium>]]);

recipes.addShaped(<ic2:overclocked_heat_vent> * 2, [[<ore:stickElectrum>, <cyberware:component:2>, <ore:stickElectrum>], [<ore:stickElectrum>, <ore:fanSteel>, <ore:stickElectrum>], [<ore:stickElectrum>, <cyberware:component:2>, <ore:stickElectrum>]]);
recipes.addShaped(<ic2:advanced_heat_exchanger>, [[null, <ic2:heat_exchanger>, null], [<ore:dustDiamond>, <ore:circuitBasic>, <ore:dustDiamond>], [null, <ic2:heat_exchanger>, null]]);
recipes.addShaped(<ic2:component_heat_exchanger> * 2, [[null, <tfc:ceramics/fired/fire_brick>, null], [<ic2:heat_exchanger>, <ore:plateElectrum>, <ic2:heat_exchanger>], [null, <tfc:ceramics/fired/fire_brick>, null]]);
recipes.addShaped(<ic2:reactor_heat_exchanger> * 2, [[<ic2:heat_exchanger>, <ic2:crafting:7>, <ic2:heat_exchanger>]]);
recipes.addShaped(<ic2:heat_exchanger> * 4, [[null, <ore:plateIron>, null], [<ore:plateIron>, <ic2:crafting:7>, <ore:plateIron>], [null, <ore:plateIron>, null]]);
recipes.addShaped(<ic2:component_heat_vent>, [[null, <ore:plasticLightGray>, null], [<ore:plasticLightGray>, <ic2:heat_vent>, <ore:plasticLightGray>], [null, <ore:plasticLightGray>, null]]);
recipes.addShaped(<ic2:advanced_heat_vent>, [[null, <ore:quicksilver>, null], [<ic2:heat_vent>, <ore:dustDiamond>, <ic2:heat_vent>], [null, <ore:quicksilver>, null]]);
recipes.addShaped(<ic2:heat_vent> * 2, [[<ore:barsIron>, <ore:barsIron>, <ore:barsIron>], [<ore:barsIron>, <mysticalmechanics:gear_fan>, <ore:barsIron>], [<ore:barsIron>, <ore:barsIron>, <ore:barsIron>]]);

